### ISSUE TITLE
O> Working Group on the use of the Social Ledger by RChain

### ISSUE THREAD

**Issue by entropee** [rchain/bounties#113]
[Go here and use the Dig A and Join the Committee](https://rchain.divvydao.net/community/pl/s9w46xihj3bg3csn4ngiu1gj8c)

[What is the Social Ledger?](https://docs.google.com/document/d/1L0GieXDlJ1CEdOSlwvlRAYjZ_ANy3c7DNpNf0bXZj34/edit)

Why is Social Ledger so good?

Why is it important to RChain?

Is there a problem?

Is the Mattermost / social ledger work environment conducive to smart contracts?

Who is behind the Social Ledger project?

Does the Social Ledger make use of decentralized computing or the blockchain?

What is the work-out-loud concept?

How will the SCOTUOSLBR be formed?

What options for the adoption of social ledger are available now?

What level of development is the "/dig a" command?

Can the "/dig a" command be implemented on Discord or Slack?

Is implementing the "/dig a" command the only way for a project to implement social ledger?

Is there any urgency around this issue? Yes.

**Comment by dckc** [comment]
I see a $5k budget proposed for this month; perhaps the work is visible in mattermost or something, but that's behind a login. Somebody summarize the recent / current work, please?

**Comment by aviationhacker** [comment]
@jimscarver you would be better qualified to answer this rather than me. 

At this stage, most of this work has been mixed in with development of the Social Ledger v2 in terms of making the new SL something that will satisfy the needs of Rchain and can be moved onto Rchain in a relatively seamless manner, while to some extent futureproofing it so that it can grow as Rchain does and be modified to suit.

Because of this, the design itself is not yet formalized and is being tested/modified as we speak. Most of this work has been occurring during the noob learning sessions, and has been focused on the basic elements - building a graphQL server, and now adding OAuth2 into that server so that immediate needs are met. 
In terms of architecture design, the Google Slides link below would probably give you a better idea of what we're up to at this stage, specifically slides 78 - 80.
https://drive.google.com/open?id=1z8_Qt4fHAHuVKFKBh3Wq8-w9SL4tYxc3w6BYmHc0kh8

Hope this helps a little!

**Comment by dckc** [comment]
a graphQL server sounds interesting; point me at the source code, please?

**Comment by jimscarver** [comment]
We have gone through a tutorial of connecting an sqlite database, a rest api and mongodb datasources. We are just learning. I committed the reactQL starter kit at https://github.com/DigitalLifeCollective/basecamp where I have admin rights. This is just the starting point. Notes are in the [noob log](https://docs.google.com/document/d/1HNIq_sBupkrtO3yuZT_5OlBWw8UEM3O9vNeQGtq9dpw/edit#)

**Comment by TrenchFloat** [comment]
> I suggest [Gary] report SL use in RChain here regularly
@entropee Does that work for you? Any ideas on how often you can update us?

**Comment by entropee** [comment]
I can update on a regular schedule. Maybe weekly, or monthly, @TrenchFloat
