### ISSUE TITLE
O> Compensation Committee: Determine meeting times

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#164]
The compensation committee probably doesn't need to meet weekly, but should define the date and time for those meetings.

**Comment by kennyrowe** [comment]
We can also do meetings on a ad-hoc basis. This would be my preference for this committee since it's business is infrequent.

That being said we should set a meeting to review our first action which will be to set board compensation.

It should also be stated that since I am a board member, I will be recusing myself from any vote.

**Comment by patrick727** [comment]
@kennyrowe ok awesome, 

Well give Lisa some time to provide her feedback. 

How about next week. Monday & Tuesdays are pretty open for me.

**Comment by dckc** [comment]
This issue seems to be overtaken by events.

I suppose interested people should tune in to the [#comp-committee](https://discordapp.com/channels/375365542359465989/398198181881577473) channel.
