### ISSUE TITLE
O> Review of Community Reward Program by compensation committee

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#165]
I believe that a perfect role for the compensation committee is to drive the community reward program forward. 

This could happen as an agenda item in the meetings. Couple things to work out though are 

1. What issues are being worked on within an SOW's scope
2. What issues are being worked on within a volunteer position scope?

maybe if the "drivers" label issues as "community" or "co-operators" then that could help

**Comment by kennyrowe** [comment]
Yes this could also fall under the preview of the committee. 

@lapin7 Could you comment on what is working well and what can still be improved with the process?

One comment I've received is that community members should be responsible for submitting their own invoices.

**Comment by dckc** [comment]
Re what can be improved: yes, let's please narrow the scope of this. The program can always be improved. What's at least one thing that is worth changing? What would be enough of a change to close this?

**Comment by patrick727** [comment]
@dckc thanks for help narrowing this down. 

I think that one small change could simply be that at least 1 Member of the compensation committee has approved the budget of the of an issue and that 0 have objected. 

If HJ is on the committee, then it runs smoothly. and if the committee is tasked, every other week to review the program then they can recommend and objection. 

An objection can result from
- an issue that is within the scope of someones SOW or Employee responsibilities
- an issues budget is being gamed for way above typical rewards(subjective but still a point to consider as we grow very large)
- an issue not being completed
- an issue where they feel the budget is too low and would propose a larger budget

idk how best to handle something like an objection but i do want that to be considered, albeit used very infrequently.

Checks and balances

**Comment by Ojimadu** [comment]
I think the compensation committee should have the final say when an issue is objected to. If an issue is objected to, the committee might review it if there's a mistake or if the issue deserves more reward if a majority of the if more members of the committee agreed to improve the reward for a certain issue then that'll be it if otherwise the member takes the reward as it is. 
The committee doesn't have to be perfect it just has to be fair enough.

**Comment by kitblake** [comment]
I second what @dckc just said. 
The Co-op is slowly but organically growing and we should avoid adding bureaucratic friction to processes. 
Someday we will need an arbitrating entity and the compensation committee would fit that purpose.

**Comment by n10n** [comment]
Agree with @dckc in general. Bring compensation committee into a community reward dispute or deciding on the amount of a bounty complicates the focus of the committee and managing individual bounties is out of their scope of work. Of course, the committee can help guide the budget for the reward program in general. We should have community members decide for it in some way. For example, a group of rotating community managers (monthly rotation) can help guide this situation.

**Comment by patrick727** [comment]
Thanks for the feedback. 

So I still lean towards the compensation committee meeting(maybe twice a month) and reviewing the decentralized program for "objections." 

I assume that individuals mostly won't care about the set budgets and will lean towards getting people as much as possible, which is a great thing, to a point. 

Example(maybe Lisa can help clarify) I do believe that as soon as the Co-op pays out RHOCs it has a tax liability for those. 

What about this?

The committee doesn't have to sign off on any budgets, but will meet(twice or once a month) and review and if 3 or more of the members object a budget then it must be revised? 

"Silence compiles consent" would be the time of invoice. So if there are no objections before the invoices go out, then it's considered approved. The committee can also share in the reward issue and in the discord channel every meeting something like "0 Objections, great work guys" just so there is no uncertainty. 

I don't think that will slow things down, but it provides a small check & balance system. 

I like the engagement with this guys, much appreciated

**Comment by dckc** [comment]
Good point: the invoicing step already constrains the bandwidth of the system.

**Comment by lapin7** [comment]
**Let's avoid bureaucratic hurdles.**

The way I see it it that the system is fine as it is. The committee can talk about it's features but not about it's execution. That becomes very cumbersome. In stead we just simply trust the fairness of collaborators and of course the social control under collaborators.

**SoW versus bounties**
Simple rule: A member who get's a monthly reward, doesn't get bounties. The bounties are listed on the invoice in order to give more insight in what members are doing for their reward. The calculation is such, that bounty-rewards are summed up and subtracted from the SoW-reward. 

The final goal is that the SoW amount is covered by bounties.
Even when issues are out of scope of the SoW, the payee doesn't get more then is agreed upon in the SoW. This is to avoid discussions about IN scope and OUT scope.

Example:
The SoW is $8000 per month
The bounties are $1700 in total for this month

The Invoice says:

Description | Amount
-- | --
SoW November | 6300
Bounties November | 1700
Total reward | 8000

In the ideal situation it would be:

Description | Amount
-- | --
SoW November | 0
Bounties November | 8000
Total reward | 8000



**Invoices**
_One comment is that community members should be responsible for submitting their own invoices._

In this system they do, but they get from the coop (me) a prepared invoice. The member can change as s/he see fit. The member sends an invoice-PDF to rchainfin@googlegroups.com. And the coop processes the payment of the invoice, meaning approving and checking.

**Approval**
The approval of the coop for the payment of the invoice is merely a formality. Quick action.
This is possible because the real approval has already been done through minimal three collaborators on the issue.

The setting of the budget goes the same. The committee doesn't have to interfere. The committee just trusts the decision of three collaborators to set a fair budget for the issue.

Please tell me what you think.

**Comment by lapin7** [comment]
**Tax Liability**

_Example(maybe Lisa can help clarify) I do believe that as soon as the Co-op pays out RHOCs it has a tax liability for those._

I understand the tax liability as that the coop has to give to the IRS a [1099 form](https://www.irs.gov/pub/irs-pdf/f1099msc.pdf) for each contractor that has been paid more then $600.

The data to be filled out are basically:
personal ID + total sum paid in USD in 2017

The coop get's this personal data from each contractor by the form [W9](https://www.irs.gov/pub/irs-pdf/fw9.pdf) for USA-citizens and form [W4](https://www.irs.gov/pub/irs-pdf/fw4.pdf) for USA-aliens.

I guess that the IRS uses this info to check whether enough income tax, etc. has been paid by the contractor.

**Comment by patrick727** [comment]
@lapin7 thanks for that, very clearly put.

**Comment by Ojimadu** [comment]
@lapin7  nice input. The system does not seem to be broken so lets work with what we have and watch how we evolve organically.

**Comment by kennyrowe** [comment]
Great discussion, I think it's also probably a good idea for the members of this committee to participate in the budgeting process as well.

**Comment by patrick727** [comment]
what do you guy think about organizing the reward sheet by projects? 

Each project could be a tab within the document? and then we can set a total monthly budget as well as highlight SOW'd work

**Comment by patrick727** [comment]
For the purpose of team building at scale a larger scale, i have broken up marketing projects into separate projects, some task may bridge two or more which will create sociocratic links between the co-operators who drive it.

**Comment by patrick727** [comment]
For the purpose of easier reporting on budgets and KPI's, @lapin7 gave me the idea for an easy naming scheme for issues that we can use to sort the decentralized budget system. 

M> indicates Marketing
O> indicates Operations
F> indicates Finance
L> indicates Legal
D> indicates Development

**Comment by ResonanceXX** [comment]
Great move it is. Makes sense to compartmentalize these information. As we grow they could also be departments with specifics attached to them. 

Sent from Yahoo Mail on Android 
 
  On Fri, 8 Dec 2017 at 23:30, patrick727<notifications@github.com> wrote:   
For the purpose of easier reporting on budgets and KPI's, @lapin7 gave me the idea for an easy naming scheme for issues that we can use to sort the decentralized budget system.

M> indicates Marketing
O> indicates Operations
F> indicates Finance
L> indicates Legal
D> indicates Development

**Comment by dckc** [comment]
@patrick727 did you consider using issue labels?

**Comment by kitblake** [comment]
> @patrick727 did you consider using issue labels?

That's a superb suggestion. If the issues are labeled the label works as a filter. So if you click on a "Marketing" label, you get a listing of all Marketing issues.

**Comment by patrick727** [comment]
@kitblake within the reward allocation sheet?

**Comment by patrick727** [comment]
This is mainly as an easy way to organize the reward sheet so that we can measure the return on our budgets.

**Comment by lapin7** [comment]
I can add a column "Label" to the Reward sheet. Let's all try add labels to the issues. And as we get used to this system, we can add also Milestones etc.

**Comment by dckc** [comment]
I considered closing this one, but it seems worthwhile to have the compensation committee actually decide something about the program.

**Comment by dckc** [comment]
@kennyrowe I get the impression this is as done as it's going to get.

Especially given the interest that the executive committee has taken.

As always, feel free to re-open it.
