### ISSUE TITLE
O> Governance Forum - Agenda

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#189]
_p.s. Planning the agenda mostly happened elsewhere, but this issue served as a useful place to keep up-to-date with plans as they evolved. -- @dckc_

----

Lets plan out some agenda items for the governance conference

1. formalize ["Declaration of Interdependence"](https://docs.google.com/document/d/1E8FCjRjbUDu8nSwkbl-z_lcA97Y3P7wQ4eOaWlIxEr4/edit#)

2. [Governance Agenda template ](https://docs.google.com/document/d/1w7shDAvmJascWjcnuJl7T_c6lYZBOYRb38z1wTePP4I/edit
)

**Comment by dckc** [comment]
"the governance conference"? What does that refer to? Is it an idea from a teleconference or something? I'd appreciate a pointer.

**Comment by ResonanceXX** [comment]
The governance forum should decide how to govern the RChain platform. I believe it is instructive to have a  constituted authority to lead us through.

**Comment by patrick727** [comment]
@dckc see the last hangout, and previous ones. It has been greg and vlads idea to hold a conference on blockchain governance and co-op governance for RChain Co-op.

**Comment by dckc** [comment]
OK... I hope it shows up in the [debrief index](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index) soonish. "See the previous hangouts" would otherwise take several hours.

I'm not used to all this business done with only video records. I'm sure it's easier for the participants at the time, but it's a pain for folks who want to catch up later (which is a larger and growing audience, if things go well). I'm spoiled by the W3C culture of near-real-time text records, edited into a hypertext.

**Comment by patrick727** [comment]
@dckc you asked for a pointer. The last hangout. Im the one having to manually do the summarys so feel free to pick back up or propose an automated soltuion. I know that @entropee was suppose to be working on one

**Comment by patrick727** [comment]
It has been a valuable resource in my opinion, but yes aside from the initial work that you did, I have done every single one since.

**Comment by ResonanceXX** [comment]
@patrick727  Can there be a clear information on how many attendees for the conference.

**Comment by patrick727** [comment]
@ResonanceXX for the governance conference? 

We estimating 75-100, but that's a very rough number.

**Comment by patrick727** [comment]
Hello everyone fill out this form for the location that we choose. Deadline will be 12/27/2017

https://goo.gl/forms/x4766jd6o66jSsUh2

**Comment by Ojimadu** [comment]
Since the event is expected to last 2-3 days, am more inclined to vote for weekends where more persons would be free and able to attend.

**Comment by kdvalentine** [comment]
As of the last Governance Committee meeting the plans for the Governance Forum are as follows:


Date: | February 15, 16, 17, and 18
Location: | Seattle
Venue: | TBD
Agenda: | Work in progress

**Comment by ResonanceXX** [comment]
Oh nice one. Seattle, the "Jet city."

Sent from Yahoo Mail on Android 
 
  On Sat, 23 Dec 2017 at 14:48, Kevin Valentine<notifications@github.com> wrote:   
As of the last Governance Committee meeting the plans for the Governance Forum are as follows:

Date: | February 15, 16, 17, and 18
Location: | Seattle
Venue: | TBD
Agenda: | Work in progress

**Comment by dckc** [comment]
Lots of details are on https://www.rchain.coop/events and ...
> Further details regards Session Details, Guest Speakers and Venue will be update on this page as they are confirmed

**Comment by patrick727** [comment]
another thing i want to do is create a survey with if then statements to try and get feedback regarding these questions. 

What brought you to RChain Cooperative? 
What would cause you to devote your full-time efforts on the RChain Platform/Ecosystem?

What would cause you to leave the RChain Cooperative? Platform? 

What would cause you to fork the RChain platform?

What would cause you to actively dissuade people from join the RChain Cooperative/Platform?

**Comment by patrick727** [comment]
The final thing I think would be fun(ill try to propose if time permits) is a consenus game using the ether.cards we have. 

Something like this. Maybe people have a better idea for a verzion of this. 

1. Everyone gets the same Sudoku puzzle at the same time
2. Each person gets 3 RHOC cards
3. 5-10% of the group will secretly be "bad actors"
4. Everyone stakes 1-3 cards on if they will choose the correct answer. 
5. The timer starts for 15 minutes, each person raises there hand when they are done
6. At the end of the 15 minute the people with complete puzzles move to validation
7. Timer starts for 5 minutes
8.  Some number of Volunteers attempt to validate the puzzles in the time frame. 
9. At the end of 5 Minutes the volunteers choose by staking more of there RHOC cards.
10. The correct answer is displayed and compared to the stakeholders choices
11.. If a group chose to validate the wrong answer, then they lose all of there cards to the correct answer
12. The first person who solved the puzzle correctly keeps there cards and recieves an additonal 10% RHOC bonus of total RHOC staked. 
13. Anyone who validated the correct answer(including the winner) keeps there staked RHOCs and splits the lost RHOC from the bad actors

seems like fun right?

**Comment by Ojimadu** [comment]
@patrick727 I like your idea. The game would be a fun way to end the forum. How about instead of using sudoku, we use something similar that can be played a good number of times in a limited time frame? I suggest we use a modified version of [this consensus game](http://www.consensusgame.com) where each vote is backed by 1-3 RHOC cards depending on how strongly the voter feels. 
After a vote is cast, the majority distributes the reward and the games is restarted this can be played multiple times in few minutes. 
Here is the [PDF instructions](http://www.consensusgame.com/Consensus_Music_Instructions.pdf) for Consensus game music edition.

**Comment by ResonanceXX** [comment]
We can also ask questions that related to RChain answers would have to display knowledge about the Coop. Thereby doing two things. 1). Rewarding people2). Teaching them/ making them learn more. Questions may be technical or more general. Depending on the subject matter decided on. And only the most interested members get to win prizes. Nice one guys.  

Sent from Yahoo Mail on Android 
 
  On Sun, 14 Jan 2018 at 10:32, Ojimadu<notifications@github.com> wrote:   
@patrick727 I like your idea. The game would be a fun way to end the forum. How about instead of using sudoku, we use something similar that can be played a good number of times in a limited time frame? I suggest we use a modified version of this consensus game where each vote is backed by 1-3 RHOC cards depending on how strongly the voter feels.
After a vote is cast, the majority distributes the reward and the games is restarted this can be played multiple times in few minutes.
Here is the PDF instructions for Consensus game music edition.

**Comment by Keaycee** [comment]
@patrick727 Nice idea you've got. I think i will have to work your suggestion and show you a preview after it's done.

**Comment by patrick727** [comment]
Sweet!

I'm glad people like the general concept. 
@dckc alright that sounds good to me. 

@Keaycee looking forward. 

The reason why I chose sudoku was because its a mathematical puzzle. There could be other ways of doing it so long as there are only one answer to whatever the puzzle is.

**Comment by 9rb** [comment]
Apparently there is a new monopoly game published by that has no Banker and allows cheating -- seems like a crypto game.

**Comment by dckc** [comment]
@patrick727 I suggest this issue is overtaken by https://www.rchain.coop/events and a discussion document available in the [#governance-forum][gf] channel. Please edit the description to say so and close this (or let me know it's OK for me to do so.)

[gf]: https://discordapp.com/channels/375365542359465989/393462637100400650

**Comment by dckc** [comment]
I updated the issue description to say what actually got done here.
