### ISSUE TITLE
Blockchain Governance Group

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#207]
Kevin had a great idea of forming a counsel that includes members of various organizations to participate in blockchain governance R&D and thought leadership

**Comment by ResonanceXX** [comment]
But, does this not negate the core principles of  a "decentralized governance." Since a new hierarchy consisting of a select few form this counsel. Other Developers may feel left out and without power. Also several other small players in the Block chain may be without adequate resources, information and persuasion to join. 

 
 
  On Fri, 22 Dec 2017 at 15:46, patrick727<notifications@github.com> wrote:   
Kevin had a great idea of forming a counsel that includes members of various organizations to participate in blockchain governance R&D and thought leadership

**Comment by kdvalentine** [comment]
@ResonanceXX I concern for exclusion is fair. The thought here is to discuss paths towards best practices. The counsel would be inclusive to blockchain projects, academia, government, not-for-profit organizations and developers. Since this is a very nascent subject, collaboration across segments may prove useful in establishing best practices. Especially with regard to cooperative governance which is rooted in inclusiveness.

**Comment by BelovedAquila** [comment]
Kevin has a great  idea,the formation of such counsel is a good step ahead, it would out spread Rchain broadly and make it possible for useful and developmental information  to spread and be shared,because  information remains power and remains it's sole communication is its key.

**Comment by jimscarver** [comment]
@leithaus mentioned a governance colloquium along the same lines. I suggest that is a good way to frame this activity.

**Comment by pmoorman** [comment]
closing this issue because it seems to lack any momentum or urgency (and I want to clean up the marketing label). Feel free to reopen if you still deem it relevant.
