### ISSUE TITLE
Announce Rholang and SDK on sites like Hacker News

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#238]
@MParlikar I expect you already have something in the works, but just in case...

see also tutorial #169 and playground #185

escalating https://github.com/rchain/Members/issues/234#issuecomment-358700050 to its own issue

cc @pmoorman @patrick727

**Comment by dckc** [comment]
We should address the following items from the [Programming Language Checklist](http://colinm.org/language_checklist.html):

You appear to be advocating a new:
[x] concurrent
programming language.  Your language will not work.  Here is why it will not work.

You appear to believe that:
[x] Garbage collection is free
[ ] Nobody really needs:
    [ ] concurrency  [x] a REPL  [x] debugger support  [ ] IDE support  [ ] I/O
    [ ] to interact with code not written in your language
[x] Scaling up to large software projects will be easy
[x] Convincing programmers to adopt a new language will be easy

Unfortunately, your language (has/lacks):
[x] type inference
[x] tail recursion  [x] coroutines
[x] reflection
[x] algebraic datatypes  [x] recursive types  [x] polymorphic types

The following philosophical objections apply:
[x] The most significant program written in your language isn't even its own compiler
[x] No language spec
[x] Your language relies on an optimization which has never been shown possible

Your implementation has the following flaws:
[x] Your compiler errors are completely inscrutable

Additionally, your marketing has the following problems:
[x] Unsupported claims of increased productivity

**Comment by dckc** [comment]
The blog item is great, but... um... I don't actually have an account on hacker news, reddit, nor lobste.rs.

@pmoorman be advised: this is at-risk

@MParlikar is Daniel G. doing developer outreach?

 - [RChain Rholang SDK (v0.1) Released](https://medium.com/rchain-cooperative/sdk-v0-1-5f6bc35bf3e9)  
   Nash Foster Jan 31

**Comment by dckc** [comment]
looks like @patrick727 put it on reddit yesterday: https://www.reddit.com/r/RChain/comments/7udryt/rholang_sdk_v01_released/

No comments. Hmm.

**Comment by pmoorman** [comment]
Maybe Hacker News itself isn't the most important, actually. When I mentioned this, my idea wasn't much focused on HN perse, but rather about **validation**:

> A major "risk" for RChain is that developers need to learn Rholang before they can build anything on our platform. Since Rholang is functional programming, it's a much higher barrier-of-entry than say Solidity.

RChain should be engaging with the wider developer community as early as possible, to learn how to overcome such barriers. Assuming that the entire RChain platform works well, it might be one of the main (if not the #1) reasons developers choose something else instead.

**As an aside:** the format of the blog is very much like a press release, rather than a blog post. If you're not already intimate with RChain and it's prime value prop, there's hardly anything to get excited about (basically, it doesn't sell the _"why should I care?"_ or the _why_).  
Another supplemental post could be written to outline in more detail _why you should care about Rholang_. Idea?

+++

_**P.S.** this state of affairs also the highlights the lack of a strong promotion plan to push out such announcements. I think we should create an issue for that, too_

**Comment by MParlikar** [comment]
Hi everyone,
If I could weigh in here.  There are a couple issues for developers with respect to the SDK.  If a developer is needing a feature set in the platform, there is a timing issue between our roadmap and theirs.  Attracting them in 2018 may cause them to commit to a platform that may not be ready in time for their needs, which could lead to sour grapes.    We want to attract developers that are dreamers, that see the vision and are committed to learning Rholang because they believe in functional programming and contracts that are correct by construction.   We should be targeting niche communities of developers and building our own.  I hope this helps.

**Comment by pmoorman** [comment]
@MParlikar does that mean we'd have to wait till much later in 2018 (or even 2019) to validate whether we are not all hallucinating about how hard/easy it will be to convince developers to switch to functional programming / Rholang (especially when they come from something like Solidity)?

Can we do anything to see if we could... 

1. ...get other functional programming communities enthusiastic about "a blockchain with a functional foundation"?

2. ...get the wider crypto dev community to at least consider the merits of the functional approach in a blockchain use case?

Btw, would it make sense to form a small group of people that focuses specifically on "marketing to developers"? Getting those dreamers onboard is a job in and off itself, yet they're one of the most important aspects of our marketing.

I'm super happy to contribute from the marketing perspective, but I'm not much of a developer at all!

**Comment by ottermagically** [comment]
@dckc wrote "We should address the following items from the Programming Language Checklist: You appear to be advocating a new..."

Given that the big Marketing Plan will be aimed initially at "Mavens", who will rightly care deeply about such things, it seems that anything we can do in regards to addressing checked boxes in the Programming Language Checklist would be desirable... thoughts?

**Comment by dckc** [comment]
@pmoorman I trust this sort of thing is being tracked elsewhere.

(I'm reviewing Development issues to see whether they have a clear next step... that sort of thing.)
