### ISSUE TITLE
O>organizing discussion and Issues: forum? folders? wiki?

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#243]
Hello cooperators, the proposition of the issue is based on personal observation in the co-op but don't know if its peculiar to me. I discovered that the Co-op is filled with so many ambiguities and no clear organising about the classification of issues. Some people including on boarding members and existing members tends to be less informed about the underlying idea of the Co-op. This can be seen when issues that not SMART are raised or misinformed answers to certain question in the channels. Secondly, concerning classification of issues, I think it could be more organized than placing tags on them. I feel that there should rather be folders under the issues where related issues are classified and named so that members can choose issues they wish to work on according to their interest and capacity. Because of this, I wish to suggest that there be a quora-type of forum squarely for direct questions and answers within the Co-op and apart from the socials. This I consider, is necessary for justice to be done in clarifying ambiguities. Questions sometimes are not squarely dealt with, closely given attention to and other times silently lost in the conversations in the social channels but such questions can be redirected to the suggested forum for justice. This will reduce the miss information, ambiguities and promote efficient participation of members in making SMART contribution. I believe the the course of the questions and answers, there will an be internally generated innovations. Please, the ground is open for deliberations and solutions.

Victor Viraculous:
The measure of completion: A quora-type of forum and classification of related issues into folders with its relevant tags.
Suggested Budget:

**Comment by Ojimadu** [comment]
The labels can act as folders. Have you tried clicking on them?

**Comment by Ojimadu** [comment]
I still feel they do same things.

**Comment by Keaycee** [comment]
@Viraculous You've got point. There are issues that is base on Marketing, Graphic design, Articles, Promotion, Web development, Language Translation and many more. All related issues, are labelled base on their classification. In this way, it will be easy for cooperative members to work on issues base on their interest or specialty.

**Comment by BelovedAquila** [comment]
@viraculous do you a sort of, issues as pertains to Development, should be placed under a folder created for Development issues. And issues as pertains to Marketing, a marketing folder should be made where solely marketing issues would be placed on it?, if yes, then it's ok, makes issues more precised and collaborators able to specifically go to issues they can handle.
And about creating a quora type of forum for questions isn't a bad idea too, but a social media platform can likewise be used solely for the questions and answers, not necessarily must it be a quora platform.

**Comment by lapin7** [comment]
I've set up a "container issue" for Development. When you're working on a Jira Bounty, you can add links and comments into [#176 D> Development...](https://github.com/rchain/Members/issues/176)
The development tickets can be found here
https://rchain.atlassian.net/browse/ROS-271?jql=labels%20%3D%20bounty

**Comment by Viraculous** [comment]
Nice work @lapin7 I just checked it out.

**Comment by dckc** [comment]
@lapin I don't find such "container" issues useful. Would you want all the Operations work collected in one issue? It defeats the whole budgeting structure, no?

**Comment by dckc** [comment]
I had to read the issue summary several times before it became clear to me what you're advocating: reducing the use of issues for Q&A by providing another outlet for them.

I have seen similar suggestions to address the fact that chat systems like discord don't preserve history well.

I'm partial to web-archived mailing lists, since email is decentralized. But moderating them is very manually intensive. [discourse](https://www.discourse.org/) is the one web-based forum platform that integrates with email well enough for me and provides significant automation for scaling a community (e.g. you can't post "buy viagra!" links until you've established a bit of reputation.) On the other hand, @drbloom told me he set up forums in a similar community and they were abandoned in preference to chat (slack at the time).

Meanwhile, our github repo does include a wiki: https://github.com/rchain/Members/wiki
In our call this week (#249), there was considerable support for investing in that wiki. It provides shared memory to sum up results of message-passing exchanges in chat, issues, etc.

I like the metaphor Sandro used in his writing on [The Bees and the Ants](https://www.w3.org/2002/11/bees-and-ants/paper.html):
> ... developers weigh these same two approaches for arranging how the computer processes communicate, calling them "message-passing" and "shared-memory". 
> Honey bees use direct communication: the scout does a "dance" in which particular body movements indicate the direction and distance to the discovered food source. Ants, on the other hand, modify their environment and leave a persistent message: the scout, on the way back home after finding some food, activates a scent gland and drags it on the ground.

**Comment by dckc** [comment]
@Viraculous writes:
> Secondly, concerning classification of issues, I think it could be more organized than placing tags on them. I feel that there should rather be folders under the issues where related issues are classified and named so that members can choose issues they wish to work on according to their interest and capacity.

The [meta issue pattern](https://github.com/dart-lang/sdk/wiki/Creating-and-triaging-meta-Issues) is common in github. It uses one issue to represent a collection of others by just listing them in the description:

 - [ ] #1 Describe org...
 - [ ] #2 Add rights...

**Comment by lapin7** [comment]
@dckc It would be great if you could take care of the Development issues. Split them or using containers or whatever. The goal is not to double discussion channels about Issues. So when things are discussed in Jira then they don't need to be discussed here.

**Comment by David405** [comment]
Concerning organization, what if we have different repos that contains issues based on the repo subject, for example, development repo for development, marketing and other subjects. Then I suggest we should try to reduce our means of communication, there are so many platforms that are being used that sometimes one can get overwhelmed with installing Apps and stuffs like that.....what do we think about this?

**Comment by dckc** [comment]
@lapin7 writes:
> @dckc It would be great if you could take care of the Development issues.

I did make an effort to take care of them this month.

**Comment by patrick727** [comment]
@Viraculous there are labels to act as categories and there are projects that act as a way of organizing the issues by way of stage of completion. 

https://github.com/rchain/Members/projects/14 for example is "digital community building"

Ian reccomends a knowledge base plug in for Q&A that I agree should be implemented
@dckc I also reccomend a discourse forum, i told medha about it for developer.rchain.coop

Just because people abandoned it in an old context doesnt mean they will here, our community is much more active and willing to experiment with tools to better process, and discourse has some other tools that would help us scale feedback. 

For example we were speaking about this in marketing meeting how to track "quality feedback" on releases like the SDK, if done in discourse the mods could use a badge that indicates quality feedback. Etc etc.

**Comment by dckc** [comment]
I see https://forum.rchain.coop/ is launched. It calls itself "RChain Developer Forum", so perhaps the scope is different from the target here, but it's hard to imagine that there's room for two different forum systems.

**Comment by dckc** [comment]
In preparation for tomorrow's meeting (#381) I'm doing some issue pruning.

I don't see any progress on this. If anyone intends to work on this, go ahead and re-open it and assign yourself.
