### ISSUE TITLE
M> Get connected with Discipl

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#247]
[Discipl](http://discipl.org) is a Dutch initiative to re-create government services from the bottom up with the view of the citizen perspective. It consists of all kind of small pilots with blockchain tech. 
Specific: contact discipl about introducing RChain as a platform to work on
Measurable: RChain accepted by discipl as working platform, introduce our way of defining issues, budgets and rewards
Achievable: Get the list of existing or described ideas
Realistic:
Timely: Before March 1st

Measure of Completion:  0
Suggested Budget: $5000

_See CONTRIBUTING.md for details on budget and reward process._

**Comment by BelovedAquila** [comment]
Checked on it, amazingly love the idea of The discipl  (DIStributed Collaborative Information Platform) being Scalable(such that users can users can provide their own capacity) , it's free (No fees for transactions and using this platform) , and putting ones privacy in mind too in a way in which it evaluates your data rather than sharing it. Indeed quantum safe. And much more vitals that would enhance RChain if discipl actually works on its platform(RChain platform). Let's work on it

**Comment by pmoorman** [comment]
@lapin7 since I'm a fellow Dutchy, maybe I could reach out to them? It seems like they are (for now) quite dutch-minded, because their manifesto is still in Dutch for instance.

Before I reach out to them though... I'm not sure if I understand precisely enough what exactly we want to get out of it. 
What do you mean with...

> Specific: contact discipl about introducing RChain as a platform to work on
> Measurable: RChain accepted by discipl as working platform, introduce our way of defining issues, budgets and rewards

Let's discuss, and I can reach out to them. I'm keen to reach out, because I'd love to contribute more to projects like that, too.

**Comment by Viraculous** [comment]
Perhaps they could help us on governance issues @pmoorman. Maybe they could apply their blockchain technology in governances in service to the platform where applicable. There are on github but here is their twitter link https://twitter.com/discipl_org  . I also want to get in touch with them through this means for them to consider if the co-op is a workable platform for their technology more especially particularly on governance.

**Comment by Viraculous** [comment]
I had just contacted Discipl for consideration on whether the RChain coop is a workable plat form, hoping to get their reply soon.

**Comment by BelovedAquila** [comment]
The Dutch government is fully participating in blockchain. It is studying various technology platforms and technologies. Under the supervision of Marloes Pomp, the Ministry of internal Affairs has initiated an umbrella project, under which various pilots are being developed. These pilots have been  presented early in November 2016 and, at a later date, had developed into a hackathon40 to be organised by DutchChain. Meanwhile, the Dutch Ministry of Economic Affairs is setting up more  various activities, discipl being one of its initiatives. So I think discipl  would be interested to introduce RChain as one of its platforms to work on, considering how enviable RChains prospects is becoming.
@Viraculous nice move, since you are already handling getting in touch with them on Twitter, we look forward to getting a feedback, and most certainly a positive one. Cheers!

**Comment by Tonyprisca13** [comment]
it is a welcome idea @viraculous

**Comment by kaka56** [comment]
@pmoorman and @Viraculous .good  work trying  to contact the discipl on twitter it will be a good  idea to check in on other links to get  to them.

**Comment by Viraculous** [comment]
Yes thank you all we are on progress. I got a reply from one of the team leaders today. After twitting him up, he said "Hoi Victor, dank voor je bericht. Ik had/heb nog niet gereageerd via Discipl handle omdat ik daar nog niet aan toegekomen was/ben. Komende dagen ben ik ernstig druk. Reken erop dat binnenkort hierop bij je terug kom.Nog even geduld.
Gr. Steven" that's in English "Hi Victor, thank you for your message. I had / had not yet responded via Discipl handle because I had not yet arrived. Coming days I am seriously busy. You can count on that soon to come back to you.Please be patient.
Gr. Steven" . my twitter name is victor.

**Comment by BelovedAquila** [comment]
@Viraculous that's a good progress

**Comment by Viraculous** [comment]
Still on progress. got a reply later this evening after responding his message. 

VIRACULOUS: Hearing from you now gives me certainty about the progress. I am patient and hope you get along quickly. Thank you for the reply.
STEVEN GORT: It'll be fine. I think I saw / spoke to a colleague of yours who I met at the RIVM last week in a session. He explained RChain there.
VIRACULOUS: Wow! good you know that. The coop would be very happy if Discipl were to work on its platform structure.

I will get in touch with other team members to build the community's impression and meet her interest.

**Comment by lapin7** [comment]
Please send them these links to get them on board.

*Please become member of this group
<http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgroups.google.com%2Fforum%2F%23!managemembers%2Frchain%2Fjoin&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
to
get access to documents
Create an account on Github
​ and read​
 *github/rchain/Members
<http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fblob%2Fmaster%2FCONTRIBUTING.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
in
order to contribute.
And send
​your github name ​
to *ops@rchain.coop <ops@rchain.coop>*.
Then after a while log in to github and then accept the invite through this
link https://github.com/rchain/Members/invitations

To know more about RChain:

   - Official *RChain Website
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Frchain.coop%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   - Chat about RChain at *Discord
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdiscord.gg%2FfvY8qhx&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *Telegram
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Ft.me%2Frchain_coop&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *Twitter
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Ftwitter.com%2Frchain_coop&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *Facebook <https://www.facebook.com/rchaincooperative/>*, *YouTube
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCSS3jCffMiz574_q64Ukj_w&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *Reddit
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.reddit.com%2Fr%2FRChain%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *BitcoinTalk
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fbitcointalk.org%2Findex.php%3Ftopic%3D2494040&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   , *Medium
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fmedium.com%2Frchain-cooperative&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*,
   QQ Group ID: 中国朋友欢迎加入RChain粉丝群，QQ群号: 530718666
   - Read the *FAQ
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Freference%2Fblob%2Fmaster%2Ffaq.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   - RChain *Architecture
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Frchain-architecture.readthedocs.io%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
    Doc
   - To compare *Blockchains
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Frchain-architecture.readthedocs.io%2Fen%2Flatest%2Fintroduction%2Fcomparison-of-blockchains.html&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   - Weekly *Debrief
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fwiki%2FWeekly-Debrief-Index&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
    Index
   - Follow the *Roadmap
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Frchain.atlassian.net%2Fwiki%2Fspaces%2FCORE%2Fpages%2F105709609%2FRoadmap&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   - RHOC *Distribution and Circulation
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Freference%2Fblob%2Fmaster%2Ffinance%2Frhoc.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*


To contribute to RChain:

   - Join RChain Coop by *signing up for membership
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Fmember.rchain.coop%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
   - Join *rchain@googlegroups.com <rchain@googlegroups.com>* *see
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgroups.google.com%2Fforum%2F%23!managemembers%2Frchain%2Fjoin&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
to
   get access to documents.
   - Join *github/rchain/Members
   <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fblob%2Fmaster%2FCONTRIBUTING.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*
in
   order to contribute


RHOC Token Details
To see RHOC in *MEW
<http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.myetherwallet.com%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*/Metamask
"Add Custom Token" with address:
0x168296bb09e24a88805cb9c33356536b980d3fc5
8 digits


--
Cheers,
HJ

**Comment by Viraculous** [comment]
Thanks @lapin

**Comment by BelovedAquila** [comment]
@lapin7 is it all the links that is to be sent to them or just  on boarding links that directs them on how to a member?

**Comment by Viraculous** [comment]
Contacted Bas Kaptijn; ICT Architect of Discipl today, hoping to get reply soon.

**Comment by Viraculous** [comment]
Feedback from Bas Kaptijn; ICT Architect of ICTU/Discipl, replied me thus; Hi Victor,  I discussed this with Steven. It appears he was already in contact in the Netherlands with someone from the RChain community. This might lead to a project in which we'll try out RChain too like we did with IOTA. It would involve developing a binding from our Discipl Core API's (in development) towards RChain.  But I can't promise as also we'll have to take our time to look into this. For now: thank you for your interest and info about RChain of which we do think it is an interesting project.  Kind Regards Bas Kaptijn

**Comment by Viraculous** [comment]
I contacted the ICTU also (initiatives of Discipl) on this issue. I hope to get their replies soon. I also sent them links to collaborate with us. https://www.ictu.nl/about-us

**Comment by Viraculous** [comment]
Feedback from Bas Kapijn ( Architect @ICTU/DISCIPL); Hello Victor, note we are a very small team. There hasnt formed yet a real community around discipl. We (some of our team) might think of using rchain in some future project and as such might collaborate with the rchain community but i cant say for sure nor when. We are not really talking about it and are busy with a lot of other things to be honest. I'd be helped more when apart from such a project the rchain community would try and help build a discipl core binding to rchain instead of the other way around (us building it ourselves in the rchain community of which i don't think will happen given our ample time/resources). In a sense this would mean collaboration too as i'd have to explain rchain devs more about what discipl actually is and  make discipl core more mature. Note that discipl core is mostly a w3c verifiable claims api on top of which a new needs centered discipl pattern api will be build. Implementing the binding to rchain would mean rchain could be a choice of platform (one of the supported platforms) for  use cases (8 of them currently in development) build upon discipl core. If rchain dev people are interested in this, they can contact me (note also: then it would be best when these people are living in nl so we could meet once or twice). I hope this helps?.   Regards Bas

**Comment by lapin7** [comment]
Let's implement [w3c verifiable claims api](https://www.w3.org/2017/vc/WG/) on RChain and try to get their 8 usecases worked out.

**Comment by Viraculous** [comment]
OK @lapin7.

**Comment by BelovedAquila** [comment]
@Viraculous this is progressive, implementation of the binding #334 is the next phase,we are indeed heading somewhere. I think this issue of getting the discipl has been resolved, other subsequent steps on implementing the  https://www.w3.org/2017/vc/WG/ should be on #334.
