### ISSUE TITLE
rename rchain/Members repo to distinguish from coop members?

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#267]
The current name of this repo, "Members" is far too easy to confuse with "member" as in RChain Cooperative member as defined in the [board and bylaws][1].

[1]: https://github.com/rchain/board

Let's do some polling on the candidates; please use :+1:  / :-1: on the respective comments (as many as you like) to indicate support or opposition:
 - [activisits](https://github.com/rchain/Members/issues/267#issuecomment-362051171)
 - [Activism](https://github.com/rchain/Members/issues/267#issuecomment-364671559)
 - [bounties](https://github.com/rchain/Members/issues/267#issuecomment-362051171)
 - [BountyProgram](https://github.com/rchain/Members/issues/267#issuecomment-364669372)
 - [Collaborators](https://github.com/rchain/Members/issues/267#issuecomment-364665705)
 - [RAM](https://github.com/rchain/Members/issues/267#issuecomment-361967810)

To add a new proposal, make a new comment with your suggestion in **bold**.

**edit**: note old links will not break; [github supports redirects](https://github.com/blog/1508-repository-redirects-are-here)

**Comment by kitblake** [comment]
Incisive thinking @dckc, it would be good to distinguish active contributors from passive Members such as investors.

I agree about RAM's appeal. As for `rchain/bees_ants/` it's two elements (with the requisite underscore). Looking for one word, I checked the clade. Bees and ants are classified within Hymenoptera. I'm not thrilled with `rchain/hymenoptera` and the order also includes wasps and termites. 

Btw, these insects are 'eusocial', the highest level of organization of animal sociality. Bees live in a 'hive' and ants in a 'colony'. Meh.

At this point, since we already have `rchain/` in the path, I'm most partial to `rchain/activists` which doesn't include the insect or animal reference but does have a history. Before the private sale in September, it was used to distinguish active contributors while waiting for the Membership program. Also beginning with an 'a' has advantages.

But let's continue thinking..

**Comment by pmoorman** [comment]
_Pre-P.S. I'm definitely one of those confused people :/_

---

- Activists for me conjures pictures of Greenpeace, etc.  I wouldn't go with that.

- RAM might be confusing because you need to remember what it _stands for_. It also sets the tone for "using weird accronyms is oke", which it probably shouldn't be.

- "Active members" is hard to beat in terms of just exactly describing what it is, but it's not very sexy. Positive is also that it outlines exactly the correct relationship:  members = active members + passive members.

- For me, "Contributors" comes to mind. It's equally clear, and sets the right kind of expectation of what it is. It's not sexy. It could also be that this conflicts for developers, because these members wouldn't necessarily commit code. I can't really speak for how developers feel, in that sense.

++++

I'm afraid that none of the catchy solutions will be clear, and none of the clear solutions will be catchy. 

**Should we optimise for _catchy_, or for _clarity_?**

**Comment by lapin7** [comment]
I like RAM :-)

**Comment by dckc** [comment]
Some candidates from tooth-brushing / driving time:

- **bounties**
  - I think this is the word used in the wider software development, security, and cryptocurrency community for the sort of thing we're doing. In cases where I only had one word to refer to what we're doing, I have used "bounties" or "bounty system". It's used as a keyword in the core JIRA, for example.
- **swarm**
  - I have yet to read that "swarm way of working" thing, but meanwhile, I recommend [the bees and the ants](https://www.w3.org/2002/11/bees-and-ants/paper.html) by Sandro.
- **dbr** for distributed budgeting and rewards
   - dbr is obscure, but I find that's often useful: nobody reads anything into the name; they only know what it means by looking it up.

**Comment by dckc** [comment]
@pmoorman writes:
> Positive is also that it outlines exactly the correct relationship: members = active members + passive members.

No, there are ways to be an active RChain coop member that don't involve this bounty system.

**Comment by pmoorman** [comment]
> No, there are ways to be an active RChain coop member that don't involve this bounty system.

Oh God....  (this stuff is more complicated than I thought!) 

---

Actually, I think the suggestion of "swarm" is neath, although what would a "swarmer" or whatever be called?

@dckc wrote:

> - dbr for distributed budgeting and rewards.  
dbr is obscure, but I find that's often useful: nobody reads anything into the name; **they only know what it means by looking it up.**

In that case, I would say RAM is the better-sounding alternative. RAM can also reference a person who works as an "RChain active member."  Girls could say _"psst look, I think he's a RAM..."_, better than talk about a dbr'er or whatever.

**Comment by dckc** [comment]
@lapin7 we seem to have a critical mass of support for RAM. On Weds Feb 7, the proposal will have been out for a full week. At that point, if noone has made strong arguments against, would you please make it so?

**Comment by lapin7** [comment]
@dckc So without strong objections appearing, I will change the name of this Sub Repository from Members to RAM on Feb 9 (my birthday).
And the Google Drive: RChain/Members wil also become RAM
And further more all words like activists and so have to changed to RAM
As for the bounties: I would call KRAM (Kiss RChain Active Member) and in fact in Swedish this corresponds to a kiss or a hug. :-)

**Comment by dckc** [comment]
@lapin7 ? go ahead and rename it?

**Comment by drbloom** [comment]
The name RChain **Active Members** (RAM) causes confusion because it conflicts with **ACTIVE MEMBERS** as defined in the Cooperative's Articles of Incorporation & Bylaws:

[RChain Cooperative - Articles of Incorporation with RA.pdf](https://github.com/rchain/board/blob/master/RChain%20Cooperative%20-%20Articles%20of%20Incorporation%20with%20RA.pdf)

> Articel IV.2 "Active Members are those who (a) purchase at least $10 worth of..."

[Revised Bylaws (8-28-17).docx.pdf 
](https://github.com/rchain/board/blob/master/Revised%20Bylaws%20(8-28-17).docx.pdf
)
ARTICLE II.2 Active Status;Termination
> RChain's Articles of Incorporation, as amended (the "RChain Articles"), describe the requirements for "active" membership status and the circumstances under which a membership will automatically terminate...

Perhaps give the repo the simple name "Collaborators" ?

**Comment by dckc** [comment]
I'd rather just just give RAM a different expansion. Perhaps RChain Active Movers.

Greg said he wants to use this program to encourage people to tell the RChain story. A thesaurus says storyteller = minstrel. Perhaps RChain Active Minstrels. I'm not sure that's good for recruiting open source developers, which is the other goal Greg mentioned yesterday.

Or we could stop trying to push water up hill and call it what everybody is already calling it: **bounties** or **BountyProgram**; e.g. from the [Governance Forum agenda](https://www.rchain.coop/events).

**Comment by dckc** [comment]
I tweaked some of the comments to support polling: each proposal goes in its own comment. See the issue description for detail.

I'm also assigning this to all the repo admins.

**Comment by patrick727** [comment]
what about "Activism"

**Comment by dckc** [comment]
The dictionary says an activist is "a person who campaigns to bring about political or social change." I don't think that's a good word to recruit open source developers.

**Comment by zsluedem** [comment]
`RAM` is not easy for the new bees to understand what it means.
Any abbreviations are not always friendly to the new members.

**Comment by ICA3DaR5** [comment]
May I suggest [Cooperator](http://www.dictionary.com/browse/cooperator)

# verb (used without object), cooperated, cooperating.
1. to work or act together or jointly for a common purpose or benefit.
2. to work or act with another or other persons willingly and agreeably.
3. to practice economic [cooperation](http://www.dictionary.com/browse/cooperation).

# Synonyms
- collaborate
- join
- participate.

**Comment by Viraculous** [comment]
Me am still yet to fully grasp the whole idea of what RAM  is all about and how to fully participate @Ojimadu. I wish it could be made simpler.

**Comment by Tonyprisca13** [comment]
I suggest we retain collaborator or go with cooperator, it's easily understood especially for new members.

**Comment by lapin7** [comment]
I suggest to go for RAC = RChain Active Collaborators.
Github talks also about Collaborators.
Thx @drbloom for pointing out this problem.

**Comment by ICA3DaR5** [comment]
@lapin7 Here's Wikipedia on RAC: https://en.wikipedia.org/wiki/RAC

**Comment by kitblake** [comment]
RAM
RChain Activity Matrix
RChain Action Makers
RChain Associated Movers

RAW
RChain Active Workers

/rchain/collaborators is one clear word. 
/rchain/colab is for short.

**Comment by zsluedem** [comment]
@Tonyprisca13 yeah . I spent a few days to understand `RAM`. 

I prefer a straight easy simple word. Sometimes I think `Member`  is a good word,too.
But I prefer `collaborators `.

**Comment by kitblake** [comment]
**RAW**
RChain Active Workers
RChain Apiarian Workers

**Comment by Ojimadu** [comment]
I prefer collaborators. It gets the message across without much semantics.

**Comment by dckc** [comment]
My polling suggestion hasn't generated much response. I'm strongly inclined to just rename it to **bounties**. I'll try to check with @kitblake and @lapin7 tomorrow.

**Comment by dckc** [comment]
As you can see, I changed it to **bounties**, having checked with @kitblake and @lapin7.

**Comment by dckc** [comment]
As you can see, I changed it to **bounties**, having checked with @kitblake and @lapin7.

**Comment by lapin7** [comment]
I've changed the name of "Pub Member Budget Allocation-Spending" to "https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=950224463"
