### ISSUE TITLE
M > Translate Rosette document into Chinese

### ISSUE THREAD

**Issue by yuhuanmocmoc** [rchain/bounties#269]
Blockchain is my research interest. Meanwhile, I'am a front-line blockchain developer and have a great interest in rchain. [Rosettle](https://github.com/rchain/reference/blob/master/docs/Rosette-1.1.pdf) is a core part of the Rchain architecture, in order to allow more developers to understand Rchain, I plan to translate this document into Chinese. And better yet, I can invite other developers who have experience in the development of blockchain to assist me.

**Time**: 3 weeks
**Collaboator**: @linsheng9731 , @yyh1102 (and others?)

**Comment by yyh1102** [comment]
Please let me join in~ I've already research some part of this document , and i believe it's a good and win-win chance.

**Comment by Whisker17** [comment]
I am interesting in this too.Maybe we can work together

**Comment by rjl493456442** [comment]
Sounds cool!

**Comment by linsheng9731** [comment]
@yuhuanmocmoc  Good idea! I am very interesting in this, and i think i can help you.

**Comment by lapin7** [comment]
#269 will be added in 201802: Budgets and Rewards.
Feb 1 the TAB's will 201801: Budgets and Rewards will be frozen. No changes possible anymore and payment process will start, first with some analysis and possible cleaning.

**Comment by rjl493456442** [comment]
@yuhuanmocmoc Add me please

**Comment by yuhuanmocmoc** [comment]
@lapin7 Sure, but we will start working on this issue right now.

**Comment by lapin7** [comment]
@yuhuanmocmoc #269 has been added. It's the last update for January. So you can set the [budget](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=468279933&range=179:179) and [rewards](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=950224463&range=2268:2274)


269 |   | M > Translate Rossette document into Chinese
-- | -- | --








M > Translate Rossette document into Chinese |   | 0 | OPEN | $ - | 0.00 | 0.00 | 0.00 | Member
-- | -- | -- | -- | -- | -- | -- | -- | --
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | yuhuanmocmoc
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | yyh1102
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | Whisker17
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | rjl493456442
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | linsheng9731
M > Translate Rossette document into Chinese |   |   | OPEN | $ - |   | 0.00 | 0.00 | lapin7

**Comment by Viraculous** [comment]
Please check the link above, its not going,"ERROR 404" .

**Comment by yuhuanmocmoc** [comment]
@Viraculous  thank you, it's alright now，

**Comment by Viraculous** [comment]
Good

**Comment by yuhuanmocmoc** [comment]
The translation work has been done. You can preview the translated document in [this](https://drive.google.com/file/d/1FeeZysyud_ao2j8UUDP3pwNKZYiN6lzb/view?ts=5a96c0b2).

**Comment by ICA3DaR5** [comment]
@yuhuanmocmoc Looks good to me. Should I close this issue?

**Comment by yuhuanmocmoc** [comment]
@ICA3DaR5   @rjl493456442 @yyh1102  will review it for a few days.

**Comment by Jake-Gillberg** [comment]
I'm not sure that this document is a correct target for translation. Why did you identify it for translation?

To my understanding, the hope is that Rosette is hidden away in the background / might not even be a part of the stack long-term. This document really only seems relevant to the very core development team, which conducts most of its business in English.

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg I am sure the chinese team is doing great work, since this file is in the reference repository.

Keep on working guys/gals.

@AbnerZheng @rjl493456442 @yyh1102 @yuhuanmocmoc @linsheng9731

**Comment by Jake-Gillberg** [comment]
@ICA3DaR5 This doesn't address my concerns. The reference repository was not created with the intention that everything in it would be translated. Sure, some stuff in there is great for translation, but just because something is in there doesn't mean it's a good translation target..

Rosette is an intermediary compilation target for Rholang, it is not necessary to know for smart contract developers. In fact, in the "native stacks" that Greg talks about, Rosette isn't even a part of the client!

**Comment by ICA3DaR5** [comment]
@yuhuanmocmoc What's the status of this? For the time being I don't encourage to translate this document.

**Comment by rjl493456442** [comment]
@ICA3DaR5 To be honest, we have finish the translation.

**Comment by yuhuanmocmoc** [comment]
@Jake-Gillberg @ICA3DaR5 me and my teammates spent more than 10 days to make the translation. If the rosette document is not a good target, it should be banned at the beginning. It is unfair to cancle the budget now.

**Comment by yyh1102** [comment]
@Jake-Gillberg That's not fair. This issue is created one months ago and we completed the translation work an the end of Feb. Why not declare the unnecessary of the translation of this doc at the very begining....?

**Comment by linsheng9731** [comment]
@Jack-Gilbert, I just want to know what is the criteria for judging whether this document is important? Because, in our opinion, this document will help increase people's understanding of rchain. In general, we need a clear standard to judge whether it should be translated. Unlike what we do now, we each have different standards.

**Comment by AbnerZheng** [comment]
I have participate in this translation too.  
@Jake-Gillberg It is unfair to cancle the budget, since the item is created in 31 Jan. And we started this work after this item being added to the budget excel. Thanks for you concern firstly, we should decide which document should be translate firstly. But I think this document is worthy to translate. The rosette virtual machine is just like the jvm, as I know, rholang will be compiled into rbl firstly, then running in the rosette(or roscala), this document is the specification of vm, like the specification of jvm. This well written document give community the possibilities the create another language, just as scala to jvm. This document give the possibilities to transpile the existing language as solidity into rbl. So in my opnion, this documen is valuable, though it is written in 90s. Perfect design remains forever. 
The community is growing, and as Greg said, just keep try, and learn from the error, the communty will be better.

**Comment by Jake-Gillberg** [comment]
Hey all, I didn't say anything about canceling the budget. First of all, I only have one vote. Second, I understand that a lot of time and work went into this, and I didn't catch that this was being translated for over a month, I won't vote 0 for a budget.

@AbnerZheng This is a good argument for the document being translated. But do know that in the "native clients" that are being discussed, to my knowledge, the Rosette VM will not be targeted as an intermediary.

**Comment by AbnerZheng** [comment]
@Jake-Gillberg Thanks for you undetstanding.
Yes, you are right, this is not a plan of core team right now. So I just said a possibilities. I am helping core team porting rosette to roscala, so I am quite familiar with rosette. The rbl is a scheme-like language, Greg add actor to this panguage. As I know,  the goodneas of rchain is not just the rholang, but also casper, namespace and so on. If the prototype system of rchain do achieve its goal, I thought that will be a great improvement to the blockchain. And I think at that time, the whole community is willing to use this system. And at that time, this docuement will be valuless.

**Comment by ICA3DaR5** [comment]
This issue was paid. The file is uploaded in a pulic view, I asked from @AbnerZheng to create a PR.

**Comment by zsluedem** [comment]
I believed this one has been finished, right ? @yuhuanmocmoc @AbnerZheng
