### ISSUE TITLE
onboard @pmoorman, growth marketer for early-stage tech startups

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#294]
@pmoorman suggested a marketing audit in #234; that resonates with some gaps I see, and he's clearly more qualified to address them than I am, so I'm doing what I can to show him around.

 - [x] how he got involved: "@traviagio asked me to get involved with RChain"
 - [x] filled out introduction / skills inventory (#222) 1/25/2018 10:47:52

See also on-boarding issues #15, #253

cc @traviagio, @pmoorman @patrick727 @drbloom @kennyrowe

**Comment by pmoorman** [comment]
I'll write another comment later outlining the history of how I got here (similar to your own issue, @dckc). That could be helpful for modeling future onboarding.

For now, I thought it might help to outline a few things that I'm still stuck with. At this point I've been actively involved with the RAM for 2-3 weeks.

### Key confusion / friction areas:

1. **How to define good scopes for projects.**  ::  I'm probably better at this than most marketers already, but for any non-dev this will be confusing. It's something I see all sorts of people do badly. _Related to: defining SMART goals._

2. **How does consensus work?**  ::  I might be a bit impatient sometimes, but I sometimes struggle to figure out whether we have enough of a consensus to proceed with a suggested approach, or rather wait for more "approval". (see #219 for instance) More clarity here would help me be more productive.

3. **[BIG ONE!] How is RChain structured?**  ::  We have RChain, RChain Coop (and Ventures and Holding), and then we have within the coop the RAM, but the RAM is only part of it.... I'm badly confused about this shit, and limits me in moving bigger projects forward. 

4. **Making bigger contributions**  ::  there are 3-5 areas of marketing that will make an _outsized_ difference in RChain marketing effectiveness. The nature of the RAM is such, that it's much easier to just work on small issues, rather than kill the elephant. But solving 100 small problems/tasks isn't the same as solving one of those _big_ things. I currently have a hard time finding the right approach towards making _big_ contributions.

I don't know for sure if any or all of these problems are problems to others, also. But here's how I think we can maybe tackle each one of them:

### Suggested improvements:

**Scope setting**

- Education on how this works should be included in the onboarding. Once you understand the basics of how RAM and the coop works, this could be part of the "practical" education. It's also a valuable skill to have for other projects.

-  Experienced people helping you. I appreciate the effort of more experienced people (mostly @dckc) to help me set better scopes for issues. This is a bit tiresome for the mentor, but really helps. The more people get good at setting scopes, the better this will work.

**Consensus**

- Clear guidelines on how this works would help

- Clearer understanding of "who decides on what". Could also be part of onboarding education.

**RChain structure**

- Maybe we can make an organisational chart, or some form of diagram that would take away much of the confusion ([something like this?](http://blog.visme.co/wp-content/uploads/2017/03/17-totally-free-venn-diagram-templates-Mixed.png))

- Naming conventions help. See the issue about "members != members", for instance (we decided to change it to RAM, which is better already)

- Maybe this is not an issue to most people. If you're in the RAM and want to do translation work, or fix bugs as a developer, or write blog posts, I don't think you'd particularly care about this. Which leads to the 4th issue...

**Contributing on big issues**

- I think this might be more something personal, rather than an issue everyone experiences. Still, it's interesting to think what we can do to improve it.

- Having a bit of a 'political mentor' helps navigate those waters

- Better solving of the RChain structural stuff would also really help.

++++++++

Pfff.... that's it for now!!

Cheers,

–Pieter


_**P.S.** I think @dckc deserves a BIG shoutout for patiently helping others get up to speed, when he has undoubtedly more glamorous things to do.  I **really** appreciate it._

**Comment by dckc** [comment]
In reverse order, i.e. most useful to least useful answers:

> Making bigger contributions

In your case: get in touch with @kennyrowe . He's busy, so be patient and persistent.

I'm not sure this advice generalizes... perhaps it does: make time to talk with people that have been around for a while.

> How is RChain structured?

That one we should be able to deal with in 5 to 7 wiki topics:
   - [ ] Greg Meredith
   - [x] [RChain](https://github.com/rchain/Members/wiki/RChain) cooperative
     - [ ] RChain Board of Directors
     - [ ] RChain Officers and employees
   - [ ] Core Dev team, Pyrofex: Medha, Nash, Mike Stay
   - [ ] Holdings

> How does consensus work?

One of the great mysteries of life. I spent 15 years compiling "The Art of Consensus" at W3C. I wonder if I can get a copy to share publicly... of course, I wonder how much of it is applicable outside the particular context of chairing a W3C working group.

> How to define good scopes for projects. ... It's something I see all sorts of people do badly.

That's the nature of the beast, as far as I know. There's a reason organizations hire project managers. It's a skill that typically takes time to develop.

**Comment by pmoorman** [comment]
In #253 @dckc wrote:

> If you haven't spent hours onboarding others, please document your own experience coming on board in an issue like #293 or a blog item or whatever.

So here we go, so we can add that to the library of cases there. In roughly chronological order:

- I learned about crypto about 4 years ago

- In 2017 I had some more time to dedicate to new projects, so I decided _"I should get involved with crypto stuff"_

- Georgi (@traviagio) and I work together more regularly on projects, and he introduced me to RChain.

- When I entered, I was completely confused about what RChain actually is trying to achieve. The upside was: they had lots of marketing problems to solve. Good for me.

- Due to @traviagio more or less holding my hand, onboarding was rather smooth. He crucially pointed out that I should call with Ian to get my KYC / passport verification done.

- @ian is actually the first one that gave me some more background about RChain during the verification call, and the enthusiasm was contagious (well done, Ian!).

- @traviagio had actually invited me with the specific instructions to do a marketing audit (which became #234), so that's where I started.

- Once that was on the rails, I had a good understanding of the main issues marketing-wise, and started contributing to a bunch of other issues. Multiple people picked up on my enthusiasm and involvement, and showed me around, such as @dckc 

- Honorable mention of where we got totally confused:  I sat with @traviagio about his December invoice, and together we deciphered how the financial spreadsheet worked. Took _forever_ to understand that (Bali internet on such a massive spreadsheet didn't help, either). 

That's where we're at today.

**Things that went well (onboarding-wise):**

- @traviagio pulling me inside the project

- A clear 1st project to work on (marketing audit)

- More senior members seeing my work, and helping me really get up to speed (Dan, Ian, Kit, etc.)


**Main friction points:**

- Setting up all the infrastructure (Discord, membership payment, Github (which I otherwise never use), Google Groups access, etc.)

- Scheduling the passport verification with Ian

- The financial spreadsheet

- 'Political' navigation: _"who should sign off on this?"_, _"Who is in charge of marketing?"_ and similar sort of questions/frustrations

**Comment by pmoorman** [comment]
Btw, thanks everyone  :+1:

**Comment by makys** [comment]
Researching new blockchain project I could get involved in to help understand blockchain technology - Rchain came up
I requested for access to one of the google doc and I got an email from @lapin7 which was my guide to getting on rchain coop. This was very good.
$20 to sign got me to think twice and whated to verify this was legit.
I looked up coop members on LinkedIn, contacted @Ojimadu just to validate his experience on the coop. @Ojimadu  sounded convincing, so I decided to join.
When I paid, I thought I would get a notice for verification, so I called +1 206-923-8417  (the number on the reciept to call if I have got any questions). I did not get a respond.
I literally had to keep asking to be verified, I did not get an invitation to get verified.
I jot on Github and there were tons of issues, I was reading through to get a sense of what was going on. Next I wanted to get involved so I commented on issues I wanted to work on a task, I wasn't sure what the norms are.
@pmoorman sent me a private message on Discord because I had mentioned I was interested in being involved in a task. @pmoorman helped guide me through this process.
I contacted @jimscarver that I'd like to be part of the BYOID project and he sent me link to it.

**Areas I am still unclear of:**
-Budgetting, voting and Invoice
-Creating SMART issues. 
-Identifying SMEs in various areas (maybe not applicable in this org)
-What the coop mission, vision, strategy is and if or where it is stated
-How Personal Information is secure and what privacy policy is in place (area I would consider working on if not in place)

**Comment by lapin7** [comment]
@makys Your story shows that you're very motivated. Even after going through an onboarding hell, like you did. Anyway you're all set now to make things better at RChain. :-)

**Comment by dckc** [comment]
Are we done here? The only thing left that I see is perhaps to expand the scope (change the title) to include the story from @makys and perhaps some part of her role / title: "Global Information Security and Privacy Professional"

**Comment by pmoorman** [comment]
Let's close it. If we want to include the scope of Makys, we should spin it out into a separate issue. One person, one issue (to keep things clean).
