### ISSUE TITLE
Rholang Documentation for upcoming Rholang Developers

### ISSUE THREAD

**Issue by David405** [rchain/bounties#298]
TASKS

- [ ] Create a comprehensive PDF document for Rholang I.e A cookbook or step by step process which will consists of downloading, installation of SDK,  syntax, building Rholang Applications.

- [ ]  Upload a simple demo Rholang App on github.

- [ ] Upload video tutorials covering the above tasks to our YouTube channel.

STATEMENT OF PROBLEM
There are no sufficient documentation and tutorials on Rholang for an intending developer to explore to become proficient in Rholang programming language. For example, I introduced  a php developer to Rholang and he would love to master the language but the challenge of not enough materials to explore has slowed down the process and I am certain he is not the only one affected by this. We need to do a lot of work concerning Rholang documentation if we want the language to scale.

JUSTIFICATION OF ISSUE
Each year, Google trains more than 10,000 new android developers in Africa alone while Microsoft also invests heavily in training C++, .NET developers. Other thriving open source languages such as php, java also dedicate a huge amount of their resources in putting up documentations, video tutorials, PDF tutorials just to ensure that more than enough developers get skilled in these languages. What are the results? The aforementioned languages power most of the applications we have today, and that is simply because there are just enough developers that are adequately skilled in these languages. 
I strongly believe that if Rholang must scale and be in use,  there must be just enough Rholang developers that can build Apps with Rholang.

A target for 10,000 RAM for set for year 2018 and if this target must be achieved then we must teach on boarding members the skills they require to be useful in solving issues. This  tutorials shouldn't just only be for Rholang but tutorials for other categories such marketing, operations should be created too.

LIMITATION
I understand that the Rholang is still in its infancy but I still believe that just enough documentation and tutorials can be created for developers like us to follow up with the language. Rholang will get better and better as time go by but we must start now to build an active community

**Comment by David405** [comment]
In this I will make reference to @dckc #295
And would love to know your take on this issue @laplin @dckc @belovedAquila @pmoorman and everyone else I failed to mention

**Comment by dckc** [comment]
Documentation is certainly important and welcome.

It will be easier for me to evaluate this task once you share a small piece of your work. Do you have any particular app in mind for the demo?

A detail: be sure to share the documentation in source form as well as PDF so that it can be collaboratively maintained.

Also, I suggest you make an inventory of the currently available rholang documentation so that you be confident that what you develop is consistent with documentation from other sources.

**Comment by dckc** [comment]
I understand why this is labelled as as **Development** and **Education** but it's not clear why label it as **Marketing** as well. I wonder what use people are making of the Marketing label. More on that in a separate issue, I suppose...

**Comment by dckc** [comment]
@flowpoint I see that you have assigned yourself to this issue; would you please comment on what you plan to do?

**Comment by David405** [comment]
@dckc I am looking at a very basic Application, one that could perform a simple function, What's your telegram or discord id? Let's collaborate on this because from your other issues I can see you are very interested in this topic

**Comment by David405** [comment]
Which one of you have used the Rholang before? @dckc @flowpoint

**Comment by dckc** [comment]
I have never written a Rholang application. I'm not sure anyone has, unless you count some [example contracts][4] in development by the core dev team.

My experience with Rholang is limited to
  - [some exercises at the whiteboard][1]
  - [reviewing a tutorial][2]
  - running some examples in the compiler web ui (#185)
  - [tweaking the grammar markup in an early draft of a spec][3]

My discord id is dckc, just like here in github. But I'm already involved in more projects than I have time for, so I doubt I can spend significant time on this one.

[1]: https://www.youtube.com/watch?v=0wi0txVf0Po&list=PLf2bbiic5ZjCPzin3gCSMGiBtbT8UO5o2&index=7&t=570s
[2]: https://github.com/rchain/Members/issues/169#issuecomment-358858461
[3]: https://github.com/dckc/rholang-spec
[4]: https://github.com/rchain/rchain/tree/master/rholang/examples

**Comment by flowpoint** [comment]
im not very experienced in it as rholang is very new, but i plan on doing some example contracts, and later i definitely would like to writeup an approachable guide into rholang from my viewpoint, but first we should discuss on where, the possibly multiple tutorials of rholang from different perspectives, fit besides https://developer.rchain.coop/tutorial

**Comment by cenyuhai** [comment]
The tutorial is too simple, I don't know what I can do with Rholang... 
It also make me confused. 
1. This example  for Mutable state is too long.
2.There are too many Secure design patterns. 2-3 design patterns will be better.
we should have a tutorial like https://solidity.readthedocs.io/en/develop/introduction-to-smart-contracts.html

**Comment by dckc** [comment]
Unfortunately, @cenyuhai, only a small part of the design of Rholang is complete, so what you can do with it today is not very much. It's unfortunate that the [SDK announcement blog item][1] doesn't mention this. I suggest you provide that feedback in the gitter channel linked from that blog item.

Meanwhile, Medha did explain in [her Feb 2 comment][2]. Greg and Medha have talked about it in the [weekly community debrief][3] too... I'm not sure which one it was, but there are several updates about the SDK release since number 60. Greg talked about how for the early releases, we can only afford to target those who are willing to go through a certain amount of pain to get involved.



[1]: https://medium.com/rchain-cooperative/sdk-v0-1-5f6bc35bf3e9
[2]: https://github.com/rchain/Members/issues/238#issuecomment-362648063
[3]: https://github.com/rchain/Members/wiki/Weekly-Debrief-Index

**Comment by dckc** [comment]
@flowpoint writes
> i plan on doing some example contracts ...

Note #255 is a specific issue on example contracts and points to some core team jira tickets.

**Comment by Valentine-Mario** [comment]
The documentation was not very concise and it was very hard to read plus the terminologies used were not explained.
take more on the installation, that's hell

**Comment by dckc** [comment]
I don't see why this was reopened.
