### ISSUE TITLE
anomalies in the 201801 budget / reward process

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#306]

**Comment by dckc** [comment]
moving [comment by @lapin7][1] here:

[1]: https://github.com/rchain/Members/issues/260#issuecomment-364417841

Please check the issues below and tell if @Keaycee earns a total of RHOC 6557.85 or $ 1,311.57 in a fair way.


Keaycee | 99 100 115 133 135 150 156 169 173 186 210 214 215 217 218 219 220 222 225 226 231 233 234 236 243 | 6557.85 | $ 1,311.57
-- | -- | -- | --


Check if OK
--
- [ ] 99
- [ ] 100
- [ ] 115
- [ ] 133
- [ ] 135
- [ ] 150
- [ ] 156
- [ ] 169
- [ ] 173
- [ ] 186
- [ ] 210
- [ ] 214
- [ ] 215
- [ ] 217
- [ ] 218
- [ ] 219
- [ ] 220
- [ ] 222
- [ ] 225
- [ ] 226
- [ ] 231
- [ ] 233
- [ ] 234
- [ ] 236
- [ ] 243

After two days, the result will be used to adjust his reward for January.

**Comment by dckc** [comment]
If I knew which issue had the highest reward, I would start there. But I don't see it as a good use of my time to review them all or even pick randomly.

**Comment by dckc** [comment]
I'm refreshing the data in the SQL webapp in order to review anomalies here.

I'm running into integrity constraints: not all the voters an workers are collaborators in this repo:

```
WARNING:__main__:unkonwn voter:
    pay_period  issue_num          voter amount
16  2018-01-01        115  coininterview    200
56  2018-01-01        185    KentShikama   1500
149 2018-01-01        230  feixingxiaozi   1500
210 2018-01-01        246        yyh1102   3000
225 2018-01-01        250     optictopic   2000
251 2018-01-01        257        yyh1102   2000
255 2018-01-01        258        yyh1102   2000
WARNING:__main__:unkonwn voter:
1   pay_period  issue_num    voter        worker  percent
577 2018-01-01        233  8lcarte       8lcarte        2
578 2018-01-01        233  8lcarte       Ojimadu       70
701 2018-01-01        242  yyh1102    AbnerZheng       20
702 2018-01-01        242  yyh1102   RowlandZhou       20
703 2018-01-01        242  yyh1102  linsheng9731       20
704 2018-01-01        242  yyh1102  rjl493456442       20
705 2018-01-01        242  yyh1102  yuhuanmocmoc       20
737 2018-01-01        246  yyh1102    AbnerZheng       25
738 2018-01-01        246  yyh1102  rjl493456442       25
739 2018-01-01        246  yyh1102       yyh1102       25
842 2018-01-01        257  yyh1102  linsheng9731       20
843 2018-01-01        257  yyh1102  rjl493456442       40
844 2018-01-01        257  yyh1102  yuhuanmocmoc       20
845 2018-01-01        257  yyh1102       yyh1102       20
862 2018-01-01        258  yyh1102  linsheng9731       20
863 2018-01-01        258  yyh1102  rjl493456442       40
864 2018-01-01        258  yyh1102  yuhuanmocmoc       20
865 2018-01-01        258  yyh1102       yyh1102       20
WARNING:__main__:unkonwn worker:
1   pay_period  issue_num          voter            worker  percent
175 2018-01-01        141         lapin7           8lcarte        5
274 2018-01-01        185     AbnerZheng       KentShikama        7
278 2018-01-01        185           dckc       KentShikama        7
354 2018-01-01        215  BelovedAquila  iamnathanwindsor        5
362 2018-01-01        215        Keaycee  iamnathanwindsor        3
367 2018-01-01        215      Mervyn853  iamnathanwindsor        5
374 2018-01-01        215        Ojimadu  iamnathanwindsor        2
579 2018-01-01        233        Ojimadu           8lcarte       20
728 2018-01-01        246     AbnerZheng           yyh1102       25
733 2018-01-01        246           dckc           yyh1102       22
736 2018-01-01        246   rjl493456442           yyh1102       25
795 2018-01-01        250         lapin7        optictopic        1
833 2018-01-01        257   linsheng9731           yyh1102       20
837 2018-01-01        257   rjl493456442           yyh1102       20
841 2018-01-01        257   yuhuanmocmoc           yyh1102       20
849 2018-01-01        258         lapin7           yyh1102      -75
853 2018-01-01        258   linsheng9731           yyh1102       20
857 2018-01-01        258   rjl493456442           yyh1102       20
861 2018-01-01        258   yuhuanmocmoc           yyh1102       20
```

**Comment by dckc** [comment]
Using the SQL webapp from #260, I get
  - $234 for #225 (looks like a consensus of voters including @kitblake )
  - between $10 and $100 for #100, #150, #215, #220 
  -  $-667 for #115
      - @Mervyn853 explained his negative rewards [Jan 29 in 115][1].
      - the spreadsheet seems to clamp the low end at $0
  - no reward for the rest (insufficient votes)

This seems reasonably well in order to me, though I hope others will look more closely at #100, #150, #215, #220.

[1]: https://github.com/rchain/Members/issues/115#issuecomment-361339337

**Comment by Rafkraft** [comment]
On #156 some good remarks on the header footer and pages for the designer and myself, don't know what budget has been settled for his work

**Comment by jimscarver** [comment]
@kaeycee has been very active and produced quality work and I think he deserves a bonus on top of the award amount

**Comment by dckc** [comment]
@jimscarver pointer to the quality work? H J can adjust rewards on a per issue basis. But I'd rather not get into ad-hoc bonuses.

**Comment by jimscarver** [comment]
I don't know when I'll have time to go over all the details. As the gov
working group evolved he did major updates to the scope document several
times. Any I saw significant comtribution all over the place. Nickel and
diming our members is not a productive activity in my view.  I do not see
how the reward could be considered excessive given the dedication show. It
is an insult in my view. I do agree we need to do oversight but I do not
think any reward system will be fair to everyone and we ought consider
bonuses rather than enabling people to nit pick the rewards for those they
may not like or appreciate.

**Comment by lapin7** [comment]
I will delete the comment.

**Comment by Tonyprisca13** [comment]
@Jim u are right. keaycee is dedicated and produces quality work. I checked it up and it is not bad at all.

**Comment by dckc** [comment]
@jimscarver writes:
> As the gov working group evolved he did major updates to the scope document several times.

A pointer to the relevant issue (#133) is all I asked for. Surely looking it up would have taken less time than the rest of your comment. :)

**Comment by drbloom** [comment]
Regarding issue (#133) - Large portions of the document "[SCOPE OF THE GOVERNANCE WORKING GROUP](https://docs.google.com/document/d/1U3elyL4y-H8Z6uBU61tiO0sRTWu7DeRmPjfdYgpUOKY/edit?usp=sharing)" are copied from other sources without Citation or Attribution.
See Shermin Voshmgir's Mar 12, 2017 Medium Article: [Blockchain’s Problem with Unknown Unknowns](https://medium.com/blockchain-hub/blockchains-problem-with-unknown-unknowns-6837e09ec495)

**Comment by jimscarver** [comment]
Adding references is something we need for the finished document. That the
document is not finished does not take away from the significant editing
done. That someone took the responsibility for the document is rare and
ought not be discouraged.

Yes Dan, I should have found the issue number yes kaecee has been active
everywhere and I certainly cannot investigate all the issues and doubt we
can get everyone he DMed with to validate every little thing.

But my intent was to object to the process here and vote against changing
his reward based on incomplete information. I get the feeling this is an
attack on a system that is working very well considering there is no
perfect solution. I agree we need to police ourselves with respect to
future rewards to whom we might consider bad actors but unless the reward
exceeds a living wage greatly we need to take responsibility ourselves for
the error, if any and not put our valuable contributors on trial. I believe
it sets a bad president.

The system is transparent providing for oversight by the membership and
coop management. One person being able to challenge another's reward and
divert all this coop energy to the issue seems a total waste of time making
a simple system highly complex while making all our members vulnerable. We
need to accept imperfection and correct for it in the future.

The value a member produces is highly subjective. Onboarding people I
encourage them to comment in the issue they are engaged with. Is agreeing
with a position not a contribution?  Comments reporting work product may be
more valuable than others and mopbody is suggesting otherwise. The comment
1% as I understand it intention is simply recognising engagement in the
issue and the value of their time.

I would not object to increasing the reward showing to thew world that
rchain rewards contributors with heart rather than bureaucratic
insensitivity.

Sorry for hijacking this issue. The compensation committee is where we
ought have a consensus before putting members on trial. The system is
working well enough and may be continually improved without nit picking
rhoc expenditures that cost us nothing in the first place.

**Comment by dckc** [comment]
This is done to my satisfaction.
