### ISSUE TITLE
M> Translate the RChain YouTube channel retreat video into Chinese

### ISSUE THREAD

**Issue by Whisker17** [rchain/bounties#384]
#347 @zsluedem  has create a crude subtitle for the retreat video,I and @han014 have reviewed the subtitle and translate this into Chinese for days.
fortunately,we have finished it now,what we have worked is [the  Architecture & Rholang Overview](https://www.youtube.com/watch?v=Fs38s7nI3Uk&list=PLf2bbiic5ZjCPzin3gCSMGiBtbT8UO5o2),and its total words is 9447,according to #347
And I'm not sure where should I upload this in the [Drive](https://drive.google.com/drive/u/0/folders/0Bx1gRG7UuoiJZ1lpSnZzenNzY00).Could u please tell us? @lapin7

**Comment by han014** [comment]
Since there are 9447 words in the video according to #347, the total money for our translation is $1889.4 if it is $0.2 for 1 English word.
@Whisker17  and I also reviewed the English words in the video, and I wonder that if it is regarded as the additional work? @lapin7

**Comment by zsluedem** [comment]
WOW~!send me the translated video or upload the the google drive and I will put up the subtitle into the video and upload to the Chinese video webside~!

**Comment by han014** [comment]
Since there are 9447 words in the video according to #347, the total money for our translation is $1889.4 if it is $0.2 for 1 English word.
@Whisker17 and I also reviewed the English words in the video, and I wonder that if it is regarded as the additional work? 
And I'm not sure where should I upload this in the Drive.Could u please tell us?@BelovedAquila

**Comment by han014** [comment]
The srt files of reviewed English version and translated Chinese version are attached in this email.


Best wishes,

________________________________
发件人: will <notifications@github.com>
发送时间: 2018年2月20日 19:00:25
收件人: rchain/bounties
抄送: #LU; Mention
主题: Re: [rchain/bounties] M> Translate the RChain YouTube channel retreat video into Chinese (#384)


WOW~!send me the translated video or upload the the google drive and I will put up the subtitle into the video and upload to the Chinese video webside~!

―

**Comment by ICA3DaR5** [comment]
So, there is a good English version of this? I am interested in translating to Greek.

**Comment by zsluedem** [comment]
@ICA3DaR5 check #347

**Comment by ICA3DaR5** [comment]
@zsluedem Great!

**Comment by Whisker17** [comment]
@lapin7 I'm not sure if the review work should regard as another work and I dont know how should I set the budget

**Comment by zsluedem** [comment]
@Whisker17 I can review the translation.

**Comment by han014** [comment]
Since there are 9447 words in the video according to #347, the total money for our translation is $1889.4 if it is $0.2 for 1 English word.
@Whisker17 and I also reviewed the English words in the video, and I wonder that if it is regarded as the additional work?
And I'm not sure where should I upload this in the Drive.Could u please tell us?@ICA3DaR5

**Comment by ICA3DaR5** [comment]
@han014 Upload them [here](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii) with an appropriate title.

**Comment by LiliNL** [comment]
Whisker17
--
han014
zsluedem
ICA3DaR5
lapin7

Please set a budget and give your percentages for each of above. Find out yourselves how a review should be rewarded. It's up to this team.

**Comment by lapin7** [comment]
Member | 0.00%
-- | --
@Whisker17  | 0.00%
@han014 | 0.00%
@zsluedem | 0.00%
@ICA3DaR5  | 0.00%
@lapin7 | 0.00%


Please set a budget and give your percentages for each of above. Find out yourselves how a review should be rewarded. It's up to this team.

**Comment by Whisker17** [comment]
@lapin7  the total words is 9447,so the total money for our translation is $1889.4 if it is $0.2 for 1 English word,we have [upload](https://drive.google.com/drive/folders/1Q1ZvWI6DCr2CTFoEtcm6cuW9Ylir5QD1) the English subtitle(reviewed) and the Chinese version,so I think it worth $1889.4*2 = $3778.8

**Comment by lapin7** [comment]
@Whisker17 you don't have to ask my permission for this budget. If you think $1889.4*2 is OK and good for RChain, then go ahead. But I will vote it down, because I don't understand the *2. I would rather say the $1889.4 is for the budget for the team that works on it.

Please go ahead and set the budget here.
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965&range=A248:N248


384 |   | M> Translate the RChain YouTube channel retreat video into Chinese | Marketing | $ - | $ - | $ - | ⍴ - | $ - | OPEN | 0 |   |   | Whisker17
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by Whisker17** [comment]
@lapin7 I think the review should be another work,but I'm not sure how to judge it since the translation is $0.2 a word,so I thought the review should be regarded as an English version subtitle which is also $0.2 a word,but if u don't agree,it's OK

**Comment by lapin7** [comment]
$0.20 is for the whole process. Intake, analyse, translation, review, delivery.

**Comment by Whisker17** [comment]
Cool，I‘ll close this issue cuz it's done

**Comment by lapin7** [comment]
@han014 please send your email, name, discord name to ops@rchain.coop. It's needed for invoicing
