### ISSUE TITLE
O> Constrain bounty voters and payees to Coop members with KYC

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#391]
While having a low barrier to entry for collaboration has led to some great outcomes, paying invoices to non-members raises risks, as does letting non-members vote on budgets and rewards. @kitblake and @kennyrowe and the rest of the executive committee agreed to refine / clarify the **bounty-contract** so that only RChain Cooperative members receive these benefits.

**Goal:** update to CONTRIBUTING.md (PR #396)

I'm working with @drbloom on a technical enforcement mechanism using discord and OAuth, as part of the web app (#260).

I expect the policy should affect the 201802 payment cycle, regardless of whether the web app is done by then.

ref: [Executive Committee February 16th, 2018 , working lunch at the Governance Forum](https://docs.google.com/document/d/1XwQoXBT6YsnUUSmRjOnqCehyR49_rwqOKhj3zDObdOE/edit)

cc @lapin7 @dcpnlau

**Comment by makys** [comment]
@dckc:
Will this imply that bounties will be held back until verification is done or contributors will lose their bounty?

**Comment by dckc** [comment]
Perhaps you could elaborate the question? I don't understand. If a contributor is not a member, no bounty is theirs to lose.

**Comment by Ojimadu** [comment]
This was the status quo. I think January should be the first time non-members were paid by the coop.
I remember @kitblake raised a point about having to pay to "be a member" or to "collaborate" on an open-source platform but since this repository has been renamed to 'bounties', this has to be stated in the Contributing.md document.

Since this is just coming in, bounties for February should be paid to whoever participated or contributed to an issue as they weren't aware of it and should be rewarded for their work n

**Comment by Tonyprisca13** [comment]
If a contributor has worked on an issue he or she should be rewarded for this month and then notified of the new development going forward.

**Comment by pythonical** [comment]
I didn’t realize you didn’t have to be a member to get bounties and you also can vote on rewards? In that case what’s to keep me from creating multiple personas and voting for myself?

**Comment by ICA3DaR5** [comment]
@pythonical Exactly!

**Comment by lapin7** [comment]
@pythonical In principal I expect that we work in good faith. If one creates multiple personas and votes for him/herself then that doesn't help RChain forward. I hope that multiple personas will be quickly discovered by the peer collaborators and that proper actions are taken. I think for example that collaborators must have the power to "kill" other collaborators, instead of escalating things up hierarchy.
So we have rewards and fines, carrots and sticks for each. Let's see how this works out.
Until now it goes fairly well. :-)

**Comment by Viraculous** [comment]
Am in consonance with @dckc @pythonical.As platform with cooperative modelling, rebates should be restricted to members. I think the issue here is basically checkmating duplication of personas from non-member collaborators in order to avoid multiple vote and reward allocation  to an individual. Firstly I think this should be considered before taking actions; What was the initial terms of the bounty contract? Did it restrict rewards and voting to only member collaborators or both member and non-member collaborator? If it does for both, I think the effect of the policy shouldn't affect 201802 budget because, ceteris paribus, the cycle should have ended by now and secondly, as there were yet no contractual restriction of rewards and voting to only member collaborators, implications of the refined policy shouldn't affect 201802 rewards cycle since it was not defined or included in the bounty contract used for January. Like @lapin7  said  > In principal I expect that we work in good faith ...>, I think bounties for 201802 should be classified as work assumed to be done in good faith. However, if the restrictions has been there before 201803 February to only members  it can affect  bounties in January but with the notice of non-member collaborators. The need giving notice to non-member collaborators on the bounty contract restricting rewards and voting access to members only is to encourage innovative and active collaborators move from activist to member proper and discourage bad actions in budget rewards allocation and voting. Secondly, what will happen to helpful, innovative and sincere members whose contributions have added value to the community? Will their efforts be discarded or discouraged because of bad actors?  A labourer is worthy of wage. I suggest likewise like @Ojimadu pointed, the implementation of the policy due not fromr February but possibly from 201804 bounties since collaborators are yet to know the terms of bounty contact while we in good faith we discover bad actors like @lapin7  mentioned by peer collaborators.

**Comment by dckc** [comment]
Is there really anyone who wants to collect a 201802 bounty but not become a coop member? I could perhaps arrange for exceptions to be considered on a case by case basis, but in general it really doesn't seem too much to ask.

**Comment by ICA3DaR5** [comment]
True. If you are going to hunt bounties, $20 is not much for the membership.

**Comment by Viraculous** [comment]
@dckc and @ICA3DaR5  that's why the bounty policy must be widespread to the notice of the collaborators before implementation for better rational decision from non-member collaborators  as cited.

**Comment by dckc** [comment]
@Viraculous writes:
> the bounty policy must be widespread to the notice of the collaborators 

Agreed; I suggest that collaborators need only stay tuned for issues with the [bounty-contract](https://github.com/rchain/bounties/issues?utf8=%E2%9C%93&q=label%3Abounty-contract) label to be informed of changes.

> What was the initial terms of the bounty contract? ...

I made some effort to document that: https://github.com/rchain/bounties/issues/78#issuecomment-367208156

In particular, there has always been a **Centralized Payment process** step where coop officers review invoices before payment. Payments to possible non-members have been a source of friction at that point; hence this refinement / clarification. Rather than leaving it as a matter of opaque discretion, we're making it more transparent.

**Comment by dckc** [comment]
@BelovedAquila are you personally asking to be paid bounties without joining the coop? Or are you, @Viraculous?

Or are you asking on behalf of some specific person whose github name you will please share?

Or are you asking on behalf of hypothetical parties who may get insufficient notice? As I mentioned above, payments to such parties have always been at the discretion of the coop officers. The coop officers have requested that the executive committee clarify this point, and we are now attempting to do so.

**Comment by BelovedAquila** [comment]
@dckc I suppose a member doesn't have a second need to re-register by means of the new mechanism, so wouldn't be needing it for myself. And don't have any specific person in mind, just making a kind of allocutus plea on behalf of the below stated, 

  > Or are you asking on behalf of hypothetical parties who may get insufficient notice? As I mentioned above, payments to such parties have always been at the discretion of the coop officers. The coop officers have requested that the executive committee clarify this point, and we are now attempting to do so

Because every rule, law or policy made should be made on a balanced scale, considering other vital factors, we don't just assume it would be fitting and applicable at just anytime and to just any people. but since the coop officers fully have intentions of justifying it,having basic factors in mind as you said, then what stops it? Go on friend.

**Comment by dckc** [comment]
I don't understand your point. I read your comment several times.

> ... by means of the new mechanism

What new mechanism?

> ... every rule, law or policy made should be made on a balanced scale ...

The policy was made by the RChain executive committee, on a balanced scale to the best of our ability. I don't see anything in your comments that we didn't consider in making our decision.

Note comments above showing that several already understood this to be the policy, so it really is as much a clarification as a change.

**Comment by Viraculous** [comment]
@dckc was wondering the base of your question though; as I never see where I requested or inferred that I personally be paid bounties without joining the coop. I am a legit member of the coop with entrance fee duly paid and so would I for every non-member who is a collaborator with us on github. In drafting out a policy that affect an environment, care must be taken to avoid biasness of the policy by ensuring that both the internal and external variables of the environment are captured within the policy. This is necessary to ensure equity. I was only trying to bring this factors though passive to be captured in the policy so that non-member collaborators active and helpful interest will be represented to enable them make rational decision. I am of greater opinion to creating the awareness of such policy to non-members before implementation like I cited, it will encourage them move from Activist to members and discourage fraudulent tendencies.

**Comment by BelovedAquila** [comment]
@dckc the comment is self explanatory, you not understanding seem to be a personal issue.


 > Note comments above showing that several already understood this to be the policy, so it really is as much a clarification as a change.

Saying SEVERAL  based on the few number of github users who commented here,  as compared to the other greater number of exceptions not present here, is shallow. besides Iike everyone here is already a legit member,believed to have known the policy, so this issue wouldn't apply to them nor affect them. We are to put into consideration  those newbies making vital contributions, who are not yet members, who the policy is more likely to affect,and of which I believe is being considered by the coop officers as you said, that's the main point.
 So each comments here isn't made on any personal preference but on a cooperative consideration believed to be for a general good.
Cheers!

**Comment by dckc** [comment]
@Viraculous unfortunately it's not straightforward for me to look up who is a paid member and who is not.

You write:
> I think bounties for 201802 should be classified as work assumed to be done in good faith

and as long as everyone who expects to vote on or collect a bounty is a member, we can agree with no need for me to take this back to the executive committee for reconsideration.

Given the relatively small and young nature of our community, I would make much more effort to ensure consideration of any concrete cases of a person put in a difficult situation by this evolution than I would to ensure follow-up on "what if?" situations.

**Comment by lapin7** [comment]
Just as the coop asks to fill out a tax form W8 or W9 before payment happens, the coop can also ask to become an official member of the coop in order to receive bounties. It can be implemented for the work done in February. I don't see a big point in membership or not.
Paid membership is also a hurdle for trolls and other bad-actors. :-)

**Comment by dckc** [comment]
@lapin7 the **RAM-weekly-agenda** label is still on this, which suggests it was not addressed in the Feb 21 meeting (#381); was it?

Or it could be that the norm of removing the label when the meeting addresses it is not established. What do you think about that norm?

**Comment by lapin7** [comment]
The subject "Membership and bounty" has been addressed, but it didn't go towards a decision.
Let's decide about it in the meeting of 2018-02-28 and leave the label on until decision has been made. (good norm)

**Comment by ICA3DaR5** [comment]
Merged #396

**Comment by dckc** [comment]
Now that #396 is merged in c1cc50c, I guess we're done here.

_p.s. note to self: just use a PR next time, not a separate issue and PR._

**Comment by dckc** [comment]
The SQL code that counts votes ([dbr_views.sql](https://github.com/dckc/rchain-dbr/blob/master/dbr_views.sql)) should be updated to include this constraint.

**Comment by dckc** [comment]
all set:
 - 6741b4f master only count votes from verified_coop members
