### ISSUE TITLE
Migrate budget, reward data from Gsheet to SQL db

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#415]
I got 201801 mostly done, but in order for carry-over budgets to work, we have to go all the way back to the beginning (201708, I think).

I prototyped it using a jupyter notebook, but it's now more packaged:

[dbr_norm1.py](https://github.com/dckc/rchain-dbr/blob/master/dbr_norm1.py)

```

Usage:
  dbr_norm1 [options] save_sheets <xlsx>
  dbr_norm1 [options] normalize
  dbr_norm1 [options] insert
Options:
  <xlsx>               the big spreadsheet in .xls format
                       e.g. 'Pub Member Budget Allocation-Spending.xlsx'
  --pay-period=YYYYMM  pay period in YYYYMM format [default: 201801]
  --data-dir=DIR       where to save CSV, pkl files [default: sheets]
  --db-access=FILE     where to find access credentials
                       [default: ram-dbr-db-access.json]
```

splitting this out of #260

**Comment by BelovedAquila** [comment]
@dckc I find this impressive, using the Gsheet tends to have many lags such as it being quite slow and it freezing a lot,especially in cases of numerous rows and data volumes. gladly the transfer of the Reward and Budget sheets to the SQL would really go along way in resolving this as SQL seldom slacks on account of data volume as compared to Gsheet. Nice one friend

**Comment by Pionelle** [comment]
The Google sheets is a well used and allows for phone tablet or pc access. can SQL be adequate for Coop uses and constant access to the spread sheet.

**Comment by BelovedAquila** [comment]
@Pionelle actually Gsheet is actually accommodating as regards to various device access,  but Gsheet kind of makes data integrity  harder to manage when using its spreadsheets. I know with SQL database management system, several people can access the same data set. Such that it's  system manages editing of data so that two people cannot alter the same data values at the same time. And this preserves data integrity, which Gsheets seldom does.     
The SQL can also allow for phone tablets or pc access I suppose, by downloading an SQL viewer. But can't really say if it did be adequate enough for Coop uses though, but it's pros kind of outweighs. No harm in trying seemly better options you know?

**Comment by lapin7** [comment]
Yeah, yeah I know the limits of Gsheet. But it was the quickest way to get started. Hopefully the Gsheet solution will die gracefully in Feb and in March we can implement the SQL system of @dckc.

**Comment by dckc** [comment]
@lapin7 wrote:
> I’m wondering if old budgets have to carry over anyway. I don’t see a need.

I guess I'll open a separate issue to change the **bounty-contract** so that budgets don't carry over.

**Comment by dckc** [comment]
Let's skip this until / unless it seems more important.
