### ISSUE TITLE
Publish co-op governance (esp executive committee) Google docs in Rchain.coop Domain

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#418]
just like #411, but for google docs

see: [google sites custom domains](https://support.google.com/domains/answer/6069257?hl=en)

cc @patrick727 @jeremybusk @kennyrowe @hyperevo

**Comment by dckc** [comment]
brainstorm: let's do this for notes from the Governance Forum

**Comment by dckc** [comment]
@ian-bloom maybe the executive committee is a place to start? Would you please make a subdomain of rchain.coop for the executive committee (perhaps **exec-comm**.rchain.coop ?) and connect it to a google site and give me write access?

**Comment by dckc** [comment]
very nice, @ian-bloom : https://www.gov.rchain.coop/executive-committee

cc @patrick727 @jeremybusk @Jake-Gillberg

**Comment by ian-bloom** [comment]
<copy of my response in #exec-committee on Discord>

ian: - Today at 12:28 AM
@AyAyRon_P: Thanks for the png. This is just a GSite for now, to help sort shared Google Documents. Our new member site WordPress can be more ambitious. @dckc: and @Coin Physicist: have been doing some great work that should help us connect actual Co-op members (as attested by Discord role) with WordPress and bounties/rewards.

@dckc: - Thanks for jumping in to help. I was still kicking the tires and trying to see if I could knock the www off of the url. We might just have to live with it because the DNS is hosted outside of Google. Dan, publish permission is now open to Exec-Committee members. We can do the same for other Committees and well established WG if this tool is useful, although I'm not sure how it will fit in with the WP.

**Comment by dckc** [comment]
This approach seems to be working for https://www.gov.rchain.coop/principles-and-values-wg too.

@ian-bloom and I chatted about wordpress vs. google sites / docs for this sort of thing and we're more or less content to continue with the google sites / docs pattern, with links from wordpress etc. The "less content" part is because the individual docs still get `google.com` addresses rather than `rchain.coop` addresses.
