### ISSUE TITLE
M> Translate Casper Proof-of-Stake on RChain into Chinese

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#425]
Background:Many people in channel of Chinese QQ group have huge interest in Casper Proof-of-Stake on RChain. So I am prepare to spread it in them. 
Work: 1)obtain the introduce in youtube([Casper Proof-of-Stake on RChain](https://www.youtube.com/watch?v=qJFCtmlCu-0&list=PLf2bbiic5ZjCPzin3gCSMGiBtbT8UO5o2&index=8)), 2) translate it in Chinese.
Budget: from $1500 to $2000. I will append the budget intime base the whole work.
Time: about a week.

**Comment by zsluedem** [comment]
Once you make it done, I can help review the subtitle

**Comment by zsluedem** [comment]
#347 has the google generated English subtitle

**Comment by JieL314** [comment]
Welcome! 
The English subtitle which generated by google can't be accuracy. So the verification is important. 
I will inform u when the work were been done.

**Comment by JieL314** [comment]
The subtitles for both videos are approximately 5200 words. So the budget for translation is $1040($0.2 per word). the another budget for $600 is set to understand, handle and rectify subtitles. So the total budget is set to $1640.

**Comment by hcl3** [comment]
That‘s great

**Comment by zsluedem** [comment]
This one is ok to close!

**Comment by ICA3DaR5** [comment]
Could you please post a link of the final work done here for public view?

Thanks!

**Comment by zsluedem** [comment]
@ICA3DaR5 Ok~!trying to get to the man~!

**Comment by zsluedem** [comment]
https://drive.google.com/drive/folders/1q6njv5uzIRkGX9WxupbFTaxlZlqD2MFw
Finally get to the man.The work is done here.

**Comment by ICA3DaR5** [comment]
So if I understand correctly you got payed $1640 for two pages?

Please elaborate. @zsluedem @JieL314

**Comment by allancto** [comment]
@ICA3DaR5 my understanding is that this work was already rewarded in February. @zsluedem is simply posting the work retroactively so it can be available to everyone. If #425 is not up for vote now I'd recommend the issue can be closed again. @zsluedem @JieL314 thanks for posting the work product, i got to watch a video and run google translate Chinese to English :) :) :)

@zsluedem @JieL314 I hope you all continue to follow Casper development, the development is ongoing and Casper Standup is posted on youtube every week. Also Greg spoke about the tradeoff between fees and transaction volume in this week's debrief, the Casper theory all plays out in the Validator discussion. The economic role of sharding is also an interesting topic and important for prospective validators to be aware of. 

Thanks! -@allancto

**Comment by zsluedem** [comment]
@ICA3DaR5 
I am sorry that I haven't elaborated things clearly.

This issue was created in Feb.And I have check the [spreadsheet](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=592953635) from #637 the reward has already been given to the contributors for **$1640**. I have checked my invoice in Feb which I got **$32.8** from this issue which is **2%** of **$1640**.

I am **not a translator** or a **reviewer** in this issue. My job in this issue is to bake the subtitle into the videos and upload them to China website. You can check my work done below which I think **$32.8** is reasonable.
1. https://space.bilibili.com/286283912/#/video?tid=0&page=4&keyword=&order=pubdate
2. https://www.bilibili.com/video/av19240432/

The bounty policy wasn't elegant and explicit enough in Feb so they may set an unreasonable price for it.(That's why we should have guides and trust metrics now) There are actually two subtitles of this issue.(the one I posted above is a draft one and they have lost final ones somewhere ask them to remake it based on the video again)Post here.
1. https://docs.google.com/document/d/15fSjf4qLrfgEO1zLNoiITBezBJHwDWNfdJOCPZLy2Jc/edit
2. https://docs.google.com/document/d/1AQ0ERpZFisWpeeBtnTbyIm1UNU3xn_ce55N7Zn03ftw/edit?usp=drive_web&ouid=115573881377148283245

@ICA3DaR5 If you have any questions or anything I have stated above is not clear , please ask. I would be glad to answer it :).BTW, there is no one going to claim any rewards for this issue anymore(No votes in June and in the future). So close it if everything is clear.

**Comment by ICA3DaR5** [comment]
@zsluedem Closing this, your elaboration is clear as far as I am concerned!
