### ISSUE TITLE
RChain Coop Membership Benefit

### ISSUE THREAD

**Issue by makys** [rchain/bounties#520]
As we spread the word on RChain and encourage our friends to join the coop, one question that is most likely to pop is 'What are the benefits of joining the RChain Coop". The reasons definitely may vary for each person. 

In the [Membership Agreement](https://github.com/rchain/legaldocs/blob/master/Coop_Membership_Agreement.md) A3-A5 seems to itemize the benefit. However I believe there is more and more so what is **relateable.**

This issue seeks to:

- Collate what benefits there are to joining the coop.

- Document the benefits in a concise way.

https://docs.google.com/document/d/1qotvfri8UbYYsld1cPe914W8wMVBfHaiGEwgLUryDes/edit?usp=sharing

**Comment by kitblake** [comment]
@makys I'll add some things to your doc (copied here for efficiency, we can copy back later):

**RChain Coop Membership Benefit**
- Participate in Rewards/Bounty system
- Participation in Co-op Governance
- Access to member-channel on Discord and member portal (when built)
- Early access to offering by co-op partners

Following is a text that was used on the first Activist Registration form:

If you're interested in becoming a Member of the Cooperative there are several key benefits:
- Members elect the board
- Members get annual dividends of REV used on contracts executed on the network
- Each paying member receives a stake of 100 RHOC

There are additional roles that Members might play, for instance:
• Proposing projects (with deliverables, milestones, budget)
• Deciding about approval of projects
• Deciding about allocation of budgets
• Other governance items

**Comment by ResonanceXX** [comment]
I always use the viability of the Cooperative's involvement in birthing a newer Blockchain solution as somekind of evangelical persuasion. 

Everybody in and around the Blockchain world asides from the financial emoluments/incentives involved would also like to be 'timestamped' to a project such as ours'.

Personally, I remain very satisfied that in some way, we are contributing to the future of the world - technologically.

**Comment by Ojimadu** [comment]
> **RChain Coop Membership Benefit**
- Participate in Rewards/Bounty system
- Participation in Co-op Governance
- Access to member-channel on Discord and member portal (when built)
- Early access to offering by co-op partners

The points made above encompasses the benefits. Am inclined to make it a five pointer by adding this
> -Members get annual dividends of REV used on contracts executed on the network
But there has not been any definition on how that would work. Severally, I've been asked to clarify that point but since we don't REVs yet it would be quite problematic to explain.

Also, for this point
> -Each paying member receives a stake of 100 RHOC

I can't remember seeing this anywhere, Any lead? I also assume the exact details of this is yet to be defined as well.

> There are additional roles that Members might play, for instance:
• Proposing projects (with deliverables, milestones, budget)
• Deciding about approval of projects
• Deciding about allocation of budgets
• Other governance items

I see all the above as participating in the co-op's governance process.

I would like us to limit the stated benefits to 4-6 so we don't overpromise whatever comes as benefits along the way can be considered a plus but not an entitled benefit.

**Comment by Tonyprisca13** [comment]
It's good we dont over emphasize the benefits lets stick to what we are sure to give.

**Comment by kitblake** [comment]
@Ojimadu That point about "Each paying member receives a stake of 100 RHOC" was in the reg form, but it's certainly rather generous for today. I think the idea was that a new member gets the $20 back in RHOC. 

@Tonyprisca13 The REV rebate is an artifact from using REI as a model for the cooperative setup. REI has a rebate program (basically air miles) and the Coop thought of doing something similar. But since how it will actually work hasn't been defined I think we shouldn't mention it for now. It's vague. 

Can anybody think of something else? If not, we have a list and more replete descriptions could be written as content for the member site.

**Comment by Keaycee** [comment]
@kitblake I support your view on 

> -I think the idea was that a new member gets the $20 back in RHOC

However, i think this should be on a full membership registration on all the major RChain community Channels like:
Github
Discord
Telegram
Google group

It's only a suggestion.

**Comment by pmoorman** [comment]
Hey all, I was on a call with @dckc and @ian-bloom yesterday, and **it was decided we should make the signup flow to become a members more smooth.** 

Right now the flow is:  

> you're on the homepage => click "become a member" => login screen

The new flow will be: 

> homepage => click "become a member" => see a page about why you should join => registration screen.

That 'sales page' for lack of a better word in the middle we'll build on Squarespace, and we could take input from the above discussion, and integrate it. I have the Squarespace credentials, so I can actually execute this task.

We'll recycle [this page](https://www.rchain.coop/coop-information-1) into something cool and exciting. I'll send a ping when I have a first version ready 😃 


If anyone has any specific ideas / suggestions / concepts that they would like to see integrated but haven't mentioned yet here... then this is a great moment to tell me!!

**Comment by kitblake** [comment]
Can somebody look in the stats and check the referrals of visitors coming into member.rchain.coop?

That URL is published in a lot of places, not just the homepage, and it would be really interesting if we could find out from where new registrants are arriving. A sizable number might be coming from Telegram. 

But making the arrival more friendly is certainly something to do. Now. 

In issue #446 there's discussion of making an MVP of the future members.rchain.coop. In that incarnation it would be better to have the 'sales page' be the home page of members.rchain.coop (as opposed to in Squarespace, which only intercepts visitors arriving via rchain.coop). Then regardless of the referral, new users "see a page about why you should join".

**Comment by kitblake** [comment]
@makys I tried to edit your doc but don't have permission, so here it is in plain text. 
Nice last line you added about the future of the world.. 
@pmoorman ^^ 

### What are the benefits of joining the RChain Cooperative?

Members can:

- Attend and vote at annual and special membership meetings.
- Elect the Board of Directors.
- Participate in Co-op Governance.
- Participate in the Bounty/Rewards system.
- Access the members-only channel on Discord.
- Get early access to offerings by Co-op partners.
- Have the opportunity to contribute to the future of the world – technologically.

**Comment by pmoorman** [comment]
@kitblake credit to the last "future of the world" line goes to @ResonanceXX I think (or at least: not to me)

@kitblake in response to:

> In issue #446 there's discussion of making an MVP of the future members.rchain.coop. In that incarnation it would be better to have the 'sales page' be the home page of members.rchain.coop

The thinking is that it's much easier to edit Squarespace at the present moment than edit the member.rchain.coop domain, so for a very practical reason we'll host that sales page there. For now this is just easier.

What we could do, is point all the traffic (incl. from Telegram) to that sales page. That would have the same effect (although old links would need to be updated/redirected, so that's a disadvantage)

**Comment by kitblake** [comment]
Ah, now I see the comment from @ResonanceXX, must be @makys added it the GDoc. Nice work boys and girls.

@pmoorman Why don't you forge ahead and make a rchain.coop/benefits-of-joining-the-co-op page in Squarespace. That can then have a CTA, maybe a [I want to join button]{member.rchain.coop}. 

But I don't think we should edit all the links to member.rchain.coop to point to Squarespace in:
- Telegram pinned messages
- the FAQ
- CONTRIBUTING.md
- various issues and other places

Better to just wait until we get control of member.rchain.coop and then we make the homepage list the benefits-of-joining-the-co-op. So your Squarespace content can be transferred to /index in member.rchain.coop.

**Comment by kitblake** [comment]
@ian-bloom:
IF we don't have a new KYC app 
&nbsp;&nbsp;&nbsp;&nbsp; (but we want to get that landing page with benefits-of-joining-the-co-op up)
THEN we could relocate the KYC app to kyc.rchain.coop
&nbsp;&nbsp;&nbsp;&nbsp;and use member.rchain.coop for the WP instance.

**Comment by pmoorman** [comment]
@kitblake exactly our thinking!  **I plan to work on it in the next few days.** I'll be out-of-office Friday and Saturday, but my intention is to get the page updated before that. 

**As for updating external links:** I don't have a strong opinion about it for now, and other people have a better view on that then I do. So let's keep that as-is for now, and we could update things once we regain control of the member.rchain.coop subdomain
