### ISSUE TITLE
Choose a CMS for member.rchain.coop

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#521]
As the member site will be a collaborative effort, the public facing content should be stored in a content management system. Which one is the subject of this issue. 

In the grand-antecedent to this issue, #400, a number of people liked the idea of WordPress. If that's still the case and the various stakeholders can agree on it, then we're done. 

Drupal (a PHP system) was also mentioned, and there's a plethora of other contenders. My personal req is that the system must have a visual WYSIWYG editor, so content can be copy/pasted from other HTML sources such as websites and Google docs. 

Measure of Completion: a CMS has been chosen and approved
Suggested Budget: $200

**Comment by zsluedem** [comment]
http://www.cmsmatrix.org/  this is a website for Comparing different cms systems. It helped us compare between different systems by features we want.

**Comment by dckc** [comment]
> As the member site will be a collaborative effort ...

I haven't seen that established as a fact yet. I've seen several wishes for such a thing, but nothing that proves we can't meet our goals without it. I'd agree with "will likely be a collaborative effort..." or "should be...".

When I asked in #446 what we need WordPress (or the like) for, the answers included a blog and a dynamic FAQ, but we have those already, and it's not clear that those who maintain them want to change the way they to it. (They're currently [sharecropping](https://github.com/rchain/bounties/wiki/Social-Media-Strangle-Hold), so I'd sure like to change that!)

> My personal req is that the system must have a visual WYSIWYG editor

Do you have any plans to use the CMS personally, @kitblake ? If so, what are one or two of the first documents you plan to work on?

**Comment by kitblake** [comment]
If the member site will not be a collaborative effort, then whoever gets tasked with maintaining it can make the call on the underlying content system. 

If it will be collaborative then we need a system that controls access rights on a content level. There are lots of CMSs that do this, often with an LDAP integration. 

Personally there are a number of docs that I'd like to contribute to (note that we don't need a running CMS to get content ready). One doc in particular is, "Structure of the Coop and related entities (Pyrofex, Pithia, Reflective)". That will probably be a 'dynamic' doc like the FAQ, requiring regular revision.

**Comment by dckc** [comment]
> ... docs that I'd like to contribute to ...  in particular ... "Structure of the Coop and related entities (Pyrofex, Pithia, Reflective)".

I approached that using the wiki in this repo: [RChain Organization](https://github.com/rchain/bounties/wiki/RChain-Organization). You're more than welcome to fix / add anything there as you see fit; I don't suppose it meets your WYSIWYG requirement, though. I'm pretty comfortable with markdown, especially paired with a git history. My only reservation with this arrangement is that it's not in the rchain.coop domain; but I hope / expect / plan to fix that in #411 .

**Comment by ian-bloom** [comment]
I wish WP did version control as well as GitHub, and that GitHub was as extensible as WP. Rather than have a big debate over which platform is better, I'm proceeding with Jeremy Busk to self-host a WP with a minimal set of plugins.

Ideally, content on the WP will be [synced](https://premium.wpmudev.org/blog/syncing-git-wordpress/) with GitHub. Greg Meredith has previously requested that all website history was saved to GitHub. For you old-timers out there, you may recall the Synereo Bounties we paid for Blog summaries of Greg's weekly Wed 11AM PST call. (Example [here](https://blog.synereo.com/2016/05/18/synereo-community-hangout-may-18/))

In my experience, WP has an easier learning curve for less technical contributors to jump in and contribute content.

I asked @ICA3DaR5 which WP Plugin was better for multi-language [WPML](https://wpml.org/) vs [Polylang](https://wordpress.org/plugins/polylang/). He has more experience working with both, and recommends Polyglot. He also recommended a very cool translation platform, [Weblate](https://weblate.org/en/).

**Comment by kitblake** [comment]
@ian-bloom Nice. I was hoping to avoid a big debate too. Personally I'm CMS-agnostic. WP is fine. 
Looks like we can close this issue.

**Comment by dckc** [comment]
I'm experimenting with **duplicate** to mean: doesn't really merit a budget / reward by itself.
