### ISSUE TITLE
The management of Chinese translation group

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#552]
There are many works were been done in the past few months. Base it, RChain is attracts more attention from investors and developer. The [issue230](https://github.com/rchain/bounties/issues/230) has stop in Feb.. So I re-launch a issue for continue the work, and the old one(230) can be closed. 
The total budge is set $1000, include management and encouragement. 
The number of QQ group is 695298523. Welcome to join us.

**Comment by rjl493456442** [comment]
To be honest, there is no necessary to manage another translation group, since all translation target will be decided by rchain cooperative(May be @ICA3DaR5 is in charge of this). 

So all the contributors just need to set up an issue, translate the original post and upload to the proper place.

**Comment by yuhuanmocmoc** [comment]
I quite agree with @rjl493456442 ，there is no need to manage another translation group temporarily.

**Comment by yyh1102** [comment]
Glad to hear that you have built a translation group. @JieL314 But i agree with @rjl493456442 . You can just create an issue to say which doc you want to translate, and then assign work to your members~

**Comment by JieL314** [comment]
Actually, the group is not built by me, also the issue is not a new issue, but to continue [issue230](https://github.com/rchain/bounties/issues/230). 
The budget of this issue is mainly to motivate people to improve the quality of translation. Similar reward mechanism has been implement in QQ group, and promoted many people learning Rholang spontaneously. It is a good method, isn't it? 
Welcome to join our translation group. Let's work together to make RChain better.

**Comment by rjl493456442** [comment]
@JieL314 The translation quality is motivated by the budget of translation task itself. Sorry i don't know how can this group take effect.

**Comment by AbnerZheng** [comment]
@JieL314 I have taken participated in some documents translating to Chinese. As @rjl493456442 said, RChain has award the issue for translating.The method for translation guarantee is still being discussed.  But I think the budget for translation quality guarantee should be including in the same issue with translating, we usually assign about 10% of budget to the reviewer.
For https://github.com/rchain/bounties/issues/230 , I think it is a closed issue, and since all translating work has been moved into other issue and people like @ICA3DaR5 takes more interests in organizing translating issues, Chinese translation should follow the rule of community and processed as other languages. 
I am not clear about what you mean by motivating people to improve the quality of translating, if you can, please give a detail.

**Comment by JieL314** [comment]
@AbnerZheng The[issue230](https://github.com/rchain/bounties/issues/552) is aimed at promoting people to product a high quality works in a high efficiency way. In my opinion, the 10% of budget is set up for reviewer. So how can we judge the work? In this mechanism, I can push the translation work to a better one.
Compare to Jan, the works in this month is decrease. Maybe @ICA3DaR5 has done most of them. But my method may make all people more efficient.
My method: Supposed A is technical people, B is amateur, C is outsider.
the distribution may be 6, 3, 1 for A, B, C respective.  It will depend on the actually situation.

**Comment by zsluedem** [comment]
I believe this one is no longer available now. close it now~!
