### ISSUE TITLE
Write an article about the implementation of Rchain scalability.

### ISSUE THREAD

**Issue by tigermumu** [rchain/bounties#578]
Issue
"A brief introduction to the implementation of Rchain scalability."
Write an article about the implementation of Rchain scalability.

Task
1. Researching the technical documents and video of Rchain scalability.
2. Listing the features and think about how to make It easier to understand for public.
3. Writing article.
4. Review and upload to http://www.rchain.site/ and Medium (personal blog)

Co-worker
Sherryzard, JieL314

Suggested Budget
Write article: 100$
Translate into English: 60$
Total: 160$

Due time
2018/05/20

**Comment by philipandri002** [comment]
This is a great idea. I am very much interested

**Comment by Aligengen** [comment]
Nice work

**Comment by philipandri002** [comment]
So how do I contribute?

**Comment by tigermumu** [comment]
This task has to delay.

**Comment by lapin7** [comment]
@philipandri002 , @philipandri002 

## To contribute to RChain:
 
- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Bounty App https://rewards.rchain.coop/
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by TrenchFloat** [comment]
@tigermumu any progress on this issue? Could we get a new due date or an update on how things are going?

**Comment by TrenchFloat** [comment]
@tigermumu 
> I will translate this into English and published later

Is the May 20th date in the initial comment what you meant by "later"?
I'm happy to vote for this once the English translation is up.
