### ISSUE TITLE
Stack exchange engagement

### ISSUE THREAD

**Issue by Valentine-Mario** [rchain/bounties#584]
Stack exchange is a question and answer engagement site where questions and professional answers are given. It is also the biggest question and answer forum for software developers in the world. This issue hopes to publicize RChain through a series of questions and answer. 
The engagement can be found <a href="https://money.stackexchange.com/q/93948/70916">here</a>. Feel free to contribute and make the session more engaging.

**Comment by David405** [comment]
@Valentine-mario, nice concept you have here, I believe this is a greater part of taking RChain to strong active communities like stack exchange and others where a lot of persons can contribute and make RChain public.

RChain community in discord, telegram isn't indexed on popular search engines and this really cripples effort of convincing people to invest in RChain.

I strongly believe that every cryptosystem, programming language, platform is only as strong as its active community and how widespread it is among the general public and if we continue to bring RChain to more popular and active communities, it will go a long way to strengthen the cryptosystem.

**Comment by casanwugo** [comment]
I am a crptocurrency enthusiast, who is very much enthusiastic about RChain. I would like to contribute to the community

**Comment by casanwugo** [comment]
I am a crypto enthusiast. I would like to contribute positively to the community, and be a part of it.

**Comment by casanwugo** [comment]
I am a crypto enthusiast. I would like to contribute positively to the community, and be a part of it.

**Comment by Ojimadu** [comment]
@Valentine-Mario The page you linked to returns a "page not found" error.

**Comment by David405** [comment]
@Ojimadu the page was removed by stack exchange, maybe a more specific than general question needs to be asked.

**Comment by Valentine-Mario** [comment]
@Ojimadu stack exchange removed it due to their policy reasons. I would try to stick to their policy when creating a new question. Meanwhile, you can also ask questions on stack exchange and post the link here.

**Comment by Valentine-Mario** [comment]
Another question has been created on Stack exchange. Visit the link <a href ="https://cs.stackexchange.com/questions/90402/what-are-digital-currencies">here</a> to add to the answers.

**Comment by Preshcode** [comment]
Please visit the link on stack exchange and add ur contributions. <a href="https://stackoverflow.com/questions/49403233/answer/submit/html/">visit link</a>

**Comment by kaka56** [comment]
@Preshcode  the link you used returns error.

**Comment by David405** [comment]
@kak56 the question created by @Valentine-Mario got closed again and this is because it fails to meet stack exchange's policy of specificity. @Valentine-Mario please use <a href="http://www.catb.org/~esr/faqs/smart-questions.html">this</a> as a guide in creating a more S.M.A.R.T. question.

**Comment by Preshcode** [comment]
Please visit the <a href="http://www.nairaland.com/4452510/rchain community/">link<a/> and join in the discussion.

**Comment by BelovedAquila** [comment]
@casanwugo glad to know about your enthusiasm  towards the coop 
Please 
- [x] Join RChain Coop by signing up for membership
- [x] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [x] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [x] Join github/rchain/bounties in order to contribute
- [x] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [x] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [x] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform

@Valentine-Mario links still not going through
