### ISSUE TITLE
Penetrating the African market - Creating an active community in Africa

### ISSUE THREAD

**Issue by David405** [rchain/bounties#591]
**Benefit to RChain**
Africa has a large population with a lot of persons recently acknowledging the opportunities in the cryptomarket. I believe RChain will benefit a lot by having a strong active community of developers, marketers and other personnel from Africa. 

The African market holds great potentials for cryptocurrencies like RHOC for some good <a href="https://www.investopedia.com/news/africa-next-big-market-cryptocurrencies/">reasons</a>

**Objectives for RChain Africa**

- [x] Creating an active RChain community in Africa.

- [x] Hosting RChain events in Africa.

- [ ] Building on the RChain platform as a blockchain technology to solve active challenges african communites are faced with.

- [ ] Onboarding software developers from Africa.

- [x] Sharing tutorials, updates and news about RChain on several active african communities and platforms.

- [x] Engaging the african academic and university community with RChain technology.

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

_Estimated Budget of Task_: $**[TBD]**
_Estimated Timeline Required to Complete the Task_: **[Monthly Report]**
_How will we measure completion?_ **[Alignment with Objectives and coop goals]**

_See CONTRIBUTING.md for details on budget and reward process._

**Legal**
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by raven104** [comment]
Yes I agree with you, Africa holds great potentials for cryotocurrency, I also feel we need to identify countries in Africa were we ve members.

**Comment by namo927** [comment]
As much as i would like to agree you that the african market is huge, the african approach has to be targeted and focused. RHOC isn't necessarily a crytocurrency just yet, which will make it a bit difficult for people to understand.

in light of the above i would suggest we select a country like Nigeria which has more active African members organise meet ups, follow that up with what i would tag "Silent Marketing" having Rchain logo, banners and other marketing material at Specific events. Thereby building a curiocity bud in the minds of our target audience, before holding a major meet up were if possible some of the Seattle team can make it down for a one or 2day session which i know African will find appealing hearing the information from the source and in person. With this and continuous marketing the african eco space can be penetrate with desired result. 

in the short/medium term we can look at creating University hubs in major universities.

**Comment by Pionelle** [comment]
Bonjour Monsieurs.

In whatever direction the African blueprint approaches, please set aside for rapid development in other smaller countries with  as much potential as Nigeria.
The Benin republic, Togo, Ghana and plenty of smaller nations like mine have good programming and a viable market too. 
I would choose a large targeted approach, viz a viz, West Africa to maximize growth potential.
Secondly the idea as I have grown to understand is making the Cooperative be understood by potential members. To an extent developers and contributors.
Also, is to ensure that developers utilize the RChain programming language to make end products. If then efforts are made to convert code writers, maybe from intersection online and in the University as @namo927 pointed. This is the good thing too.
But enter Africa for the good of all.

**Comment by lapin7** [comment]
@David405 please make this issue as SMART as possible. I agree with the general thinking, but it has to result into manageable actions.

**Comment by David405** [comment]
@lapin7 the issue has to edited

**Comment by Valentine-Mario** [comment]
I also suggest using various blogs and forums targeted for Africa to make them aware of RHOC.

**Comment by Valentine-Mario** [comment]
Using blogs and forums would be very effective as Nigeria (where I live) has a very large online presence with over 90 million people who use the internet.

**Comment by jasoncruzzy** [comment]
How about advertising it on various social media platforms accompanied with our telegram link in the post as well, then occasionally the Admins organize seminars for our new invitees/members.

**Comment by Tonyprisca13** [comment]
@jasoncruzzy your idea of advertising on social media sound good we seem have more presence on social media and this will help spread RChain faster and wider.

**Comment by Viraculous** [comment]
I think the first step is need recognition ; what are the technological and economic need faced by African societies and government? and what product of RChain stand as a pragmatic solution to the problem or need.

Secondly, amplifying the community's ambiguity on the use of her product to a layman's understanding seeing that not much of the awareness of Blockchain technology has been enforced in African states. A short animated video could be useful to explain where the community is now, which of her product is available for use, how to use the community's product in solving basic or simple economic problems and also where RChain intends to reach in actualization of vision.

Thirdly, starting from the scratch: Making analysis on crypto friendly African countries and starting with countries with greater awareness and understanding of Blockchains. This will make the awareness spread faster than starting with countries with little or no participation in Blockchain. Population size is also a factor under marketing consideration.

Fourthly, getting Africans core developers on boarded in the community. Search for their Channels, blogs, socials and other minor and major African developers blogs, platforms inviting them to join our developers team.

@david I agree with you and as a matter of fact have been concerned about the coldness of the RChain Africa telegrams group but I still think that the goal like @lapin7 said should be made with smart objectives. Let's start by breaking the goals down into bits of actualizable roadmap. Let's start with the telegram group: How do we on board more members on our telegram group? 
First: let's get the list of developers platforms, media and channels in Africa inviting them to the community with link
Secondly : managing the telegram group by entertaining the question of on boarded members and promoting our services.

**Comment by Viraculous** [comment]
Please send them these links to get them on board. *Please become member of this group <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgroups.google.com%2Fforum%2F%23!managemembers%2Frchain%2Fjoin&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* to get access to documents Create an account on Github ​ and read​ *github/rchain/Members <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fblob%2Fmaster%2FCONTRIBUTING.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* in order to contribute. And send ​your github name ​ to *ops@rchain.coop <ops@rchain.coop>*. Then after a while log in to github and then accept the invite through this link https://github.com/rchain/Members/invitations To know more about RChain: - Official *RChain Website <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Frchain.coop%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* - Chat about RChain at *Discord <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fdiscord.gg%2FfvY8qhx&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *Telegram <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Ft.me%2Frchain_coop&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *Twitter <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Ftwitter.com%2Frchain_coop&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *Facebook <https://www.facebook.com/rchaincooperative/>*, *YouTube <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCSS3jCffMiz574_q64Ukj_w&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *Reddit <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.reddit.com%2Fr%2FRChain%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *BitcoinTalk <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fbitcointalk.org%2Findex.php%3Ftopic%3D2494040&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* , *Medium <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fmedium.com%2Frchain-cooperative&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*, QQ Group ID: 中国朋友欢迎加入RChain粉丝群，QQ群号: 530718666 - Read the *FAQ <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Freference%2Fblob%2Fmaster%2Ffaq.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* - RChain *Architecture <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Frchain-architecture.readthedocs.io%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* Doc - To compare *Blockchains <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Frchain-architecture.readthedocs.io%2Fen%2Flatest%2Fintroduction%2Fcomparison-of-blockchains.html&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* - Weekly *Debrief <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fwiki%2FWeekly-Debrief-Index&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* Index - Follow the *Roadmap <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Frchain.atlassian.net%2Fwiki%2Fspaces%2FCORE%2Fpages%2F105709609%2FRoadmap&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* - RHOC *Distribution and Circulation <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2Freference%2Fblob%2Fmaster%2Ffinance%2Frhoc.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* To contribute to RChain: - Join RChain Coop by *signing up for membership <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=http%3A%2F%2Fmember.rchain.coop%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* - Join *rchain@googlegroups.com <rchain@googlegroups.com>* *see <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgroups.google.com%2Fforum%2F%23!managemembers%2Frchain%2Fjoin&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* to get access to documents. - Join *github/rchain/Members <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fgithub.com%2Frchain%2FMembers%2Fblob%2Fmaster%2FCONTRIBUTING.md&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>* in order to contribute RHOC Token Details To see RHOC in *MEW <http://t.sidekickopen08.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2zhDwMW5v_SgK2zWN1RW1p1hXH56dLy3f6WHqqH02?t=https%3A%2F%2Fwww.myetherwallet.com%2F&si=5281391242641408&pi=db7406c3-8869-40b0-f1d6-aafbc6d46868>*/Metamask "Add Custom Token" with address: 0x168296bb09e24a88805cb9c33356536b980d3fc5 8 digits

**Comment by iamcoderisk** [comment]
@david you have made a very good suggestion. My interest is in the aspect of development as they are a lot of software engineers, devops and testers who would love to contribute positively to the development of Rholang. I personally would contribute to the language development and also make other suggestions where possible.

**Comment by pmoorman** [comment]
Hey guys,

I think we can still make this issue much more SMART. 

Some ideas:

- Maybe would should split some tasks into separate issues (and reference them clearly). For instance: there is a separate issue already to grow the Africa Telegram group.  We want to avoid double-counting it.

- Attendance to a conference should really be a separate issue, and should be decided on separately. Please spin it out into it's own issue.

- The last task of onboarding African developers is arguably the most important one. I think we'd love to have more Africans turn into Rholang developers, as @iamcoderisk suggests.  To make it more SMART, we could say _how many African developers_ we're looking to onboard, or something like that.

It seems to me that this is more of an "umbrella" for organising African efforts (which is a good idea, probably), but the actual task description doesn't really reflect that!

cc @lapin7

**Comment by David405** [comment]
@pmoorman, other SMART sub issues will be still be created as a subset of this but we want there to be a starting point. We want it to be a coordinated, concerted effort, an "umbrella" as you described it.

**Comment by pmoorman** [comment]
Hey @David405 I see in the bounty app that you suggest a $3500 budget for this issue this month, along with another $3000 for related issue #592. 

That's $6500 in total budget.

**Can you explain what warrants this amount of money being spent?** Right now Telegram is at 32 members for instance, which is hard to justify a $3000 spend (that's $100 per Telegram subscriber!)

cc @lapin7 @Valentine-Mario @Viraculous @dckc @Ojimadu

**Comment by David405** [comment]
@pmoorman I acknowledge the fact that our telegram channel has not grown so much but more efforts is being placed to grow the membership and the right kind of content to engage is also being deliberated upon since we do not want something that duplicates the official telegram group.

Concerning this issue, the budget of $3500 is highly defendable, you will notice an influx of RAMs from Africa recently and this is as an effect of the marketing work that is ongoing. The work being done is more than what is reflected here. Even though we havent met all our targets yet, significant work is being done as regards penetrating African market.

_ps: I have used paid ads on some social platforms targeting africans to generate publicity_

**Comment by dckc** [comment]
> The work being done is more than what is reflected here. 

That's a bug. Please fix it.

That is: whatever work is going into the budgets and rewards, please make sure it's reflected here.

**Comment by Valentine-Mario** [comment]
Of recent, the influx of Rchain members from Africa has been astronomical, thus I think serious work has been done on boarding Africa members and thus the awareness of Rchain in Nigeria and Africa at large. I think the budget is actually worth it.

**Comment by jasoncruzzy** [comment]
@Valentine i agree with you, there has been alot of response from Nigeria
and Africa at large.

**Comment by dckc** [comment]
@Valentine-Mario 
> Of recent, the influx of Rchain members from Africa has been astronomical, ...

Where did you get that information? Got a pointer? Or would you care to elaborate a bit? Approximately how many members constitutes "astronomical"? Hundreds? Thousands?

**Comment by David405** [comment]
@dckc I am glad to have your input on this issue but I would have been more excited to have you contribute positively towards the development of worthwhile projects rather than judge budgets and votes.

**Comment by dckc** [comment]
I would have been more excited if I didn't have to deal with unjustified budgets, too.

**Comment by nonnykul** [comment]
Nigeria tertiary institution will be a great means to create active RChain members,most discipline in institution have platforms to disseminate information.I will like to use my disicipline/institution as a case study

**Comment by Ojimadu** [comment]
Like dckc said
>That is: whatever work is going into the budgets and rewards, please make sure it's reflected here.
, imo putting work going on there would better to effectively gauge the value and contribution to the coop. Along with sufficient information like KPI etc.

**Comment by pmoorman** [comment]
hey guys, I've been thinking lately about all the Africa-focused issues that pop up, and the budgets that get allocated to it.

I've been looking through the big marketing plan, as well as any relevant public statements that I could think of, and I don't see Africa mentioned as a priority anywhere. It's not really mentioned anywhere as a focus area (whereas China is, for instance).

We're working within the coop to align the work done under the bounty system with the goals of the RChain coop, and **my position is that these regionally-focused marketing issues shouldn't be funded unless they can demonstrate a clear and obvious ROI.**

I'm posting here since this is sort of the "umbrella issue", but it also pertains to:
 #701, #601, #592, #591, #662, #699, #696, #681 and possibly others that I've missed.

---

_P.S. Of course, that isn't necessarily the end of the story. If anyone can make a clear case that these issues (and associated budgets) do indeed serve a much-needed role, then please make that case in as public a way as possible. For instance: bring the case to the weekly meetings._

**Comment by pmoorman** [comment]
Hey, I got an email notification about the comment from @jasoncruzzy that @David405 then later removed. 

I'm happy to explain further (although I'll be out for the weekend), but the main reasoning for my comment is to bring marketing efforts in the bounty system aligned with the strategic marketing objectives of the RChain coop. 

Based on the marketing strategy documents, I find the budgets allocated to these budgets hard to justify. If it's not a strategic focus, some more explaining/convincing is needed as to _why_ these issues will produce a favorable ROI. 

cc @kitblake @AyAyRon-P

**Comment by David405** [comment]
@pmoorman I know this is coming late but to clarify your thoughts as to why the comment from jasoncruzzy was deleted, I was on mobile that day and I wanted to edit his comment but mistakenly touched the delete function and github doesn't reverse such ( _this has happened severally with my own comments while on mobile but deleting your own comment doesn't give a notification_)

**Comment by lapin7** [comment]
@allancto What do you mean with this?

> Another problem I see is that growth in budgets and membership from particular geographical areas seems to be happening more rapidly than we have the funds and infrastructure to deal with. How do we manage growth in a way that doesn't concentrate power within particular groups?

**Comment by tcezi** [comment]
@allancto that was a malicious statement. Please what do u mean?

**Comment by kitblake** [comment]
@tcezi I doubt @allancto meant that maliciously. The larger problem, as noted by @pmoorman above in https://github.com/rchain/bounties/issues/591#issuecomment-389939265, is the RChain marketing plan doesn't include regional promotion on specific continents. Until we hear differently we should keep our efforts consolidated on a global level. 
@AyAyRon-P

**Comment by AyAyRon-P** [comment]
@David405 

Please update your initial post following the NEW ISSUE template:
https://github.com/rchain/bounties/issues/new

Are there any updates to this project? Can we close this out and archive the issue?

**Comment by David405** [comment]
@AyAyRon-P there have been progress on this issue, see #796

**Comment by pmoorman** [comment]
Yeah, I would also prefer if we could allocate budget based on issues like #796 for instance, rather than ongoing / open-ended tasks like these.

Of course, there is a place for articulating the overarching strategy of a series of tasks, and maybe this issue could serve that purpose. In that case, it would be good to reflect that in the issue.

For now, I'll close this issue out (to keep things trimmed), and let's instead focus on actions like #796!!
