### ISSUE TITLE
Reviving RChain Africa Telegram group and Growing its membership to 100

### ISSUE THREAD

**Issue by David405** [rchain/bounties#592]
I noticed that the RChain Africa group has not been active for some months now. I would love the group to become active again. I personally volunteer myself as an one the Admins of the group

**Comment by David405** [comment]
Right now, the RChain Africa Telegram group has 17 members but if we become active and onboard more Africans, the group can grow to a 100 members before month end and if we stretch ourselves some more, who knows, we may hit 500

**Comment by jasoncruzzy** [comment]
@David405 nice idea, we really need more members in the group,, I'm in on this one...100 members for Rchain Africa telegram

**Comment by casanwugo** [comment]
@David405 Very valid point. I am quite sure that the RChain community could use some involvement from a few tech gurus with great minds from Africa... RChain Africa Telegram should be revived.

**Comment by Pionelle** [comment]
The Telegram community could be amalgamated/improved. 

The activity on the t.me/RChainAfrica is decent and very proportionate to members.
You should check that out too.
That was the landing site for me.

**Comment by Preshcode** [comment]
I support this idea completely, I live in Nigeria and I can say that over here we have so many people here who do not know about Rchain, I believe growing the membership of the Rchain active community in Africa will not only help publicize the platform but will also bring in intellects all across Africa so we can together to achieve our aim.

**Comment by Preshcode** [comment]
I support this idea completely, I live in Nigeria and I can say that over here we have so many people here who do not know about Rchain, I believe growing the membership of the Rchain active community in Africa will not only help publicize the platform but will also bring in intellects all across Africa so we can work together to achieve our much desired aim.

**Comment by namo927** [comment]
@David405 well said i am open to help out with this

**Comment by David405** [comment]
#591

**Comment by Valentine-Mario** [comment]
@David405 how do you intend to grow the Telegram community?

**Comment by makys** [comment]
@David405 What is the incentive for RChain Africa Telegram channel? The idea sounds good to me but I may be needing some context here: When was the channel originally started? Who was/is the admin on the channel? Why did the channel lose momentum? Do we have sub channels for other regions?

It is a good idea that we tailor our reach, I want to be sure that what we intend to provide does not exist in the main telegram channel. i would like to support this idea having a view of the big picture.

@Ojimadu please chime in here if you will.

**Comment by ResonanceXX** [comment]
Marketing is a very good proposition Mario. But essentially, RChain has got to attract what it needs. And more importantly 'people that can build a utility' especially around the Mercury platform launch. Your idea is a good one. Your intentions are positive, same with Davide's. 

We can set about this with a proper frame work and a laid out action plan. Cheers. 

Sent from Yahoo Mail on Android 
 
  On Tue, 10 Apr 2018 at 17:28, makys<notifications@github.com> wrote:   
@David405 What is the incentive for RChain Africa Telegram channel? The idea sounds good to me but I may be needing some context here: When was the channel originally started? Who was/is the admin on the channel? Why did the channel lose momentum? Do we have sub channels for other regions?

It is a good idea that we tailor our reach, I want to be sure that what we intend to provide does not exist in the main telegram channel. i would like to support this idea having a view of the big picture.

@Ojimadu please chime in here if you will.

**Comment by David405** [comment]
@makys the RChain Africa telegram group was created in January this year, the group's admin are @Mervyn @Keaycee @itlake and @lapin7. I guess the channel lost momentum probably due to lack of engagement.

Some other regions, for example, China have their own active sub channels, this is not intended to cause a division but to reach out to a wider audience in that region.

The point of having an RChain Africa telegram group is an effort towards penetrating the African market and building a strong, popular and widely accepted RChain community in Africa. I hope you are able to get the big picture now. RChain, Rholang and RHOCs as I have always emphasized is only as strong as its community of users and general acceptability as with any other currency, programming language and I believe at the end of this marketing campaign, Africa would have widely accepted RHOC as we accept Bitcoin or Ethereum.

**Comment by BelovedAquila** [comment]
I have always known Africa has good prospects in the RChain community, and I don't see it as a division, it's more like creating a communal mutual platform for effective results. And this time it's made broader than just a seclusion to a country, RChain Africa telegram group i believe is meant to cover a continent not just a country in Africa, so it's spherical  coverage is a good one to spread the RChain.yet I see a point just as @makys pointed out, the incentive needs be well defined above just populating the group.
@Pionelle @namo927 @jasoncruzzy  and @casanwugo are we in the RChain telegram group already?

**Comment by Keaycee** [comment]
@David405 I got your message, I look forward working with you to revive the RChain Telegram channel. I already assigned you as an admin on the telegram group. I hope we could collaborate better to revive the group.

**Comment by Preshcode** [comment]
Good job @valentine-Mario, I believe that is a wonderful way to advertise the telegram group.

**Comment by ResonanceXX** [comment]
Of course encourage potential members by 1v1 interactions. This is highly recommended to weed off non-compliant actors from the Coop. When compliance is ensured,  I believe that aggregated efforts would consequently yield better results. By also relaying your experience to another individual, the authenticity of the cooperative is super asserted. So, Mario-Valentine could you continue to ship in plenty of cooperators for RChain. Good luck while you're at that. Cheers. 

Sent from Yahoo Mail on Android 
 
  On Sat, 14 Apr 2018 at 16:33, Precious<notifications@github.com> wrote:   
Good job @Valentine-Mario, I believe that is a wonderful way to advertise the telegram group.

**Comment by Pionelle** [comment]
@ResonanceXX Please do well to educate us on who Non-compliant actors are? How do we identify and prevent such from happening. Is there a solution to this? 

You seem to be suggesting that the choice of the targeted marketing campaing predisposes RChain to **non-compliant** actors?

**Comment by David405** [comment]
@Pionelle, I believe what @resonanceXX means by noncompliant actors are persons who are not really interested but joined due to one marketing strategy or the other.

What we want are active and enthusiastic people joining the Co-op, that is why we have adopted a targeted marketing strategy which has proven to be working so far, we are indeed making progress! Cheers everyone!

**Comment by jasoncruzzy** [comment]
@David405  you doing a great Job

**Comment by azazime** [comment]
Firstly for a group to be revived it needs the members to be active daily, share ideas, set goals and achieve such goals as a unit..

Links to the group with a simple and attractive articles on Rchain should be littled online so as to get the attention of people who would join the group because they want to know more.

Then the Admins should also work on sustainability

**Comment by Valentine-Mario** [comment]
I think active work has been done on the Rchain Africa group. It has also found a group of Blockchain startup owners who are willing to partner with Blockchain. Maybe @David405 can throw more light at this. So I honestly feel the budget is justified

**Comment by nonnykul** [comment]
@David405,using a discipline in Nigeria tertiary institution as a case study,will create active members in RChain community.Tertiary institutions make use of platform to voice Info's,penetrating the platform to get people acquitted with RChain,will be a good marketing strategy

**Comment by lapin7** [comment]
@all If you see a new face in RChain/bounties then please paste this "ToDoInfo" addressed to the new face.

@nonnykul 
## To contribute to RChain, please do (if you haven’t done so already):
 
- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Watch presentation: https://docs.google.com/presentation/d/1B2Vu8o3ACwruY6HY1ayXRQ4qkNKsMy4hdbOdxrCHI2o/edit#slide=id.g3827e46a00_0_68
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform 
- [ ] Collaborate in all kind of issues https://github.com/rchain/bounties/issues
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Fool around with our Bounty App https://rewards.rchain.coop/
- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by nonnykul** [comment]
Creating a WhatsApp group,inviting engineering and computer science discipline,making them acquainted with RChain
