### ISSUE TITLE
Pithia On Quora: Neccesitated by Demand

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#603]
The Blockchain space has become almost saturated with the same cycle of Projects raising funding for a new technology/solution. 
Then there are other users (many) actually, who crave for the more futuristic, better and more sophisticated implementation of the Blockchain technology.

I became strongly drawn to this question, due to its duplicity with the thoughts of @llerner. 
I believe Lawrence, as a major player in the space (Especially with RChain's Pythia)  has got the answer to this questions. 
Since Pythia serves a major role of discovering the next generation of Blockchain startups - this user would be gratified with **the answer** disclosing our venture company.
But yet still, I have provided the answer, while giving adequate directions to both RChain's website and Pythia's also.

Thanks for your interest in telling the story of RChain in another language.

**Comment by ResonanceXX** [comment]
![screenshot-2018-4-15 home - quora](https://user-images.githubusercontent.com/34219332/38773589-20ff8722-4048-11e8-9fde-276ad61dec30.png)

**Comment by ResonanceXX** [comment]
http://qr.ae/TU1Jxh

In this answer, the user is made to understand the importance of Blockchain expanding to a better problem solver for the global community of users.
Appropriately, I create the genuine impression, that in few years time and with the presence of Pythia inc. in the ecosystem. Many innovative end use modifying/improving companies would be both discovered and supported to maturity.

**Comment by llerner** [comment]
Thanks! The spelling is Pithia, btw.

**Comment by ResonanceXX** [comment]
@llerner Pythia comes originally to me. Very sorry for always making this error again. 👍

**Comment by Pionelle** [comment]
The spelling should be corrected to www.pithia.com for the website.
 I visited the quora page and wnated to join the website to Pithia. Took me to a wood manufacturer in Brazil.
Please could you change that?

**Comment by ResonanceXX** [comment]
@llerner Truly was an original error. I understand the plight.
@pionelle Okay. I see the error now.
I have made the adequate corrections to both Pages. Cheers.

**Comment by Pionelle** [comment]
The information is better now

**Comment by ResonanceXX** [comment]
Exclusive link to a newly published article - https://medium.com/@kenechukwuoliaku/pithia-a-short-talk-with-lawrence-lerner-87abd5d7f64e
This one's on the house. 100% read per view. Cheers.

**Comment by ResonanceXX** [comment]
https://www.quora.com/Where-can-I-find-more-blockchain-business-projects?__filter__&__nsrc__=2&__snid3__=2303662621

I feel this question comes with an inference.
But this would be more specific inquiry into if, Pithia inc, has a directory of start-ups currently engaged and at what levels they are existing on.
Also if there isnt any form of this, deliberate on the importance/or lack of such a directory/page or newsletter.

**Comment by ResonanceXX** [comment]
https://www.quora.com/Where-can-I-find-more-blockchain-business-projects/answer/ResonanceXX

**Comment by ResonanceXX** [comment]
http://qr.ae/TU1m9W

**Comment by BelovedAquila** [comment]
@ResonanceXX you write good articles, but please endeavor to link membership procedures to this
- [x] Join RChain Coop by signing up for membership
- [x] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [x] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [x] Join github/rchain/bounties in order to contribute
- [x] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [x] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [x] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform

**Comment by pmoorman** [comment]
hey guys, I'm going through the list of "marketing" issues, to clean it up a little bit. 

**If this issue is completed (as the status implies), then please close the issue.**

**Comment by Pionelle** [comment]
I think this is done for now @resonanceXX has to doaway with it. Merci
 
 
  On Mon, 30 Apr 2018 at 16:59, pmoorman<notifications@github.com> wrote:   
hey guys, I'm going through the list of "marketing" issues, to clean it up a little bit.

If this issue is completed (as the status implies), then please close the issue.

**Comment by ResonanceXX** [comment]
@pmoorman Okay. I have not done much concerning this. Closing it for now.
