### ISSUE TITLE
R-Chain Review Video - Crypto Bros YouTube Channel

### ISSUE THREAD

**Issue by CryptoBr0s** [rchain/bounties#617]
### For all issues
[Keep italic labels, replace brackets with answer]

*Crypto Bros YouTube Channel featured a video on R-Chain reviewing the project, covering the tech (Well tried to anyway 😃 ) and sharing personal insights on the token and project* 

The link to the video can be found here: https://youtu.be/_QvmCQm2OD0

*Estimated Budget of Task:* **$[200]**  \
*Estimated Timeline Required to Complete the Task:* **[3-day]**  \
*Measure of Completion:* **[100%]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by BelovedAquila** [comment]
@CryptoBr0s please become a bona-fide member of the community ☺
- [x] Join RChain Coop by signing up for membership
- [x] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [x] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [x] Join github/rchain/bounties in order to contribute
- [x] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [x] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [x] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform

**Comment by lapin7** [comment]
Thx for your care @BelovedAquila, **BUT** 
@CryptoBr0s is already a "bona-fide" member

**Comment by CryptoBr0s** [comment]
Hahah! Happy Friday Guys! I appreciate the love here @BelovedAquila

I am still getting acclimated with the rchain.coop but I am figuring it out!

**Comment by pmoorman** [comment]
hey guys, I'm going through the list of "marketing" issues, to clean it up a little bit. 

**If this issue is completed (as the status implies), then please close the issue.**
