### ISSUE TITLE
Translate Community Update18-20 to Chinese

### ISSUE THREAD

**Issue by v56700** [rchain/bounties#624]
Community Update 18
you can see it here http://www.rchain.site/?p=469
Suggested Budget: 25$ 
Measure of Completion: completed already

Community Update 19
you can see it here http://www.rchain.site/?p=502
Suggested Budget: 25$ 
Measure of Completion: completed already

Community Update 20
you can see it here http://www.rchain.site/?p=525
Suggested Budget: 25$ 
Measure of Completion: completed already

Translate The best open source rookies of 2018  to Chinese
https://www.infoworld.com/article/3263736/open-source-tools/the-best-open-source-rookies-of-2018.html
you can see it here http://www.rchain.site/?p=386
Suggested Budget: 30$ 
Measure of Completion: completed already

Translate The RChain Cooperative & Pyrofex Corporation ink Strategic Partnership  to Chinese
https://medium.com/rchain-cooperative/the-rchain-cooperative-pyrofex-corporation-ink-strategic-partnership-67a72004150a
you can see it here http://www.rchain.site/?p=236
Suggested Budget: 50$ 

Blockchain comparison is my original and compared to 28 blockchains to help the Chinese community understand Rchain, 4000 words and 1900 readings 
you can see it here http://www.rchain.site/?p=412
Suggested Budget: 200$ 

Budget statistics:25+25+25+30+50+200=355

**Comment by BelovedAquila** [comment]
@v56700 good you intend contributing to the community, please become a bona-fide member for an effective cooperative contribution 😄

- [x] Join RChain Coop by signing up for membership
- [x] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [x] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [x] Join github/rchain/bounties in order to contribute
- [x] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [x] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [x] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform

**Comment by ICA3DaR5** [comment]
Since this has been voted for April and probably paid, I am closing this.
