### ISSUE TITLE
Medium Post: RChain: With Concurrency and Diversity.

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#629]
### For all issues
[Keep italic labels, replace brackets with answer]

*This is a fine attempt to express our open minded, faithful and non compromising invitation to willing potential members irrespective of the creed, location and political leanings. From my own personal experience enjoying the rare privilege of meeting with some of Blockchain's greatest assets. And also interacting with very pragmatic persons, I could mention a few. I believe that there are others like us, who although filled with the value but are unsure of the ambience in the cooperative. READING THIS WILL LIKELY DISPEL ANY FEARS, AND ALSO CELEBRATE OUR INHERENT DIVERSITY. ITS ALSO SOME GOOD PR AND ENRICHES THE BRAND.*

*Estimated Budget of Task:* **$[400 - 805]**  \
*Estimated Timeline Required to Complete the Task:* **[3 days/3 nights (with of plenty coffee breaks]**  \
*Measure of Completion:* **[Completed]**

[See CONTRIBUTING.md for details on budget and reward process.]
This is the article link, please continue to read articles, the stats have been overwhelming. And its encouraged. Hopefully someone reads this and abandons any fear/restraint and also shares in the happiness of our diversity.

https://medium.com/@kenechukwuoliaku/rchain-with-concurrency-and-diversity-114926d0e046
--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by ResonanceXX** [comment]
Its a 4 minute read thats by the way.

**Comment by casanwugo** [comment]
@ResonanceXX. This is one interesting piece! But I can assure you, it's definitely more than a 4 minute read if one must study on it. Kudos!

**Comment by ResonanceXX** [comment]
@casanwugo Thank you very much. Cheers.

**Comment by ResonanceXX** [comment]
https://medium.com/@kenechukwuoliaku/rchain-with-concurrency-and-diversity-114926d0e046

**Comment by BelovedAquila** [comment]
@ResonanceXX yes that came to mine but there are at least 3 vital links you could use, like the first 3 links. 4, 5,6 is just like placing their incentives to just bounty!, yes that's quite a boost to encouraging them participate, but for effective participation they need the first 3.thats my take though

**Comment by ResonanceXX** [comment]
@BelovedAquila Accessing the documents before accepting to pay the $20 mandatory sign on fee. Do you thing its a better alternative?

**Comment by ResonanceXX** [comment]
So thats after conditions 4, 5, 6 are met. So maybe, its fine to hold back on that. Cheers.

**Comment by lapin7** [comment]
- [ ] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain

It is merely there to be able to manage access to RChain Docs. By being member of rchain@googlegroups.com, we can see who's fooling around with our Google docs. It's not there to make people pay for membership.

So I suggest that the invite is on that paper.

**Comment by Pionelle** [comment]
I agree. The fact that people show interest is not an assurance that they pay for membership.
@lapin7   
@ResonanceXX you should make all possible means to put the required links.

For one the information is neccesary to teach before they are fully members, so that is the idea every other member has besides you.

**Comment by casanwugo** [comment]
You are very welcome @ResonanceXX

**Comment by lapin7** [comment]
@casanwugo please accept this invite 

- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform 
- [ ] Collaborate in all kind of issues https://github.com/rchain/bounties/issues
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Fool around with our Bounty App https://rewards.rchain.coop/
- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by ResonanceXX** [comment]
All changes shall be implemented. Cheers.

**Comment by casanwugo** [comment]
@lapin7, Thank you. I'm on it.

**Comment by azazime** [comment]
@lapin7 I feel a lot more work should be done in making this platform more understandable to an ordinary man because the more they understand it the more they believe and become interested

**Comment by azazime** [comment]
The admins haven't really done enough on this aspect hence some improvement should be made....

**Comment by ResonanceXX** [comment]
@casanwugo good things take time.

**Comment by ResonanceXX** [comment]
@azazime the github UI/UX is for github to make improvements. RChain's processes may seem cumbersome, but the clarity comes with a bit of time. You would  never do the same thing twice. Cheers.
@lapin7 does a good job making the already clear, clearer. Haha.

**Comment by azazime** [comment]
OK then @ResonanceXX

**Comment by ResonanceXX** [comment]
![screenshot-2018-5-12 stats for your stories may 4 may 11 - inbox - yahoo mail](https://user-images.githubusercontent.com/34219332/39951612-8098f268-5583-11e8-9eb1-06a7fe7424e9.png)
Hello cooperative. The numbers so far, on the articles published.

**Comment by ResonanceXX** [comment]
![screenshot-2018-5-17 your stories stats medium](https://user-images.githubusercontent.com/34219332/40158154-cf3f8c72-599a-11e8-85f8-de327d43eb1e.png)
