### ISSUE TITLE
Bug: Failure Notice For An Email

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#664]
### For all issues
[Keep italic labels, replace brackets with answer]

*This email ops@rchain.nl returns a MAILERDAEMON failure notice when mails were sent to it:*

**Comment by ResonanceXX** [comment]
Maybe some other persons have sent mails to the address without this hitch. Maybe it is a general problem. But either way Operations could be losing out on plenty of correspondence with Cooperative members if this continues.
Worth to check out the status of both the email address (text and account wise).
Especially since the **.nl** is a novelty.

**Comment by ResonanceXX** [comment]
@lapin7 could you do anything about this.

**Comment by dckc** [comment]
The address given in CONTRIBUTING.md is ops@rchain.coop.

Where did you find ops@rchain.nl?

**Comment by ResonanceXX** [comment]
@Keaycee 
There were no messages received. Only the error message.

@dckc  This is where it was, indulge freely:
![screenshot-2018-5-6 declaration](https://user-images.githubusercontent.com/34219332/39700583-9b837468-51f5-11e8-81c5-0b5e249ef7c3.png)

**Comment by Keaycee** [comment]
Well @ResonanceXX  i don't think RChain has any such address. The official know address is ops@rchain.coop. And if you do receive any message as such, be careful not to send any personal data as that email might not be linked with RChain.

**Comment by ResonanceXX** [comment]
https://docs.google.com/forms/d/1LpXu_Nl8LajffKbSRnqMi_GTbZ6HiqlnZ3eWQ4cm4no/viewform?edit_requested=true#responses


Follow this link @dckc

**Comment by ResonanceXX** [comment]
![screenshot-2018-5-7 declaration](https://user-images.githubusercontent.com/34219332/39727769-fac84c0e-524b-11e8-818e-b2355e9abf2f.png)

**Comment by lapin7** [comment]
@ResonanceXX You see how useful it is to refer to the exact place.
I've repaired it now in just two seconds, instead of thinking about it.

**Comment by ResonanceXX** [comment]
No. No. I wasnt looking to play around. I always had this screenshot, but did not occur to me - including it. I thought that the - Declarations on image 1 was a pointer.

**Comment by kitblake** [comment]
This issue has a $500 budget. For reporting a typo!
The budget is not listed in the issue description, as it should be, following the template. 
And HJ did the work.  
Please drop the budget to an hour or two: Valentine-Mario:, ResonanceXX:, Pionelle:

**Comment by kitblake** [comment]
@Valentine-Mario @Pionelle @ResonanceXX

**Comment by ResonanceXX** [comment]
Discovering the bug. 


@kitblake You have hastily concluded without any bit of effort, view the error mails I received after sending couple of emails to the address. Just to be sure.

I didnt see the typo. I worked out an incorrect email address. @lapin7 changed that.
Denigrating the quality of the work? Are we?


 
I think that plenty of people visited the page. 
@resonanceXX saw the bug.

**Comment by Pionelle** [comment]
I will be back down on this vote for him
This are my first times on here. Maybe he overstated the importance f his finding

Sent from Yahoo Mail on Android 
 
  On Wed, 9 May 2018 at 8:23, Chris Ken<notifications@github.com> wrote:   
As per governance model, the other members are at liberty to be influenced by the above.

But arriving at such conclusions do not placate members who (eagle eyed) will look and find minute discrepancies in otherwise perfect content.
It is becoming a pattern. And no one is infallible. Too.
Just to add that. Cheers!

**Comment by lapin7** [comment]
We have to be careful about claiming RHOC for small tasks. The Board of RChain is getting **extremely irritated** by the way RAM's are rewarded !!!!!
This may result in closing down the whole program !!!!

**Comment by kitblake** [comment]
Chris, it's really important that we follow the procedures. When you make a new issue there's a template and it's supposed to filled in with a Budget (and Timeline and Measure of Completion).

Deleting the budget in the issue, and then adding a budget in the Budget/Rewards system is NOT how it works. 

If an issue isn't properly filled in, with a budget, it shouldn't have a budget or a reward. 

Your budget was $500. If we use $40 an hour as the rate, that means you expected to spend 12.5 hours on the issue (fixing an email address). That's way out of line. I've put in a negative budget to knock the reward down to two hours. 

@Pionelle, and everybody, you have to realize that our bounty system is considered an experiment. If it fails due to dubious behavior we're all going to lose.

**Comment by ResonanceXX** [comment]
@dckc @kitblake @lapin7 Okay. Thank you very much. I understand. I do not wish to contest your opinions and/or selective bias on this case. The reward should be undone. Whatever the importance of my findings were, I renege on being rewarded for that.
Importantly, I would want to ascribe little blame on my non-receipt of March rewards. It was in seeking correspondence with ops/@lapin7 that I was chanced upon this. 
However, I am grateful for the reprimand, but eager to have my **very worrying situation** resolved. I also do not wish to claim a bounty on this anymore.
Whoever is responsible must understand that genuine hard work, not duly appreciated, breeds discontent. Cheers.
