### ISSUE TITLE
Getting tertiary institutions in Africa involved in RChain

### ISSUE THREAD

**Issue by nonnykul** [rchain/bounties#681]
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

Among students in African universities, there would be many students interested in RChain and able to apply Rholang and RChain technologies in Africa, a medium is being put in place to get developers from Africa involved in Rholang development.
,

_Estimated Budget of Task:_ **$[800]**  \
Team: 
Team lead: @nonnykul (45%)
Team members: @David405 (30%),Valentine-mario(25%)
Guides: @allancto @TrenchFloat 

_Estimated Timeline Required to Complete the Task:_ **[8weeks]**  \
_Measure of Completion:_ 
**[20 students to get involved with Rholang ]**
**[Information for Cooperative members about context, progress and vision among 20 students]**

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities law

**Comment by nonnykul** [comment]
African students especially those of Computer science and Engineering departments have shown to be more receptive to newer technology than their peers. 

Since, a lot of these students are frequent on WhatsApp, I intend to go about this using WhatsApp ads and groups.

**Comment by Valentine-Mario** [comment]
I think with the high population of software enthusiast in tertiary institutes, we should also focus on how we can on board more developers from this large pool of enthusiast.

**Comment by nonnykul** [comment]
Creating a WhatsApp group,due to the high participant of student in Africa using WhatsApp,getting them acquainted to RChain activities

**Comment by Valentine-Mario** [comment]
Due to the structure of WhatsApp, I think the application is highly ineffective for this task. I suggest a platform that is more publicly accessible and allows collaboration should be used. So that the progress curve can be measured.

**Comment by nonnykul** [comment]
@valatine-mario,measuring of progress,a google document can be used.

**Comment by Valentine-Mario** [comment]
What about public accessibility? And the limit to the number of users per group?

**Comment by philipandri002** [comment]
This is a great idea but i think whatapp has very limited number of people it group can carry so I will suggest using a telegram

And there is already an RChain Africa telegram group..

I suggest @nonnykul you reach out to @David45 for clarity.

However the concept and idea is great

**Comment by nonnykul** [comment]
More students in Africa tertiary institution make use of WhatsApp,I believe it would be a better medium for students to become RChain members.

**Comment by nonnykul** [comment]
@jassoncruzzy,a gud idea yu av established, noted.will work on the the telegram group

**Comment by jasoncruzzy** [comment]
Yes the telegram group will be for different tertiary institutions, each
institution should have its own. This way we will on board developers much
faster

**Comment by Murphy6** [comment]
That is a very good idea... But due to the fact a lot of students can not be added through watsapp channel who can comeup with telegram that accepts over thousand members. A lot of African youths would be waiting for an opportunity this big but we basically need to promote this and send information across.

**Comment by nonnykul** [comment]
@murphy6.already on the telegram group,getting to know people from different varsities in Africa,introducing them to RChain

**Comment by Keaycee** [comment]
@jasoncruzzy There won't be need for having different group for various institution, because it's going to be difficult to manage all at the same time. Secondly, how are you selling RChain to other people? When onboarding, you must understand that it's not all about the rewards thereof, but rather the bigger prospect that is yet to unveil.

**Comment by Keaycee** [comment]
@Murphy6  please accept this invite 

- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform 
- [ ] Collaborate in all kind of issues https://github.com/rchain/bounties/issues
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Fool around with our Bounty App https://rewards.rchain.coop/
- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by Tonyprisca13** [comment]
i think we should still use telegram

**Comment by jasoncruzzy** [comment]
@keaycee what i meant is the telegram group created for each higher
institution will bring them closer to themselves and share more ideas, just
like we have broken down the telegram group into sub units like telegram
Africa, telegram Nigeria. The aim is to bring RChain closer to everyone and
it will new members understand the visions of RChain better because with
every institution having their own telegram they meet themselves and share
ideas before coming with real Issues.

On May 14, 2018 21:02, "Tonyprisca13" <notifications@github.com> wrote:

i think we should still use telegram

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rchain/bounties/issues/681#issuecomment-388943872>, or mute
the thread

**Comment by Keaycee** [comment]
@jasoncruzzy it would be lot better to have them in one group, rather than having a multiple group. I already created a group, so we can groom the newbies about RChain and other morals they need to know before engaging. What ever idea they have can also be shared in the group.

**Comment by Pionelle** [comment]
Telegram be the better option. 

Sent from Yahoo Mail on Android

**Comment by azazime** [comment]
A sponsored AD should be the fastest, easier and more accurate medium to achieve this as the AD would be targeted at tertiary institutions hubs

**Comment by nonnykul** [comment]
Great ideas being put together by a great team,@azazime,@pionelle,@keaycee@jasoncruzzy,@murphy6@valentine-mario@philipandro002@Tonyprisca13
This is really a great issue ,that involves working together,and will help in the growth of RChain

**Comment by Murphy6** [comment]
@keaycee .. Still on the promotion, Nice contribution social media platforms is one of the highest promoting platforms.. We all should kindly follow the rchain Instagram account https://www.instagram.com/rchainafrica

**Comment by Keaycee** [comment]
@Murphy6  https://t.me/Rchain_Africa

**Comment by allancto** [comment]
@nonnykul can you explain the term "tertiary institutions"? Is this the same as "University" in your comment above? Are you speaking of particular institutions? Thanks!  -Allan

**Comment by nonnykul** [comment]
@allancto Yes I mean Universities or generally institutions of higher learning. This work is geared towards adding RChain to various research work.

**Comment by allancto** [comment]
@nonnykul  thanks! I was wondering, perhaps a longer version (long comment or short gdocs) might give everyone a bit more context on what the names of the institutions are, how many, where they are located, and so on. Also perhaps a little more context will be helpful in the measure of completiion, what might it mean for students to get involved with Rholang? In the first 2 weeks of 8 proposed, what have been your student experiences with Rholang up until now?

**Comment by allancto** [comment]
@all it looks to me like this is a very promising proposal, i would support it and suggest that if it seems to be working well we watch the results over the the length of the proposal and let the results guide our future decisions. @nonnykul the more visibility and analysis you provide as to the purpose, results and progress the easier it will be for voters to understand and make decisions about appropriate rewards here and for future proposals.

**Comment by nonnykul** [comment]
@allancto David and I have been talking a lot lately concerning reaching out to the university community in various parts of Africa. We reached a conclusion that the best way for now is to make as many students and researchers as possible present for the First RChain africa meetup that is coming up on the 9th of June in Nigeria. This is part of the first phase of this work.

The idea behind this is to get researchers and students actively involved in the development of the RChain project. For the first phase of the project, we are only reaching out to universities and research institutes in Nigeria such as:

- **Nnamdi Azikiwe University, Awka**

- **University of Nigeria Nsukka, Enugu**

- **University of Ibadan, Ibadan**

- **Federal University of Technology, Akure**

- **University of Lagos, Lagos**

- **University of Ife, Ile-Ife**

- **Covenant University, Otta**

I have highlighted these Nigerian schools because they are at the fore front of higher education in the country (_This work is not limited to Nigerian Universities alone but we are beginning with them because we can easily get across to these schools_).

Across these schools, Science fairs, Academic workshops, Symposiums and other intellectual events are organized regular to discuss and brainstorm intellectual ideas and it will be a good idea for RChain to be presented in such events. 

This issue is a fragment of the whole idea and it is completed when at least 20 students get involved with RChain by studying RChain and rholang models, downloading the sdk or using the online editor rchain.cloud.

I am currently undergoing a course in computer engineering at Nnamdi Azikiwe University and so the interactions I have had with other students have been engaging. Although, they have limited knowledge of blockchains and what it can do, they seem to be a lot interested in becoming part of the technology. I have talked about the prospects of RChain and how it can solve a lot of problems faced by the african community. 

_PS: I strongly believe in this project and the prospect of getting African colleges involved in RChain_

**Comment by allancto** [comment]
@nonnykul @David405 your comment just above is very communicative of what you're doing. I'd vote to expand the budget by an additional $600 (or more?) could be used to provide an expanded version of this comment. In an expanded version I'd hope to see information of the following sort: an expanded version of the comment as a googleDoc with the information above and more (bios? photos?), a google/wikipedia map kind of thing with names of universities, students or rchain "champions" there, accomplishments in terms of code written, application ideas, existing computer infrastructure (where are servers located, what kind of bandwidth/ capacity is available, etc). In a sense this might be like internal "marketing" for our Cooperative membership; it can provide additional visibility into expenditures that myself and other members who haven't yet traveled to Awka, Enugu and other places may not have as much context for. I'm pretty sure that demographically your area has a young and energetic population, so many of your goals are focused on your future and if we are to all work together we will do well to understand each other's conditions, objectives, and vision.

**Comment by nonnykul** [comment]
The first phase of this work has been achieved, there were a good number of attendance of students in the RChain meetup in Africa #796 . 
Students were enthusiatic to learn more about Rnode, during the process I had the opportunity to have a one on one interaction with them to know their plight.

CHALLENGES ENCOUNTERED DURING RUNNING OF RNODE:
1) File directory error with their computers
2) difference in operating system (OS)
 my team and I, contemplated on their plight and came up with a best suitable solution, which is a workstudy group.
 The second phase of this project is starting a workstudy group.

**Comment by pmoorman** [comment]
As a guide going through this issue, I struggle to understand which work was done in May, and which was done in June.... and thus what kind of (additional) reward is warranted in June on top of the May reward.

Can someone (probably the project owner) help me with this?

**Comment by nonnykul** [comment]
@pmoorman please carefully study the issue and my earlier comments, this issue is a work in progress.

Last month(May) we had engagements with university students (which I stated in previous comments) and that prompted attendance by students to the meetup that was held #796.

In June, we continued with a follow of these enthusiastic students thus prompting the formation of a workstudy group.

**NB: This is NOT a one-time effort but a continuous work in progress to bring RChain to the university community in Africa **

**Comment by nonnykul** [comment]
The second phase of this project is in progress.
The workstudy group will be involved in our First RChain developers meetup in Africa on 21st of july.

**Comment by TrenchFloat** [comment]
@nonnykul How did it go? Any updates for us?

Provided it went well and your Measure of Completion in the initial comment is fulfilled, this issue can be closed. GitHub issues don't lend well to continuous works in progress (aside from exactly repetitive tasks like #812); separate issues will help clarify the work you're doing as your goals for this new community change. A new issue like "Expand RChain Africa Student Community to 50 Members" would work well, or something like that.

I propose a $0 budget for July, since it seems the entire proposed budget for this issue ($800 + $600) has already been collected.
