### ISSUE TITLE
Promoting RChain Africa on Reddit 

### ISSUE THREAD

**Issue by jasoncruzzy** [rchain/bounties#704]
A subreddit has been created for RChain Africa. Reddit is an amazing social media Channel with milliions of users, the channel will be helpful for discussions and topics that promotes RChain in Africa markets and provide regular updates on the events of RChain, briefings on less complex and very complex documentation that can onboard fresh ideas for both new members and established members. Click here u/RChain_Africa https://www.reddit.com/u/RChain_Africa?utm_source=reddit-android

Tasks to be done
Create the subreddit ✅100%
Manage the subreddit ✅ 100%
Promote RChain in Africa✅ 90%
Generate content for the page✅90%
Getting members to follow back✅80%
[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

_Estimated Budget of Task:_ **$[400]**  \
_Estimated Timeline Required to Complete the Task:_ **[3days]**  \
_Measure of Completion:_ **[90% completed]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by azazime** [comment]
@jasoncruzzy this is a step in the right direction as long as you would keep managing the account and it doesn't become domant. Nice one

**Comment by philipandri002** [comment]
@jasoncruzzy this is beautiful and I think reddit is even becoming very popular in Africa and this will certainly create the needed awareness for RChain

**Comment by awesome000** [comment]
This is a very welcome idea, as collaborators will get to communicate to each other via the Reddit platform while also promoting the community. We need more of this to make RChain Africa bigger and I would also like to add that all RChain Africa platforms across the various social media channels should be synchronized so as to harness the opportunities within

**Comment by casanwugo** [comment]
@jasoncruzzy... Nice one! We certainly need more of this to reach out more.

**Comment by jasoncruzzy** [comment]
@pmoorman I'm currently working on that at the moment

**Comment by Keaycee** [comment]
@awesome000   please accept this invite 

- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform 
- [ ] Collaborate in all kind of issues https://github.com/rchain/bounties/issues
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Fool around with our Bounty App https://rewards.rchain.coop/
- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by Murphy6** [comment]
It is a huge development

**Comment by jasoncruzzy** [comment]
The reddit address has seen been posted on the telegram groups and some other RChain channels and I update the account with RChain videos and docs twice a week as a way of follow up.

**Comment by jasoncruzzy** [comment]
@JimsCarver @azazime so far we have made significant progress:~RChain Reddit now has 40followers and we have made over 19post to update our followers regularly

**Comment by jimscarver** [comment]
Nice work! Be sure to coordinate with other rchain africa initiatives.

**Comment by jasoncruzzy** [comment]
@jimscarver thanks, I have/will be updating it thrice a week..

**Comment by pmoorman** [comment]
I'll close this issue, for a combination of 2 reasons:

- The issue has turned inactive. No new content has been posted on the Reddit in question

- Generally, we want to move our regionalization strategy towards more of a focus on official channels, so new people wouldn't be confused about what's "real" and what could potentially be scam accounts (remember: for new people it's hard to tell apart a community member from a scammer doing fake airdrops!)
