### ISSUE TITLE
Discussion: Is regional marketing (Africa) worth it?

### ISSUE THREAD

**Issue by David405** [rchain/bounties#716]
Last month, a push to specifically market RChain in Africa began, see #591. Although, there is no standard metric or KPI just yet( _this is being worked upon)_ to measure the progress, there has been evident progress _(even though not so much)_ as the movement is just starting out, there has been more exposure to the African community as there have been addition of new RAMs from Africa. 

In the <a href="https://github.com/rchain/board/blob/master/2018/04-06/Exhibit_C_-_RChain_Maketing_Plan.docx.pdf">Marketing Plan</a>, although no region was specifically mentioned, one of the **Execution strategies made mention of RChain ambassadors to different part of the world**

> We will create RChain ambassadors in different places in the world who will engage with developers in forums, blogs and on social media groups. They will share tutorials, updates and news related to RChain and respond to comments and questions posted on the properties they are active in.

I am strongly convinced that RChain will thrive and will get a good ROI if it invest in Africa. There are a few valid reasons behind my conviction:

- There are alot of problems blockchain technology can solve in Africa [see](https://betterworkingworld.ey.com/digital/tackling-sub-saharan-africa-s-challenges-with-blockchain).

- There are lots of opportunities for blockchain technologies to exploit [see](https://venturebeat.com/2018/04/01/blockchains-big-potential-in-africa/).

- A lot of African governments are beginning to support and create favorable policies for blockchain technologies to thrive, countries such as [Uganda](http://disrupt-africa.com/2018/05/uganda-to-host-africa-blockchain-conference/), [Kenya](https://www.nation.co.ke/lifestyle/smartcompany/Blockchain-roots-deepen-Kenya-/1226-4092118-o2i2go/index.html), [Zimbabwe](https://cryptobriefing.com/zimbabwe-blockchain-bellwether-emerging-markets/), [South Africa](https://www.ccn.com/south-africas-central-bank-plots-ethereum-based-blockchain-pilot/), Nigeria and other countries are adopting blockchain technologies.

- Blockchain and Cryptocurrencies have a lot of use in Africa. [see](https://www.quora.com/How-is-Bitcoin-used-in-Africa).

**Objectives for regional marketing in Africa**

- Creating an active RChain community in Africa.

- Hosting RChain events in Africa.

- Building on the RChain platform as a blockchain technology to solve active challenges african communites are faced with.

- Onboarding software developers from Africa.

- Sharing tutorials, updates and news about RChain on several active african communities and platforms.

- Engaging the african academic and university community with RChain technology.

I believe every on of these objectives is in line with the [marketing plan](https://github.com/rchain/board/blob/master/2018/04-06/Exhibit_C_-_RChain_Maketing_Plan.docx.pdf) presented by the board.  

_Estimated Budget of Task:_ **no reward for this: participation is volunteering**  

_PS: This issue will be included in the members meeting next Wednesday as part of the meeting agenda_
 
cc: @pmoorman, @PatrickM727, @lapin7  

***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by pmoorman** [comment]
@David405 I appreciate you created this issue, and let's use it as a place for discussion.

I've already more or less outlined my position [here](https://github.com/rchain/bounties/issues/591#issuecomment-389939265) which I know is more or less shared by my fellow Marketing guides @AyAyRon-P and @kitblake 

For the sake of discussion, I think a few things would help me get convinced that African marketing is worthwhile:

1. **RChain needs developers**  ::  onboarding RAMs is not the same as onboarding developers that will write Rholang code. If anyone can demonstrate a serious influx of African developers that are downloading the SDK, trying to write contracts and running Nodes... that would be great.

2. **Performance data**  ::  I would appreciate any numbers or "facts" that can steer this discussion. Up till now, I'm basically not aware of any significant results towards bringing developers or decision makers onboard. The traffic / engagement generated seems very low, too. You say _"there has been evident progress"_, but please elaborate specifically what progress we're talking about. 

3. **ROI**  ::  Last month alone we spend almost $10k in Africa-specific marketing. I don't see any significant results for that money. I think we could have spent the money (much) wiser.

4. **Priorities**  ::  To me it seems that all these regional efforts (whether African or otherwise) are pretty inefficient compared to working on the core of RChain marketing. I don't think Dutch-centric marketing efforts (for instance, since I'm Dutch) are warranted either.

**Comment by dckc** [comment]
I guess my question is: worth _what_? These efforts are most likely worth _something_. But I'm inclined to agree with @pmoorman that last month's efforts brought in significantly less than $10k worth of value. And I also cannot judge without seeing the evidence behind the claim of  "evident progress".

I suggest setting modest budgets (some small fraction of what has been previously proposed) with clear, objective measures of success and claiming rewards only to the degree that the measure of success is met.

**Comment by jimscarver** [comment]
I suggest Africa is a top priority to make rchain international and inclusive and not just a white man's club.

**Comment by pmoorman** [comment]
Regarding the white man's club: I'm inviting every African that wants to join and contribute to do so. But that don't mean we need a regional strategy for everyone we want to invite.

**This kind of approach is _NOT_ `"safe enough to try"`:**   (!!)
Many people are turning their back against the bounty system because they believe the system is too wasteful, and too inefficient. We risk destroying the entire system we've worked so hard collectively to create. 

Exactly the attitude of _"we have the rhocs to do X, why not try it"_ is what turned so many against us. That kind of justification feels wrong. A little bit of frugality would go a long way here. 

Every task where we can't explain how our rhocs are turning an ROI, is another justification for another player to lose faith in our bounty system.

**Comment by David405** [comment]
@pmoorman I understand you always emphasize ROI and frugality in spending which is a good thing but I think you are missing the point @jimscarver is making. At some point, **RChain will have to develop strategies for servicing its members and developers in different regions** _(take a cue from Microsoft, Google, Facebook and other global tech brands)_, if this is the case, then why not start now?

I believe marketing efforts must be intentional, a brand **doesn't stumble into a market**, it must intentional execute strategies to penetrate the market. For example, Google, Microsoft and Facebook has widespread presence in other regions of the world aside the U.S. (their home country) and one of the main reasons for this is that they have intentional marketing efforts in these regions ranging from meetups, developers summit, training programmes, scholarships, employment opportunities and others.

**I strongly believe that if RChain must have widespread and active presence in places outside the U.S., then there must be intentional efforts**. 

@dckc @pmoorman I understand and share your views on the need to develop a way of measuring progress but I want you guys to also understand that everything doesn't become perfect at once, things grow and become more organised with time.

For now, I am streamlining all my efforts to give RChain an active presence in Africa to align with the Coop's [marketing plan](https://github.com/rchain/board/blob/master/2018/04-06/Exhibit_C_-_RChain_Maketing_Plan.docx.pdf) which includes the objectives stated in my intial comment.

**Comment by Tonyprisca13** [comment]
@David405 if time permits, this issue will be discussed in the meeting. are you up for this discussion?

**Comment by David405** [comment]
@Tonyprisca13 I can see you have added this discussion to the agenda, Yes I am ready to discuss this. I really do hope time will be squeezed out for this no matter how little.

**Comment by jimscarver** [comment]
I think if we cannot guild african development of the rchain community funding it represents a systematic failure of the bounty system overall.  I do not believe our leadership would favor geographical exclusion. Such a hypocritical policy would be a black eye on the coop.

Can a team be created to guide african development so that it effective? Perhaps we need gudes covering all 3rd world development.

**Comment by dckc** [comment]
(_notes in progress..._)

In today's RAM meeting (#723) @David405 argued his case persuasively. We identified some connections: @Ojimadu is a certified apprentice who is in contact with @PatrickM727 on marketing issues and with @Viraculous on weekly update blog items. @lapin7 said he would support budgets and rewards in this area.

**Comment by Keaycee** [comment]
@dckc Thank you for the information. @jimscarver I agree with your points. We have about four members who signed up for the African guide and i think that will make it more effective with more collaborative efforts. See issue #672 .

**Comment by dckc** [comment]
I just re-read the bit about ...

> one of the **Execution strategies made mention of RChain ambassadors to different part of the world**

Perhaps this issue should be re-titled to "RChain ambassador to Africa" or something like that?

**Comment by David405** [comment]
@dckc, I feel the issue title should remain the same, another issue on "RChain ambassador to Africa" would be created and properly referenced to this issue and #591.

The reason is because this issue is open to provide information regarding ROI for Africa and will continue to act as a centre for discussion, changing the title might just cause it to lose its focus.

**Comment by azazime** [comment]
Am ready to collaborate

**Comment by casanwugo** [comment]
@David405,,,Thumbs up! I am available if my assistance is needed.
