### ISSUE TITLE
Newsletter - May 16th, 2018

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#726]
Here's another issue to stake your claim if you helped out with the newsletter. Here is again the [google doc](https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit) with the notes for all the hangouts and the [Weekly Debrief Index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index).

**Comment by dckc** [comment]
@PatrickM727 @pmoorman @AyAyRon-P @ottermagically Do we still actually do a newsletter? The [newsletter archive](http://archive.sendpulse.com/shc4c/Ace65e732/) has nothing since January 3, 2018.

Meanwhile, the [blog](https://medium.com/rchain-cooperative) is an increasingly reliable place to find write-ups on the weekly debrief: May 2, May 9, May 16. Thanks, @Viraculous . I'm curious about who is reviewing those or how I could add a tweak here or there.

And I still use the [Weekly Debrief Index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index) all the time.

**Comment by TrenchFloat** [comment]
Funny enough, I've never actually gotten a newsletter, despite some effort. I'm closing these (this and #725) as duplicates and opening a "weekly debrief index maintenance" issue.

**Comment by PatrickM727** [comment]
I'll add the newsletters to archive. 

ae actually havent done them for May, as we are staffing up and reconfigureing process's (note debiref posts)

@Viraculous is submitting his summaries to me and @plantether  and @TrenchFloat continues to do good work on the index.

Thanks for staying on top of this

newsletters will be coming back asap starting Mid June... growing pains.
