### ISSUE TITLE
RHOC-REV swap communication plan

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#740]
### RHOC-REV swap communication plan #740

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

Create a clear and actionable communications plan to assure the success of the swap it is critical to create and execute a communications plan that addresses the following in a timely way:

Completion of plan: 

- [ ] Describes and illustrates the swap process
- [ ] Creates an action plan for RHOC holders to prepare for and participate in the swap
- [ ] Targets a broad audience
- [ ] Reduces confusion to mitigate the risk of RHOC holders being scammed
- [ ] Addresses questions from RHOC holders

Execution of plan:

- [ ] media channels running
- [ ] .....

See [RHOC/Rev swap specification](https://rchain.atlassian.net/wiki/spaces/CORE/pages/232587314/RHOC+Rev+swap+specification
)

_Estimated Budget of Task:_ **$1000**  \
_Estimated Timeline Required to Complete the Task:_ **1 month**  \
_How will you measure completion?_ **plan ready** **execution is monitored**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by ResonanceXX** [comment]
Okay. The document is clear. Waiting for other directives to support the process.

**(Wil) the process be similar to what EOS did?** Owner of the text can put the 'l' remaining on this. 

And the question could be answered too.

**Comment by jimscarver** [comment]
Who will do this? needs assignees for SMART objective.

**Comment by Kencode7** [comment]
Do we have an illustrated process already??
Once a well illustrated process is achieved it reduces the risk of any RHOC holder being scammed.

**Comment by lapin7** [comment]
@jimscarver 
>Who will do this? needs assignees for SMART objective.

@leithaus mentioned this in the last debrief as an interesting issue for the bounty system

**Comment by jimscarver** [comment]
I do not see how it is possible to communicate to everyone holding rhoc that is must be in accounts they control the private keys for and not in a multisig, escrow or time lock contract. I think we need to reconsider a contract based conversion rather than an airdrop where not all rhoc will be honored. I am also worried about people being scammed into accepting worthless rhoc after the air drop. I suggest a new rhoc2rev proposal be be made at the next member meeting.  Trading rhoc for rev upon authentication on rchain would make good on our promise to honor rhoc. Rhoc would remain as a stable coin representing rev on ethereum having the utility of enabling cross chain contracting. I have not seen any compelling justification for the currently planned method and hope that there is not too much inertia to change horses now.

That being said, if the current plan moves forward communicating it as many rhoc holders as possible with easy instructions on what must be done to not lose it is essential and I hope we find members to take up the challenge.

**Comment by jimscarver** [comment]
Gtrg says he will devote some time to the rhoc2rev process reconsideration at this week debrief. :)

**Comment by ICA3DaR5** [comment]
I find issue #753 to be relevant to this issue.

**Comment by Ojimadu** [comment]
It looks like the dev team is already working on this. Am checking up with Patrick to confirm.

**Comment by AyAyRon-P** [comment]
For the first item request it says:

**Comment by AyAyRon-P** [comment]
For the first item it says:

**_Describes and illustrates the swap process_**

Is there any opportunity/need for an infographic or will this be in text only?
