### ISSUE TITLE
Translate Community Update21-25 to Chinese

### ISSUE THREAD

**Issue by v56700** [rchain/bounties#746]
Estimated Budget of Task: $[200]
Estimated Timeline Required to Complete the Task: [completed already]
How will we measure completion? 

Community Update 21
you can see it here http://www.rchain.site/?p=584

Community Update 22
you can see it here http://www.rchain.site/?p=591

Community Update 23
you can see it here http://www.rchain.site/?p=618

Community Update 24
you can see it here http://www.rchain.site/?p=630

Community Update 25
you can see it here http://www.rchain.site/?p=652

**Comment by zero-andreou** [comment]
Please use the new [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

**Comment by allancto** [comment]
@v56700 it looks from your work that you've actually added commentary/ analysis/ summarization. If you can also translate this from Chinese back into English I would vote a 20% higher reward because I feel commentary and analysis makes these materials more valuable to all of us. In particular these videos represent the history of our Cooperative and anything you can do to make them more accessible and understandable is a great contribution. Some suggestions: call out "quotes" you find particularly insightful or stimulating. Add time indexes. Show where assertions in the debriefs resulted in future actions within our Cooperative. Trace the evolution of new themes as they move from concept to reality. And especially, notice how discussions in the debriefs sometimes result in the "cooperative intelligence" combining thoughts and experience of the participants to inspire new directions and new understanding.

**Comment by ICA3DaR5** [comment]
The work seems very well made, although **please** use the [**ISSUE_TEMPLATE**](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

**Comment by ICA3DaR5** [comment]
Because there was no answer from the participants of this issue, although they have voted for a budget and rewards, the translation guides are slashing the voters.
