### ISSUE TITLE
"Return" of burned tokens

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#753]
### Benefit to RChain

[My Ethereum Address](https://etherscan.io/address/0x33678Cb73B27ad766FB4cF49C3b007E5C46d1a49) (which is also known to the bounty system and the co-op, since the beginning of my involvement.)

1. I got paid by the bounty system for the month of March the amount of [4,135.33 RHOC's](https://etherscan.io/tx/0xa87db2136df64e06dcf4afdbf0be49b4d2bc5c8181d7ede0d21c364b9d5a4885), then I mistakenly sent [3,135.33000018 RHOC's](https://etherscan.io/tx/0x308750e703503d1849f79a8988c55ba5ee7306a03e0577d88363188a0421f5e7) back to the [RchainToken Contract Address](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x168296bb09e24a88805cb9c33356536b980d3fc5)

2. I also mistakenly sent another [768.18181818 RHOC's](https://etherscan.io/tx/0x9efdf29f8daf210bd9955d676cfda045d92205d3a96d527bb0a50305c39d0052) back to the [RchainToken Contract Address](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x168296bb09e24a88805cb9c33356536b980d3fc5)

Sending the RHOC's to the [RChainToken Contract Address](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x168296bb09e24a88805cb9c33356536b980d3fc5) essentially **burns** them.

**Total of RHOC's I've burned**: 3903.51181836 RHOC's

### Budget and Objective

_Estimated Budget of Task:_ **3903.51181836 RHOC's**
_Estimated Timeline Required to Complete the Task:_ **TBD**
_How will we measure completion?_ **[RHOC's are returned to the rightful (IMO) owner :)]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Jake-Gillberg** [comment]
Does this conform to the bounty TOS?

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg IMO, this is a special case.

**Comment by jimscarver** [comment]
See [this discussion on discord](https://discordapp.com/channels/375365542359465989/406191011564617748?jump=453149174662168576) for justification.

This is a case of recovering the expense of burning RHOC, something the coop has voted to do anyway, and making whole a devastating accidental loss because we can, because we care, and because it is the right thing to do.

**Comment by Jake-Gillberg** [comment]
In [this discussion on discord](https://discordapp.com/channels/375365542359465989/406191011564617748?jump=453234243472982016), it sounds like these tokens might not even be burned, and they might be given back in the genesis block.

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg That's a 50-50 approach and harder to do, contract code and scripts are needed. What @jimscarver proposed it's much easier and efficient.

**Comment by Jake-Gillberg** [comment]
It is my opinion that we should hold off on returning these rhocs until we know if they will be returned via the genesis block generation process. Otherwise we risk either A) rewarding this mistake by doubling the RHOC you sent to the wrong place, or B) complicating the genesis block generation process even further by providing an exception to the rule of "rhoc sent to rhoc token address is returned to sender".

**Comment by ICA3DaR5** [comment]
In @jimscarver's proposition RHOC's are not returned to my Ethereum Address from the contract thus no exception is needed in the genesis block generation process.

The co-op has decided to burn RHOC's anyway, so the only thing that has to be done is re-pay me and remove those RHOC's from the total of to-be-burned RHOC's.

**Comment by Jake-Gillberg** [comment]
RHOCs are not burned if they will result in ownership of Rev on the RChain platform.

> In @jimscarver's proposition RHOC's are not returned to my Ethereum Address from the contract, thus no exception is needed in the genesis block generation process.

More than just your RHOCs were sent to the RHOC contract address. In the discussion I linked above, Kenny seems to imply that these might be returned through the genesis block creation process.

Also, I seem to recall in a prior hangout Greg saying something to the effect that the resolution to burn RHOCs is not actionable (because it contains no amount specified) so no action will be taken.

**Comment by jimscarver** [comment]
I vote to go ahead and vote. We can always change our vote before july 9.

We need to estimate the rhoc price to budget this issue.  Today's price is as good as any $1.25. We can adjust the budget later. I'll vote  $6000, which is the full 6129.39 minus a129.39 penalty for not being careful :)

**Comment by ICA3DaR5** [comment]
@jimscarver I am voting as well, thanks jim!!!

**Comment by ICA3DaR5** [comment]
Voting $6000 on this.

**Comment by dckc** [comment]
@ICA3DaR5 is there more discussion you've had with board members about possibilities around the RHOC to REV transition that you haven't shared here? Please give the whole context.

**Comment by dckc** [comment]
Ah... perhaps Jake's June 5 comment summarizes the relevant points.

https://github.com/rchain/bounties/issues/753#issuecomment-394470584

Based on that, I'm afraid I'm obliged to vote against this.

**Comment by ICA3DaR5** [comment]
@dckc I've discussed them above. Okay, I don't know what to do here. :)

**Comment by deannald** [comment]
It's my understanding that you should be able to reclaim your "stuck" RHOC when the redemption process is in place towards the end of the year. I'm in agreement with @dckc and am obliged to vote against this as it violates the purpose of the Bounty System. If, at that time, you are unable to obtain the RHOC, we can readdress. I know you have done quality work for the Bounty System and have been fairly compensated but having your RHOC in holding has got to be frustrating at best.

**Comment by ICA3DaR5** [comment]
Voting $0 on this and pinging the other votes to do the same! Closing this issue! :)
