### ISSUE TITLE
Translate "RNode v0.4.1 introduces sending Rholang smart contracts across the network" - "RChain Weekly Update (Debrief 83) 27th June, 2018" Medium blog posts to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#757]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

### Budget and Objective

_Estimated Budget of Task:_ **$[2300]**
_Estimated Timeline Required to Complete the Task:_ **[8 days]**
_How will we measure completion?_ **[Post "RNode v0.4.1 introduces sending Rholang smart contracts across the network" - "RChain Weekly Update (Debrief 83) 27th June, 2018" Medium blog posts translations to the [RChain Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο)](https://rchaincommunity.xyz/c/Greek-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC/Blog-%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF)]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because translation of the RChain Medium blog posts to other languages means good global marketing.
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Greek
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency in English from institution: University of Michigan - @ICA3DaR5 | degree / certificate: Proficiency in English from institution: Edexcel - @zero-andreou 
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #497, #540, #585, #586, #597, #621, #650, #652, #686, #688, #715, #719, #721, #738 
       - [x] another body of work readily available for community review: [decred/dcrdocs](https://github.com/decred/dcrdocs/tree/master/src/i18n/el)
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by deannald** [comment]
Hey! The RChain Community Forum link from the original post is broken. I'm getting the error: 

"This site can’t be reached
rchain.gr’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN"

I'd also like to see a link for the original article you are translating from.

For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by deannald** [comment]
Ok, thanks!

**Comment by ICA3DaR5** [comment]
This has been completed!

**Comment by ICA3DaR5** [comment]
This has been completed.
