### ISSUE TITLE
Translate the Medium blog posts to Chinese Part4

### ISSUE THREAD

**Issue by yuhuanmocmoc** [rchain/bounties#761]
I will translate these Medium documents into Chinese with @rjl493456442.

1.[Introducing RSpace](https://medium.com/rchain-cooperative/introducing-rspace-ea12897daef2) [742 words]
2.[RNode-0.2.1 integrates Rholang to the RChain Node](https://medium.com/rchain-cooperative/rnode-0-2-1-integrates-rholang-to-the-rchain-node-183c0e13b024) [779 words]
3. [rnode-v0-4-1-introduces-sending-rholang-smart-contracts-across-the-network](https://medium.com/rchain-cooperative/rnode-v0-4-1-introduces-sending-rholang-smart-contracts-across-the-network-e076d0961b3e) [939Words]
4. [rchain-weekly-update-debrief-80-june-6-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5) [1707Words]
5. [rchain-weekly-update-debrief-81-13-june-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-81-13-june-2018-415b4318b02b) [1859Words]
6. [RChain Weekly Update (Debrief 82) — 20 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f) [2615 words]
### Budget and Objective

_Estimated Budget of Task:_ **$[1800]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **[upload to google doc and post to Wechat official account of China and Medium]**

*See CONTRIBUTING.md for details on budget and reward process.*

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #242, #246, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:xx

**Comment by zero-andreou** [comment]
Please use the new [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

**Comment by allancto** [comment]
@yuhuanmocmoc please consider that than simple translation is less the goal of our Cooperative, we want to add value to materials that are to be translated or utilized. One way to do this is to develop groups of people working together, because we value and are trying to develop Cooperation at Scale. Another way to add value is to analyze materials being studied or translated, and encourage discussion in both Chinese and in English. 

Do you work with @zsluedem? If so you may consider consolidating this issue with #750 and #745. @michaelizer also please see which related issue numbers may be consolidated so that Cooperative members not directly involved can more quickly get an overview and some understanding of all the activity taking place. Thanks!

**Comment by rjl493456442** [comment]
@allancto We are open to cooperation! But i have not figured an effective way to do that. I mean me and @yuhuanmocmoc are focus on the translation and Wechat official account running. I have no idea what @zsluedem is doing. But yes, definitely the more cooperation, the larger promotion will be created!

**Comment by yuhuanmocmoc** [comment]
all the translation Medium blogs have been uploaded to [Google doc](https://drive.google.com/drive/folders/1SoO3bcXzJt3rO1me-Kr9a-P_Kb7iD_6A).
1. [Introducing RSpace](https://drive.google.com/open?id=1ImD26UaF5LTvED7A6O2hGp68FqI2j4JS)
2. [RNode-0.2.1 integrates Rholang to the RChain Node ](https://drive.google.com/open?id=1_qvCfsqbeFyYAwdEz5TVT0pI-emCLgK1)

**Comment by yuhuanmocmoc** [comment]
we have posted some of them to [Medium](https://medium.com/rchain-cooperative-china)

**Comment by ICA3DaR5** [comment]
1. Please use the new **[ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)**

2. Please check @allancto **[comment](https://github.com/rchain/bounties/issues/761#issuecomment-395944086)** on added value.

**Comment by deannald** [comment]
For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by ICA3DaR5** [comment]
@yuhuanmocmoc So, you haven't responded and haven't used the new **[ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)**
