### ISSUE TITLE
 Translate rholangtut-0.3.md to French

### ISSUE THREAD

**Issue by niwaa** [rchain/bounties#762]
## Original (English) Content
[A Rholang tutorial](https://github.com/rchain/rchain/blob/master/docs/rholang/rholangtut-0.3.md)

### Benefit to RChain

This step is an effort to translate the content of https://developer.rchain.coop/ in French. This document, once published, will be indexed by search engines and bring organic French web traffic to the RChain website. 
A next task should be to properly generate a French version of the developer website.

### Budget and Objective

_Estimated Budget of Task:_ **$[1200]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **[pull request merged]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #272, #671
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: Update changes on new version

**Comment by allancto** [comment]
@niwaa @truffard we're trying to move toward value-add rather than simple translation. Can you form a French language group to study and comment on the documents translated rather than just translating? Please include @Pionelle and others translating into French as well. I believe that @lapin7 is a French speaker, perhaps he may recommend others who may be interested in participating in French language group to study/ translate/ discuss/ suggest new ideas in both French and English. 

Also please consolidate all of the related French activity into a single issue number. Multiple issue numbers results in loss of focus and too much time spent tracking related projects. @michaelizer and the other guides working in non-English languages, please also try to help getting related projects consolidated where appropriate, and encourage formation of groups to get more "collective intelligence"/  "Cooperation at scale". Thanks!

**Comment by truffard** [comment]
@allancto I see your point. @lapin7 already stated that in order to translate a document, one must be a native speaker and unfortunately, this is far from being the case. Scores of people are parasitizing the issues and how can a non-native speaker review and edit our work? It's really challenging to vet and approve of qualified people, and most of the translated result is pathetic (see previous issues).

**Comment by truffard** [comment]
@allancto  I and @niwaa will complete that translation and we will take your comment into consideration.thanks

**Comment by allancto** [comment]
@truffard I disagree with @lapin7 that being a native speaker is always necessary. In fact we have many non native speakers of English who make excellent contributions by being perceptive rather than fancy with words. 

If you agree that "most of the translated result is pathetic" how will you improve the situation? My suggestion is to form groups with French speakers and integrate them into the study process. This will also help you add value to translations. Translations by themselves are not particularly valuable, it is inspiring understanding and application and IMPROVEMENT of RChain materials that carries the high value you are seeking in your proposed budget here.

**Comment by truffard** [comment]
@allancto how can a non native speaker review and edit my work?

**Comment by allancto** [comment]
@truffard where is your work reviewed and edited by a non native speaker? Translation per se is not a priority for our Cooperative. Working cooperatively at scale, and adding value by improving the original material may be, at least that's my suggestion. 

There's some discussion of this in #755 , for instance ../755#issuecomment-394961763. If you're interested in taking the existing Rholang tutorial or other documents and improving them (in French AND in English), or creating a workgroup around utilizing and applying the tutorial or other documents within a community of French speakers, I will likely support the effort. If there is no value add I will vote for a low or no budget. You are free to do whatever work you like, but there is no guarantee of reward, and I am offering my opinion of the value to our Cooperative of the current proposal.

**Comment by allancto** [comment]
Here's some work i just started on today's DoCC video. I got inspired because of a question @ddayan asked about the purpose of the course. I also annotated the first 1/4 of the youtube transcript a bit. I'd like your feedback, do these two documents add value for you when you watch the video? If so i've succeeded! (if not I'll try again). Even better, you can make suggestions or write another introduction or an analysis or commentary on any part of the video, i'm interested to hear your opinions too. 

https://docs.google.com/document/d/1mM9bHdzav2ZiSaT1H36LZyI2iFUD6-AmuvgjlfSfWXE
https://docs.google.com/document/d/13vUJmriOHG7G1_Bnb68HgJnwAcnxetr0OXL0oKobE-Y

**Comment by ICA3DaR5** [comment]
@niwaa Please post the Pull Request here. Also this document has been removed from the repository so IMO it's obsolete.
