### ISSUE TITLE
Supporting the networking drinks at OPEN 2018 to promote Rchain

### ISSUE THREAD

**Issue by olisb** [rchain/bounties#770]
### Benefit to RChain

This proposal is asking for some budget to support the networking drinks at the [OPEN 2018 Platform Co-ops conference](https://2018.open.coop) in London on the 26th and 27th of July.
The networking will involve 400 people from across the UK who are specifically interested in co-ops and using technology to help grow the co-op sector and to connect more members. The benefit to Rchain is to promote what Rchain is, disseminate information about the Rchain Co-op and to encourage people to join - with this key group of stakeholders.
We have Peter Harris (from Resonate speaking) as well as Claire Tolan - plus Jonathan Kochmer will be attending too, so there will be a few people on hand to help spread the Rchain message and answer questions.

Patrick Maguire suggested that this would be a sensible ask for a bounty.

### Budget and Objective

_Estimated Budget of Task:_ **$[1500]**
_Estimated Timeline Required to Complete the Task:_ **[we would need to know if this is possible within 3 weeks from the date of this issue - then the networking event will take place on the evening of the 26th July 2018 ]**
_How will we measure completion?_ **[the networking event will take place on the evening of the 26th July 2018 - measure might be the number of people that attend, find out about Rchain and any new sign ups]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by jimscarver** [comment]
Another member I know will be there, John Grant. A number of folks I know from the digital life collective who have been collaborating with us on self-sovereign technology and identity will be there also. Hopefully we can make members of more of them linking stronger our cooperation. They are also a sponsor.

I think the exposure we get becoming a sponsor is well worth it.

**Comment by ResonanceXX** [comment]
Along with any meaningful gesture that does not directly reveal itself as Marketing. Using a Proximity marketing style, slightly understated gestures like this - are heart warmers - and I figure some Niche with plenty of developers having the brand name around is good. 
A sort of Micro-community marketing also, and the feel good effects, warms them up to Rchain. Maybe you could have a stand with the RChain logo where the drinks are situated (Or any other thing which works well). 
Your idea is promotional and very targeted. (Might have beautiful ushers 'serve' the drinks with branded RChain shirts. Just maybe. Cheers.

**Comment by jasoncruzzy** [comment]
Nice work, a very good concept.....I'm also planning on promoting RChain using an event like this in my country.

**Comment by dckc** [comment]
I don't this was closed on purpose.

**Comment by olisb** [comment]
Thanks @dckc  - I was wondering why it got closed! The Rchain logo will be printed on the event lanyards and people will have to show their lanyard to get a free drink so the Rchain brand will be very visible - we will also place other Rchain branded info around the space where the drinks take place.

**Comment by jimscarver** [comment]
Sounds great Oli. I added [my vote](https://rewards.rchain.coop/index.php?-action=related_records_list&-related-record-id=issue%2FBudgetVotes%3Fnum%3D770%26BudgetVotes%253A%253Apay_period%3D2018-05-01%26BudgetVotes%253A%253Aissue_num%3D770%26BudgetVotes%253A%253Avoter%3DOjimadu&-table=issue&num=%3D770&-ui-root=main-content&-sort=num+desc&-cursor=0&-skip=0&-limit=30&-mode=list&-relationship=BudgetVotes)..

**Comment by Ojimadu** [comment]
@olisb I like the idea you're proposing. I'll add a vote. Until when is the sponsorship open? I ask because this is for the pay period 201806 which would likely be paid for by mid or late July. I'd like to know if you can fund the sponsorship from your side and claim the rewards later in July that'll be great.

**Comment by jimscarver** [comment]
It needs one more [vote](https://rewards.rchain.coop/index.php?-action=related_records_list&-related-record-id=issue%2FBudgetVotes%3Fnum%3D770%26BudgetVotes%253A%253Apay_period%3D2018-05-01%26BudgetVotes%253A%253Aissue_num%3D770%26BudgetVotes%253A%253Avoter%3DOjimadu&-table=issue&num=%3D770&-ui-root=main-content&-sort=num+desc&-cursor=0&-skip=0&-limit=30&-mode=list&-relationship=BudgetVotes) (3) to be funded. There is zero chance it would be slashed since there has been npo concerns raised but I will personally guarantee payment. This should have been done last month :)

**Comment by jimscarver** [comment]
We have 2 votes a $1500 budget now, but also an issue, we usually pay an rchain member.

Is there a company to be paid? @lapin7 can we pay a company?

**Comment by ResonanceXX** [comment]
I don't know if votes from non trusted members like mine counts.

I have been very dismissive of the voting app for a while now. Count on my giving this a try at some time later today.

**Comment by jimscarver** [comment]
@ResonanceXX you have been certified. Due to the current limit on apprentices I am not sure your vote will count. I added my certification so I think it will. I do not like the fact that this can push someone who had a vote before to having their voted not counted. I expect we will increase the number who can vote to help reduce the burden on guides.. We tried increasing it last month by too much and found too many bad actors had been certified.

Votes of those without a vote help me as a guide know how to vote. Voting reasonably and certifying good actors is how one earns certification, Plus even if your vote does not count today, it may count the closing of the month.

Your participation in the reward system is greatly appreciated.

**Comment by ResonanceXX** [comment]
@jimscarver Thank you very much for your efforts. As I type this, I am giving a corresponding vote for this issue. 
@olisb Good luck with the meeting, I honestly hope that it goes to plan.

**Comment by jasoncruzzy** [comment]
Very sorry  I closed  this before,  it was a mistake

**Comment by PatrickM727** [comment]
@olisb if you want the budget to go to you, sync with rewards.rchain.coop

**Comment by Ojimadu** [comment]
@olisb the conference starts tomorrow, any updates on this?

**Comment by olisb** [comment]
i have joined the co-op, done the sync, had my ID verified etc but still not worked out how to actually get the bounty...? However, @jimscarver has kindly loaned us some funds to enable us to promote Rchain, which we will be doing tomorrow and on Friday - and once we have the bounty we will pay him back! - Thanks Jim! @Ojimadu I hope that answers your question?

**Comment by Ojimadu** [comment]
Yes, thank you.

**Comment by allancto** [comment]
@olisb i see a reward due but i you do not seem to be properly registered. Please see contributing.md and particularly [RChain Active Member Registration](https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform). Let me know if you need any help with this. 

Thanks! -@allancto
/cc @Ojimadu @jimscarver

**Comment by olisb** [comment]
Hi @allancto 
yes, I could do with some help with this - do you have time to zoom / Skype to walk me through what else I need to do?
best
Oli

**Comment by dckc** [comment]
I see a reward in the 201806 pay period. So this is pretty clearly done.
