### ISSUE TITLE
Decision on the need (or lack thereof) for translations/localisation/regionalisation

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#774]
As guides for marketing @kitblake @AyAyRon-P and myself found out that it's incredibly hard to allocate budget to proposed tasks or tactics when they don't clearly fit into a larger kind of strategy.

One area in particular, is all the work that's being done for localisation & regionalisation: making RChain available in different languages, for different geographic regions, etc.

### Goal

As a guide, I would like to have some strategic guidance as to how we should value these localisation efforts.

### 2 options 

There are roughly 2 different "camps" in this debate: 

1. The first group says...  "Being inclusive matters. That means we need to cater to every corner of the world, and leave nobody behind. For that reason it's good to localize everything as far as possible." 

2. The second group says...  "We should focus on the core. Localisation should only be done in specific situations, rather than by default"

Without a clear choice by the community on whether to pursue either strategy 1 or 2.... it's impossible to value the work done under such projects.

### SMART goal of this issue

I would like both camps to defend their case here as clearly as possible, and then distill a 'multiple choice' sort of question to either the Executive Committee or some other authoritative organ, and have them make a strategic decision on this. 

It should have the form _"should be pursue [strategy X] or should we pursue [strategy Y]?"_

**Suggested budget:** $xxxx
**Timeline:** Formulate question before next Exec Committee meeting (can some on fill me in when that is?)

----

_I guess this issue is a bit of a follow-up to https://github.com/rchain/bounties/issues/483 by @Jake-Gillberg. Please read that issue also!_

**Comment by pmoorman** [comment]
To start things off...

### My personal take on this:

- A cool part of RChain is the community, and how international it is. It's cool that we work together with Asians, Africans, Europeans and Americans alike.

- We shouldn't push people into region-specific channels. That would mean all Dutch people hang out on the Dutch forum, all French on the French forum, etc.  That will cannibalise on the _main_ channels, and is not desirable. 

- Considering that we're still pre-launch and very early stage, I think the default setting should be _"no translations, unless..."_  rather than _"always translate to every language"_

- **Localization is not needed, with the exception of the Chinese market.** In other words: RChain should speak English (primary) and Chinese. The rest we can deal with later, but is a waste of energy right now.

**Comment by jasoncruzzy** [comment]
I suggest we support Option(strategy 1 and 2) non should be left but I will elaborate more on Regional marketing Reasons; 
   Regional marketing is also effective, because those familiar with the regions and having a good knowledge of what is most effective for each region for on boarding new developers,,"As local media has a closer relationship with its audience, people tend to trust it. If you can be a part of that community, and talk in the same way as that publication and audience, then people are more likely to listen to what you have to say and trust you.
    1) The necessity of translation issues is an aspect of regional marketing because every region has to communicate(on board) their developers in a language they understand and every region is required without exception.
    2)for instance Issue #681 Getting tertiary institutions in Africa involved in RChain is another development because so far we have been able to speak to alot of tertiary institutions directly and most of the students are enthusiastic about the prospect of RChain and the idea adopted by (African) developers.
     3) one of the executive strategies of the MARKETING PLANS states "We will create RChain ambassadors in different places in the world who will engage with developers in forums, blogs and on social media groups. They will share tutorials, updates and news related to RChain and respond to comments and questions posted on the properties they are active in."....Although no specific region was mentioned I will use 'Africa' for example we are fulfilling the objectives excellently and that's also Regional Marketing.
    5) Penetrating the market requires strategies and one of which is REGIONAL MARKETING. Most important questions are; Is the regional marketing yielding results? YES, (gradually).....Is the regional marketing bring full ROI at the moment? NO,but a work in progress

**Comment by jimscarver** [comment]
Planting seeds in virgin markets before our competition takes hold bears fruit in the long term. There are many benefit to global marketing](https://www.quora.com/What-are-the-benefits-of-international-marketing). There is little benefit to leaving our rhoc treasury idle when it might be invested in the future of rchain. A focus on the short term is not necessary and thus undesirable. Getting rhocs into more hands in itself valuable as it increases the number of people with a stake in rchain promoting it in their circles. Supporting translations is a good way to get rhocs flowing into new markets.

At the same time we want to encourage translation that promise a wide readership or why bother. We want to reach the widest audience possible and not restrict ourselves to target groups like developers. A general awareness of rchain is needed first in order to conquer a market.

Translation is a part of a marketing process that either attains an adequate readership or not. One person may have all the skill needed but the selection, translation, review, publishing and promotion needs to be a team effort in my view. Cooperative work is necessary and it promotes a collective intelligence. 

I suggest people doing pieces of the activity need to find their team and guides should help bring teams together. It is not clear to me that translations without a marketing plan should be funded. We need to be about cooperative work, not isolated things done independently. Teaming up into small well connected teams is what is most productive and prevents an organization from becoming chaotic as it scales.

Proactively obeying the 10 patterns of decentralized organizations and collective intelligence principles is our challenge for every label in my view. The issues we have had with translations bears evidence to that need.

I would be very liberal in placing value on readership independent of demographics. If something is worth publishing and promoted in english, it is worth doing it in every language in my book. We need to be where our competition is and should beat them to where they are not. If we might do the translation someday means we might as well spent the rhoc now for the greatest benefit in the long term.
 We best overcome the scarcity mentality if we hope to scale.

**Comment by philipandri002** [comment]
First I would like to support@jasoncruzzy &@jimscarver. Marketing as a major business tool for growth is very important and also very expensive. To penetrate into peoples mind and capture their attention takes a lot of work and strategy.

Marketing for either company's whether for new products or existing product has always been strategy and very expensive too.

The essence of regional marketing and promotion can never be over emphasized.
Recently I was speaking with some Africa developer who seemed not to know much about Rholang and Nodes were captivated and enthusiastic about the RChain platform because they saw the inclusive of Africa in the RChain ideology. ( it show that RChain can carter for not just their talent but their dreams). These was possible because of the little and effective awareness that the RChain Africa section has been putting in place and I believe the same applies to various regions which includes China,Arab etc.

Let me wrap with an adage that says what is good for the goose is good for the gender.. If you have it in English why not have it in French..

Thanks

**Comment by Ojimadu** [comment]
Am in support of "focusing on the core" but there's a need to support localization to a certain extent; when there's an audience. Most translations have little or no audience, there needs to more organization around it like what documents to translate and into what languages. 
Same goes for social media channels, these channels are good to organize people of specific regions and countries for now I think that should be about it. When it comes to marketing, instead of compartmentalizing our efforts we should focus driving people into the coop from there they'd find their way to whatever local channels are available.

**Comment by Valentine-Mario** [comment]
Focusing on the core would only limit the outreach/popularity the community needs. Let's take some frameworks likes React JS, Vue JS, etc they only became popular due to meetups which involved localization. Localization is a very vital marketing tool that many big guns in the tech industry have exploited. And further still, some of these documents for on boarding new members sound quite technical and isn't well understood by newbies who want to join the community.

The team is work with in penetrate ngozi the Africa market have recorded more success than we would have done in Github and we are growing steadily from just one meet up.
I'm strongly in support of regional marketing because in the long run, it is very profitable.

**Comment by pmoorman** [comment]
UPDATE: had a call yesterday with @allancto @ICA3DaR5 and @michaelizer regarding this topic. A few (partial) outcomes that I think are worth sharing:

### Discourage regional entities that encourage siloing of members.

Consider the following scenario:

- I create an issue to open a "RChain Holland" Discord channel. The purpose is to have a Dutch discussion forum. 

- In here @lapin7 , @kitblake , myself and all other Dutchies hang out. It's open to everyone, but we speak Dutch, so in practice it's only open to Dutch people

- Other people do similar things for Germany, Italy, Latin America, etc. etc.

On the call we all agreed that this sort of efforts aren't very valuable to the coop, and should even _**actively be discouraged**_. The reason for this is that this splits the community. People should hang out in the main Discord channel, rather than isolate themselves. 

_There is also a horror scenario where I build this Dutch community (paid for by the bounty program), and because I created the account, I have the admin keys to this property. Once I have firmly established myself, I run a scam airdrop or something of the sort... and people can't distinguish "the real RChain" from the community that I've created._

Conclusion: all these regional efforts should be actively discouraged. We shouldn't cannibalise on the main (Coop-controlled) properties.


### Value-added translations

@allancto has suggested that translations in and off themselves aren't always very valuable. But, often people can supplement the "core piece" with a regional twist. For instance: better than translating a piece on RChain to Dutch, one could take that piece and write commentary and supplements for it, that explain how this piece is relevant to the specifics of the Dutch context (or the French / Russian / African / etc. context)


### Regional strategies like meetups, etc. are still very valuable

These are excellent examples of taking the core content of RChain, and giving it a regional / local twist. Similar to the "value added translations" this kind of stuff adds value due to the personal nature of the events. 


###  This issue goal needs an update

The top-level "strategy A vs. strategy B" decision is maybe way too big to tackle here, and needs more time to be sorted out by the community at large. @allancto suggested that some questions like that are better not tackled head-on.

I'll need to reconsider how I rephrase this issue, and what more we want to get out of it. [to be continued]

**Comment by AyAyRon-P** [comment]
After reading all of the comments and feedback there is something to be said about both sides of the coin. 

There are a multitude of regional activities as @pmoorman mentioned above particularly with the meetups that add a great deal of localization value. What doesn't add value to me is the translation into every language as I had openly stated before and mentioned in #483. 

These questions immediately come to mind:
- Does every language need it's own translation to feel "included" or does that create more silos? 
- What if the community is actually more similar across the markets and DOESN'T need localization?
- Why can't the goal of implementing a true marketing strategy that achieves scale be justification enough to losing some local customers in return for global efficiency? 

What comes to mind next is, how much will local adaptation cost? What is the potential return on the costs of adaption (how many more developers and new RAMs will we reach)? and will adaptation delay implementation (for example, a new marketing campaign or messaging)? RChain's multinational community thrives on scale and this scale favors standardization across markets. If we continue to push for localization without implementing a completed marketing strategy in English, how successful can that be? 

In my opinion this issue in it's entirety, boils down to trading off or waiting on the locally optimal programs in favor or globally optimal ones now. 

Before I decided to add my flavor to this discussionary pot, I did some reading and perhaps you will also find the reads as interesting as I did. 

**RESEARCH DOCUMENTATION IDENTIFYING MARKETING UNIVERSALS**
https://www.jstor.org/stable/1252271?seq=1#page_scan_tab_contents

**VALUE OF PROPER LOCALIZATION MARKETING**
http://www.europeanbusinessreview.com/why-localisation-is-key-to-global-marketing/

**TRANSLATION COMPANY ARTICLES**
https://phraseapp.com/blog/posts/how-important-is-localization-for-your-business/
https://phraseapp.com/blog/posts/localization-isnt-just-about-translation/

**Comment by azazime** [comment]
Well, having read about the different perspectives people have on option 1 & 2 I would like to start by saying everybody made a valid point and its really important this debate is coming up now.

Firstly, regional marketing in itself doesn't affect the global goal of Rchain negatively and should be encouraged because I believe Rchain members in various communities around the world should know how best to market Rchain to people around them.

Secondly, on the translation issue it has to be noted that not every country uses English to communicate and since the goal of Rchain is to become global, translating to various languages cannot be over emphasized especially for important informations hence the guides in charge of translation should generate a template as it deems fit.

So I think the option 1 is better and necessary

**Comment by kitblake** [comment]
This has been a fruitful discussion. It's so broad that I don't think we can draw conclusions (so here I'm with @allancto). You can see it already in the title: translations/localisation/regionalization. Wow. But here are my two Satoshis:

Translations
I think @ojimadu is correct when he says: "Most translations have little or no audience". Imho translation is a decision that should by made by native speakers who are 'on the ground', living in the region, and active on the technical side. @ojimadu's suggestion that we focus on driving people into the Coop is right on.

Localization
I agree with @pmoorman that "Localization should not be done by default".

Regionalization
@jasoncruzzy and @jimscarver make convincing arguments about the importance of regionalization. Certainly organizing for increasing RChain awareness – like running Meetups – is contributing to the global goals.

"Should we pursue [strategy X] or should we pursue [strategy Y]?"

The 'big marketing plan' is entirely focused on getting more developers involved. I think we should accept that as the focus of the marketing funnel. We shouldn't be spending time evangelizing to the general public because that requires explaining blockchain in general. 

But there is a larger target group around the coders – as the funnel flares – that's up-to-speed on crypto, technical, and capable. The ecosystem needs their skills too. That's the area our regionalization efforts should cover.

**Comment by ICA3DaR5** [comment]
I completely agree with everything @jimscarver said in his above comments!

**Comment by casanwugo** [comment]
I support Option 1 alongside @jimscarver and the others. This is because, in a business context Localization includes translation, but it also works with everything else in your content that has meaning: Pictures, colors, prices. Because these points are more subliminal, localization connects with consumers on a deeper level, improving their likelihood to buy.

For example, imagine you’re comparing sunglasses on two different eCommerce sites. On the first, the graphics look “weird,” prices aren’t in a currency you recognize, and you can’t read the language. On the second, everything you see–images, words, amounts–make sense to you. Which would you buy from? The second one, right?

You’re not alone: Common Sense Advisory reports that 75% of consumers agree or strongly agree that when faced with the choice of buying two similar products, they are more likely to purchase the one that has product information in their own language.

Businesses with the most international success are those that adapt content for customer culture, language, and etiquette. That’s why they use localization to customize currency, date formatting, units of measurement, and other details that translation alone won’t catch.

That being said, i strongly because the coop would compete favourable and possibly come on top in the blockchain industry if localization is tagged along on every stage of development.

**Comment by pmoorman** [comment]
Hey all,

I think my aim with this issue — to get a top-level decision on what to do with regards to localisation, regionalisation & translations — was probably unattainable from the start. Because of that, I want to close off this issue now.

That said, I think it's led to valuable discussion, that helps the bounty system forward. Here's to hoping we can further converge towards a "social consensus" on these topics in the future.
