### ISSUE TITLE
Promoting RChain on Bounty-one(Blockchain discourse web) 

### ISSUE THREAD

**Issue by jasoncruzzy** [rchain/bounties#778]
Bounty-one 
A place for blockchain developers and enthusiasts to talk about new ideas and build dapps together. Explore ideas, contribute to them, build the future.

Bounty-one is for blockchain developers to get together and combine their minds to create the truly exceptional!

You can find project ideas, news, learning resources and much more.

Post new ideas or questions that you want to share.

98% members of Bounty-one are BlockChain Developers.

 I created RChain account on Bounty-one web to act as a representative(developer) for RChain, sell the RChain ideologies, create RChain awareness amongst developers and possibly on board new developers for RChain.
  Here is RChain_Coop profile on Bounty-one. Click 👉https://talk.bountyone.io/u/RChain_Coop

OBJECTIVES

- [x] Create Bounty-one account(RChain)

- [x] Manage the account

- [x] Promote RChain on Bounty-one 

- [x] Generate Content for RChain_Coop(Bounty-one)

_Estimated Budget of Task:_ **$[1000]**
_How will we measure completion?_ **[Objectives]**

**Comment by casanwugo** [comment]
Good one @Jasoncruzzy,, i was able to create an account on the bountyone web space. Hopefully, will be able to follow through with what's going on there. Nice work you put!

**Comment by jasoncruzzy** [comment]
BlockChain developers getting interested in RChain....see here https://talk.bountyone.io/t/web-interface-to-play-with-the-rholang-language-check-it-out-fam/223?u=rchain_coop

**Comment by jasoncruzzy** [comment]
Reports of RChain Activity on Bounty-one

* 7 post for RChain Discourse made
* Total number of views on RChain Discourse post=228
* 8 Interactions on RChain Discourse post
* 1 professional BlockChain developer(Tutor) Interested 
Check Bounty-one activities here(https://talk.bountyone.io)
Click here(https://talk.bountyone.io/u/rchain_coop/activity) for RChain Profile and activities on Bounty-one

**Comment by pmoorman** [comment]
Hey guys, 

there's an issue that I would like to raise here (holds for this issue, but also potentially for other situations): 

**When one visits the page as it's been created, the impression is that clearly this is an account under the control of the RChain Cooperative. However, this is not the case. (!!)**

Whenever we engage in marketing outreach from the bounty system, we should make it abundantly clear that we're representing RChain as a community effort, rather than being fully managed by RChain in a more traditional kind of sense.

The logo used is also something that wouldn't really fit with how we want to portray ourselves. 

I suggest that either we I) update the account to accurately reflect the situation (that this is managed by an enthusiastic volunteer, rather than an RChain core representative), or II) close the account altogether. 

_(btw, don't take this critique too personal. I think we need to better articulate guidelines for such issues. I'll tag some people below so it can be addressed in the future)_

cc @ian-bloom @dckc @deannald @patrick727

**Comment by jasoncruzzy** [comment]
@pmoorman always verify first from source, I have done my introduction in
the Bounty-one and I clearly stated my position, I could post a link of
that. Don't raise false alarm

**Comment by jasoncruzzy** [comment]
@Pmoorman here is a link
https://talk.bountyone.io/t/introduce-yourself/13/23?u=rchain_coop , are
you clarified now, I hope something more optimistic could be heard now!!

On Jul 30, 2018 17:53, "Emeka Obinna" <jasoncruzzy@gmail.com> wrote:

@pmoorman always verify first from source, I have done my introduction in
the Bounty-one and I clearly stated my position, I could post a link of
that. Don't raise false alarm

**Comment by jasoncruzzy** [comment]
@pmoorman you talked about onboarding developers for RChain but you yet to role out a definite plan for but fault moves made by others. 
1) presenting the RChain the way I did is more viable at this point,  which states the authenticity of the coop
2) In line with being a representative of RChain on Bounty-one, I also resolved to posting RChain approved docs and I have conducted my self there in a professional manner,  that is why last week I earned a reputation there as a "Full Member" I will post evidence of that. 
3) I have discussed this issue with guider @AyAyRon-P 
4) @pmoorman  I think you should talk more on the gains and not on less factors, the Co-Founder of blockgeeks,/Bounty-one commended our efforts and commented on a few of my topics(positively) he also indicated interest to join Which he probably has.

**Comment by pmoorman** [comment]
@jasoncruzzy I don't mean to say that you have any bad intentions, but rather that we all should be more up-front about the fact that we're a community effort rather than an RChain-controlled "official" thing.

Btw, I think this holds much more generally that just this particular issue. 

Please, post a bit more about the interest you've gotten from the community. That's what we're looking for here!

**Comment by dckc** [comment]
In the text of https://talk.bountyone.io/t/introduce-yourself/13/22 I see "I’m Jason a member of the RChain_Coop ..." but the username is RChain_Coop and the avatar is the coop logo. This gives an impression that the 1000+ members of the RChain cooperative have gone through some due process to make you their representative to Bounty-one. Unless I missed something, this isn't the case.

I have similar concerns about the use of the RChain logo / trademark in many of the other channels that bounty system participants moderate (https://github.com/rchain/bounties/wiki/Channels-Moderators ) but at least in most of those cases, @PatrickM727 was part of the process of appointing the moderator. As a coop officer (communications director), he's in a position to speak for the 1000+ coop members.

@jasoncruzzy have you spoken with @PatrickM727 about this? @pmoorman works with @PatrickM727 on such things and as such, I encourage you to take his advice. Change the Bounty-one account name to something like "JasonXYZ" and change the avatar to represent yourself, not the coop.

Note that others in the [RChain executive committee][ec] have similar concerns; from the July 17 meeting:
> ACTION: Add trademark enforcement to agenda

[ec]: https://www.gov.rchain.coop/executive-committee

**Comment by jasoncruzzy** [comment]
@dckc I spoke with @PatrickM727 about the name and logo, clearly stating the position of RChain on bounty-one forum and also requested to retain the name and logo which he did ACCEPT and commended the job done. He approved of it hence the contents generated are sourced from Approved RChain document on our website or other RChain official channels.
