### ISSUE TITLE
Bounty for QQ group management on May

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#794]
### Benefit to RChain

Last month because the trust metrics was turned on and the QQ group maintain team in China didn't have a well understanding about the new rules(3 trusted rating) and all of the votes for the QQ group team don't count at all. So I'm starting a new issue for the reward to make that up.

Feel free to ask if you have any questions.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[3600]**
_Estimated Timeline Required to Complete the Task:_ **[Done]**
_How will we measure completion?_ **[example: pull request merged]**
REFERENCE: #202 
*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by sportshark** [comment]
1.After several months of development, China's QQ group has more than 2500 people and is still increasing, A group discusses technology（Num:492114454）, and a group discusses non-technical topics(Num:530718666),In order to manage such a large number of people, we have hired 10 administrators to manage the QQ group, and assign RHOC according to the administrator's contribution.
2.At present, the Chinese community we organize is very active. We successfully organized a meetup. A video of the party you can see from this link. https://www.youtube.com/watch?v=wxqOlYXny7c&feature=youtu.be
3.We also reached an agreement with Bixin (https://bixin.com/) and Hchain labs (http://www.hchain.com). In the later period, they will vigorously promote RChain's promotion and popularization activities in China. Including contact with the exchange, building community, translation of technical articles, Meetup, and so on.
4.I believe that the current RChain fans will grow into China's effective force and promote the development of RChain in China.

**Comment by pmoorman** [comment]
@sportshark really appreciate the update, and I think you guys are doing great work there in Asia/China. Keep it up!

**Comment by sportshark** [comment]
@pmoorman Thank you，I will do it better!

**Comment by deannald** [comment]
@zsluedem  and @sportshark I love what you are doing for the Chinese community of RChain enthusiasts. Can you give a better breakdown on budget for each of the 4 items you mentioned above (in other words, assign what budget amount you are asking compensation for on each item). Thanks!!

**Comment by sportshark** [comment]
@deannald 
1. budget $3600,First We have 14 administrators to manage two groups of more than 2000 people.Average $214 per administrator budget。Every month, we adjust the administrators, relieve the ineffective administrators, and recruit active ones.At the same time, we encourage all people to publish community and technical articles about RChain. A total of 7 articles were published in May, with an average of $75.
2.Meetup budget is https://github.com/rchain/bounties/issues/724。
3.budget $0,Because we have a huge and growing community, Bixin and Hchain labs are willing to cooperate with us and are willing to cooperate with RChain to become the power to promote the development of RChain in China.
4.In fact, people in the community do video translation, RChain code development, and so on. Of course, there will be separate budgets. Through the community, a cohesive force can be created, and what we want to do is to build a virtual network home for these RChain enthusiasts and provide a platform for the capable ones.

**Comment by deannald** [comment]
@sportshark Thanks for the detailed explanation!

**Comment by dckc** [comment]
In reviewing [rewards for this month][1] I see substantial rewards claimed for **both** this issue and #202. Why are rewards claimed for both? How are they different?

cc @AyAyRon-P 

p.s. @deannald I hope you can follow up on this; I'm heading out for the holiday soon.


[1]: https://rewards.rchain.coop/index.php?-table=reward&-limit=30&issue_num=&title=&worker=&reward_usd=&percent_avg=&budget_usd=&voter_qty=&voters=&reward_provisional=&budget_provisional=&pay_period=06%2F01%2F2018&labels=&-action=list&-cursor=0&-skip=0&-mode=list&-sort=budget_usd+desc

**Comment by AyAyRon-P** [comment]
Hi @dckc 

Seems that jiyuxuan voted this month on the existing ONGOING project for reference of #202 

His votes should have been cast for #794 instead

@jiyuxuan1944 please remove your votes for June from the REWARDVOTES for June

**Comment by AyAyRon-P** [comment]
I'm going to close out #202 and the ONGOING PROJECT will now be this issue #794
