### ISSUE TITLE
FINISHED: Monthly report for RChain community in China

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#803]
### Benefit to RChain

 In the last RAM meeting #800 @allancto have talked that he wants to know what is going on in the Chinese QQ group. Obviously only few people in China would attend the RAM meeting or the debrief meeting every week even if they want to because almost all these meetings would hold at the midnight in China.So the Rchain community in China is actually lack of communication with the core community.
Actually there are a bunch of people keep contributing to the Rchain community in all kinds of ways.

So I would try to reach to the contributors in China and make some reports about Chinese Rchain community.Trying to make the connections between the China community and the core community.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1500]**
_Estimated Timeline Required to Complete the Task:_ **[1week]**
_How will we measure completion?_ **[a google doc report]**

**DRAFT**
https://docs.google.com/document/d/14e7o5EkGdxzZx9cEvOi2n_YsTdZDOsdUSohifMvPKzE/edit#

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by AyAyRon-P** [comment]
Left 2 comments in your draft doc :)

**Comment by deannald** [comment]
zsluedem - This is a great start along the lines of what we discussed on Wednesday. We are still looking for an unofficial blog place for these types of reports to live as the goal is to be able to share this sort of information outside the bounds of the Bounty System. 

For the budget requested, was there going to be more content added or was this budget request restricted to the development of this one+ page Report document?

**Comment by zsluedem** [comment]
@deannald The budget can be adjust by the outcome. I will add more items to the report and try to finish this in two days~

**Comment by deannald** [comment]
@zsluedem Excellent. I look forward to seeing your finished work.

**Comment by kitblake** [comment]
@zsluedem As this is monthly, I added 'Ongoing' to the title.

**Comment by zsluedem** [comment]
The report has been finished. Comments and questions are all welcomed.

**Comment by dckc** [comment]
@deannald writes:
> We are still looking for an unofficial blog place for these types of reports to live as the goal is to be able to share this sort of information outside the bounds of the Bounty System.

Which "we" is that?

The report it's now in the web. It can be linked from anywhere you like. What audience do you have in mind?

**Comment by allancto** [comment]
@zsluedem thanks for this report. I look forward to this becoming a model for reporting on all of our worldwide community building. I have voted a budget of $1500 for this piece of work because it provides us all with an outstanding model. I encourage others to vote a budget on this issue. Also @zsluedem I've included rewards votes for those you recognized in your report for their (direct or indirect) contributions to it- for now I suggested 5% each @wangjia184 @rjl493456442 @hcl3 @sportshark @v56700 @maolulu?, please let me know if you recommend adjusting the %rewards in any way. 

I have changed the "Marketing" label to "Community Building" because Community Building represents a more comprehensive level of commitment in which the elements of marketing, translation, education and software development and so on all happen. 

Thanks @zsluedem for this great report, for the work you're doing, for the opportunity for us to recognize you and your community, and for providing a great example with your Community Building process. 

-@allanto

**Comment by dckc** [comment]
@allancto writes:
> ... I have changed the "Marketing" label to "Community Building"

That makes this an [unguided task][1]. That doesn't seem like a step forward.

[1]: https://github.com/rchain/bounties/wiki/Bounty-Task-Guides#unguided-tasks

**Comment by zsluedem** [comment]
@allancto Thanks so much. I really appreciate it . Of course , I'd love to to adjust the budget and the reward if every one is Ok with it.
