### ISSUE TITLE
Summarized article on What is RChain all about? 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#820]
The article on the video What is RChain all about? 
The article is a written piece on what was talked about in the video, it would assist the RChain community by making the video more accessible to those who for some reasons couldn't watch the video, or those who watched it without understanding fully what it talked about. 

- [What is RChain about-video](https://youtu.be/f1D4vowiMiI) 

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[14days]**

###Legal  

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by BelovedAquila** [comment]
How about now @jimscarver

**Comment by jimscarver** [comment]
I am not a marketing guide but I'd like to see a budget and potential readership based on publication venue(s) and promotion.

**Comment by BelovedAquila** [comment]
Intend placing a budget after completion and was considering creating the article and having it circulated on social media after approval.

**Comment by jimscarver** [comment]
Can youy give an approximate budget. It can always be chaned.
I suggest you add publishing personally upon completion and feed back here to your objectives. The intent to circulate on social media in the event of approval and publication by the coop can be mentioned but it might serve a community building function in our networks having value in itself.  Official publishing by the coop is is tough and not to be counted on in my view.  The venue could be private like facebook friends or given some encouragement here, publicly on medium, linkedin, reddit etc.
I guess I just think there should be something about dissemination in the objectives so that some value to rchain can be assured.

**Comment by allancto** [comment]
@BelovedAquila if you want to do something on this let me know. It's an awesome video and I'd be interested in your thoughts. In the meantime, I'll mark it wontfix until you decide what you want to do. 

Thanks! -@allancto

**Comment by pmoorman** [comment]
I'll close this given the `wontfix` label. If anyone wants to pursue this further, feel free to reopen again
