### ISSUE TITLE
RChain Membership Signup Explainer Video

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#854]
In the last video (#793) we gave an overview of the decentralized RChain bounty budget and reward system. In this next video we introduce how you might participate in that system.

 - [x] Develop [the Script ](https://docs.google.com/document/d/12IQeQ7MJNMrZ2PVMCk-_G3OuYx5EWbnHxgjvbbzRP-A/edit#)for the Voice Over, 
 - [x] Grab screenshots for steps in script
 - [x] Record and edit the Voice over in studio
 - add special effects and highlight areas
 - [x] Import all elements, audio and compositions into the timeline for main editing & post production
 - [x] Handover of [final video](https://www.youtube.com/watch?v=YHgwkvoxUfY) and loading to Youtube for link sharing etc etc

Estimated Budget : 2200$
Estimated Timeline Required to Complete the Task: Work in Progress to be delivered end of month.
improvements will be delivered continuously, budget estimate is for july work. A project backup will be executed for future tweaks and updates the the main working project file.

**Comment by TrenchFloat** [comment]
@Cryptovideos Can you explain how you got to your budget proposal?

**Comment by tucsonblockchain** [comment]
@Cryptovideos asked: @Cryptovideos Can you explain how you got to your budget proposal?
Answer: 
I logged into my GitHub account after I obviously had previously registered. I then clicked the #854 link as provided in the previous email from @jimscarver: Assigned #854 to @tucsonblockchain. which in turn took me to this very page.[](https://github.com/rchain/bounties/issues/854)
So in this case, I saw it in the email that came inbound from gitter (went to my email) and clicked on the #854 which took me to this page, so it's how I was copied in and able to pay attention to the conversation. This was a good way to prompt me into looking into it. Had I not been prompted and seen it in this fashion, it would be difficult to find it per se.

**Comment by TrenchFloat** [comment]
@Cryptovideos We (the label guides) are pushing for more budgeting based on the product's value to the coop rather than budgeting based on time or effort spent. Can you tell me why you claim this video to be over twice as valuable than the last video in #793?
In any case, it is difficult to determine the value of a marketing or educational product before we know the scope of its audience. Some stats on previous videos of yours might help us estimate this, but a good system might be to reward you some now up front and more later depending on the reach of the video

Who are your collaborators? Are they in the bounty system or elsewhere?

**Comment by Cryptovideos** [comment]
Yes tks Kyle- appreviate the label guides query...

Just to fill you in this is a jouney im walking out with Jim
1) as mentioned above already part of the budget will need to be paid to tucsonblockchain for assisting with the content for the video 

2) yes you are correct #793, some of my animated character rigs and had already been created in a previous video -thus i did not need to charge extra to create new stuff, i utalized some tools i already had" if that makes sense? " helping to shave time. hence the lowe amount compared to even more previous videos iv created before issue 793, so i try keep costs down as much as pos.

3) No, i dont agree with you regards part payment at all.... as iv not included into my budget to Pay for boosting and paid reach for this video..if thats the case ill in fact need to increase the budget - time is in fact not the only measure, its the effort and all else involved to do video production... not sure how else i can make myself any clearer? The value is epic for new member as well - see the first draft here and perhaps itll help shed some light? 👍 https://www.youtube.com/watch?v=YHgwkvoxUfY

remember - these need to all get added to the offical Youtube channel for the Coop

**Comment by jimscarver** [comment]
@TrenchFloat this is enterprize spawned #video-colab originating with gary transcriptions of videos. @entropee @tucsonblockchain and Owans have contributed and are eligible to receive some bounty. I think we allowed for $400 in the budget for others.  How much of that we will spend is TBD.

**Comment by tucsonblockchain** [comment]
I think we need to bring this to the Rchain Debate Arena where we can play
the videos produced, discuss - not debate necessarily, though that could be
healthy, but do so via civil discourse as a team. I think the Debate Arena
is perfect place for such discussion for transparency and ideas and
multiplicity and to see the process play out.

**Comment by tucsonblockchain** [comment]
Jim, could we put in for bounty to bring this motion forward with Debate
Arena and seek consensus and approvals and use it as a proving ground? The
RAMS get the benefit of the process, can chime in, and somene's work can't
go unnoticed. That is the value proposition I see above contributing to
dialogue and scripting of such videos.

**Comment by jasoncruzzy** [comment]
@Cryptovideos you did a very job with the explainer video,  I see this will go a long way to provide guide. Nice work!

**Comment by Cryptovideos** [comment]
Hey Andrew yes...this video and a few others are needed to be added there on the offical Youtube Channel... so ill definatley put a push on that on the next Ram meeting..again...thanks to all for the positive feedback..much appreciated

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nonnykul** [comment]
@crptovideo

Nice Video, the video depicts the name of the issue **RChain Membership signup Explainer video** , it would be helpful to push the video to the next RAM meeting to clarify your stand on the budget, and again Nice video.

**Comment by tucsonblockchain** [comment]
https://medium.com/@tucsonblockchain/rchain-cooperative-membership-sign-up-join-the-scalable-blockchain-application-experience-1258cb4bcf7e Here is the scripting I did and posted it on Medium. Criticize it if you wish, but did the best I could and did it step by step with hopes people would see it and sign up given what I feel was proper instruction. i don't think quality of previous work matters much, nor what I do in the future. But I am open to criticism positive or negative in the here and now.

**Comment by jimscarver** [comment]
I think we just need to answer any questions. Questions do not mean anything is being disputed. If any dispute arises, we might debate it in loomio.

The video work product for july is https://www.youtube.com/watch?v=YHgwkvoxUfY

**Comment by Cryptovideos** [comment]
Nice work Brent

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jimscarver** [comment]
This turned out the due to great teamwork less effort than expected was involved and while I feel the work is worth every penny the team agrees to reduce the budget to $1600. 

While label guides are free to exercise their personal values I suggest that the coop is as concerned with rewarding cooperation on activities in line with coop objectives encouraging experimentation as it is with value ultimately produced.  I feel the success of the cooperative depends on recognizing and rewarding cooperation.

The bottom line in [this article](https://onemarketmedia.com/2010/03/03/what-does-a-web-video-cost-25-factors-with-prices-that-affect-video-production-costs/) on video production costs is "A two to three minute web-based corporate video presentation might cost between $2500 and $10,000 if you consider the mid range of variables mentioned above. For most professionally produced web-based corporate videos you should consider between $2,000 to $5,000 as a starting point, that will give you a reasonable idea of where to begin in the budgeting process."

Including the planning, scripting, and video production, and the high quality of the result I think the value produced is greater than the original budget. The cooperation involved was also exemplary.  Low budget video production by 3rd parties generally excludes the cost of the 1st party time and effort going into developing the concept, scripting and other engagement with the video producer and the actual cost is much higher than just the video creation.

**Comment by tucsonblockchain** [comment]
I tested the waters, I did what was asked to do, to get something on the board, the process was not anything I would want to continue doing, asked to redo something I did to a T, but you slide something in with a reasonable expectation and then some guide pops in questioning work. I can see it would be how people drop like flies, but being free to say what I want as it relates to collaboration, or overreacting to others, I would say it's not a system that is for me. So I tested the waters, certainly want to bank my future on this system. I'm on strike until I see something reasonable, or even the Rhoc discussed, but I wouldn't even so much as enter "an issue", certainly wouldn't say anything beyond the next (period).

**Comment by jimscarver** [comment]
Het Brent. You did great work and I see you are getting bounties for july on several issues.

It seems you do not like us questioning each others work here. Evaluation is a necessary part of everything we do in the coop and we reward people to asking about an issue or what was accomplished. Guides help insure that process is done.

You do not have to quite. Ask me or someone else to answer any question you prefer not to answer. There is no reason to object to questions since nobody knows everything and if what they think is wrong we benefit by straightening them out.

We must accept that in cooperation nobody gets their way exactly and  not everything is perfect yet.

**Comment by TrenchFloat** [comment]
First - everybody involved with this video did great work and deserves a fitting reward. My intention in asking questions was not to stifle discussion but to foster it.
@jimscarver I hadn't considered your points about rewarding cooperation. If we're splitting hairs, I would count that as value to the coop, but in any case, the value of cooperation itself was not something I considered before now - nor did I know this project had a sizable team when I asked my first questions.
>Guides second guessing the budgeting after the end of the month can be demoralizing to the members.

Discussing budgeting once the work is done is a guide's job, no? The rewards app says the first vote on a budget or rewards didn't come until July 30. Again, "second guessing" was never my intention, only to seek transparency (which we found).

@tucsonblockchain I apologize to have ever come across as criticizing or questioning your work. I hope you stick with us, as it is evident you do good work. As Jim said, this system is a work in progress, and I appreciate your concerns. I'm voting $2200 for the budget of this issue.

**Comment by tucsonblockchain** [comment]
Kyle, point well made. You are not the problem, so don't feel you are. I am
stubborn and lost patience in going around and around in the "process",
redoing things, and realizing the amount of downtime in the overall process
that seemed overly complicated given the simple task at hand, down to the
point it did not seem to be profitable in terms of amount of time it took.
Stubborn enough that I would not enter "issues" even if it is the process.
You have to understand I am used to doing a job and multitasking and
checking it off my list, and moving on to th next one - without someone
telling me what to do, all with quality in mind. I don't see myself
changing either! So don't take it personal when some of us just want to
work, and take some things on and even do as asked, but I work
independently and didn't have all the information of the process, but
didn't agree with it when it just ate up time. And then voting came up? I
didn't think I was even going to get paid Rhocs given that I wasn't willing
to continue in the process when it never ended! So it's not you, it's me. I
don't know everything. I am far from perfect. I do not take offense. This
is my social contract.

**Comment by AyAyRon-P** [comment]
Hi @Cryptovideos @TrenchFloat @jimscarver 
Are there any updates? Do we need to vote on this for the month of August? It seems to be completed and hit the objectives. Let me know what your thoughts are on budget for the month so we can vote accordingly if this requires guide voting.

**Comment by Valentine-Mario** [comment]
More work was done on the issue this month, concerning using the rewards app. I wrote the script to guide the video creation on using the rewards app

**Comment by Cryptovideos** [comment]
That is another video...not 854

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tucsonblockchain** [comment]
Membership Sign Up: Doc shows up to step 16. - There is a step 17, 18, and
19, for your information. I updated the working doc and Medium article
accordingly. To eliminate confusion, step 19 shows how to join Rchain
Google Group as it was sort of a missing piece of the puzzle so to speak.

**Comment by AyAyRon-P** [comment]
Hey @jimscarver @Cryptovideos 

So I understand the 2200 that was billed last month and there has now been a second video added to this one? If that is the case can you please add the PART 2 into the original issue for clarity?
