### ISSUE TITLE
Translate a total 11 Top Post on Ukrainian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#865]
Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 90%
@qelentium: 10%

**Estimated Budget of Task: $ 1675**

Estimated Timeline Required to Complete the Task: **10** 
How will we measure completion? **Fill the Translated Content section below. Also, will be posted on the [RChain Cooperative Medium account(Ukrinian)](https://medium.com/@rchain_ukraine/)**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

**Original (English) Content:**
[Running RNode(v 0.5.1) with Docker](https://blog.rchain.coop/running-rnodev-0-5-1-with-docker/) 
[RChain Cooperative Presents RCon3](https://blog.rchain.coop/rchain-cooperative-rcon3/)
[Building a New Blockchain Without Reinventing the Wheel: Part 1](https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/) 
[Introduction to rho calculus](https://blog.rchain.coop/intro-to-rho-calc/) 
[Runway Interview: The Future of Blockchain](https://blog.rchain.coop/the-future-of-blockchain-event/) 
[RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5) 
[RChain Weekly Update (Debrief 83) 27th June, 2018 ](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500)
[RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0) 
[RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) 
[RChain update (Debrief 86), July 18th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) 
[RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) 

**Translation:**
[Запуск RNode (v 0.5.1) за допомогою Docker](https://docs.google.com/document/d/1xl3S3q67sU4C-pU7hv-hQBwYwzeXffwkMuUiLMH3rtQ/edit?usp=sharing)
[RChain представляє: блокчейн RCon3 конференція в Берліні](https://docs.google.com/document/d/1vYbQEes0bl8Jx9L3FYKZEHC38DRYnetKnA8TcawJrto/edit?usp=sharing)
[Створення нового блокчейн без винаходу колеса: Частина 1](https://docs.google.com/document/d/1NqosJ1ywq3lYUhB09vM-nWhp7FDGUqxGdQiFP8_udAU/edit?usp=sharing)
[Введення в rho-обчислення](https://docs.google.com/document/d/1RBh8YJkAPaQ7A4wGkrXotjiHZHDMaVlSHZYC9UTQxk0/edit?usp=sharing)
[Інтерв'ю: майбутнє Blockchain](https://docs.google.com/document/d/16hkub9opeew2yxvxWwwy2dJXlT18_9w6Jnm8WrXvQRk/edit?usp=sharing)
[RNode v0.5.1 пропонує всі функції, необхідні розробникам dApp для написання та транзакції інтелектуальних контрактів на платформі](https://docs.google.com/document/d/1nPr43JtRjToFgeELxlcBhYqeEv4dkyJHLyWg_3Zx7E0/edit?usp=sharing)
[Щотижневе оновлення RChain (Pозбір 83) 27 червня 2018 року](https://docs.google.com/document/d/1pmUSVQF7RN4HKqHzJ-r7D9btRajRkujlX_ZxOZdZ7zg/edit?usp=sharing)
[Щотижневе оновлення RChain (Pозбір 84) 4 липня 2018 року](https://docs.google.com/document/d/1cY4tKzieoRset0p4CqUy96zBEb_cuwR-sYvKL0aUeZE/edit?usp=sharing)
[Щотижневе оновлення RChain (Pозбір 85) 11 липня 2018 року](https://docs.google.com/document/d/1dU4ZQCf8qfF9qlRX8oElPR8W0wXTLls3WdWF3JowUlw/edit?usp=sharing)
[Щотижневе оновлення RChain (Pозбір 86) 18 липня 2018 року](https://docs.google.com/document/d/1l-YodCgC_uS9t47CCPmYVxKDAwgsKDlDLEvz_dvkoDI/edit?usp=sharing)
[Щотижневе оновлення RChain (Pозбір 87) 25 липня 2018 року](https://docs.google.com/document/d/1unQyMy_m6-7AnRyjvtfvbuyWCXsnSUh66mVmwAkRas8/edit?usp=sharing)

**Comment by AyAyRon-P** [comment]
@kovmargo 

- If you're posting on the RChain Medium account - I'm assuming then  you will place these in markdown text? 
- What other value added content will you be posting along with these debriefs, medium posts, RChain blog posts? 

Other thoughts:
- Is there an audience to support the need for this to be translated? 
- What is the Ukrainian community  
- What is the value to RChain having these translated? 

The metrics to this completion should be the number of views/likes/etc not simply completing the translation. We need to make sure that the right audience is reading these, because if no one reads these then there is no purpose to translation. 

Please also provide the word count for each debrief and use this [tool ](https://customer.stepes.com/instant-translation-quote/#)for budget estimation. 

cc @pavlos1851

**Comment by pavlos1851** [comment]
@kovmargo I see a budget of 3500$ which is 1824,95$ higher that it should have been. In #863 you had initially provided a word count, then went on and deleted it, removed ukrainian, and despite that, left the budget unchanged. In this issue, you did not provide a word count (Even though you obviously know how to do it and that it's required) and you somehow came up with a budget of 3500$. Please explain yourself because your actions so far seem questionable at the very least and warrant a slashing of your issues' budgets.

Here is the word count and the appropriate budget:
[Running RNode(v 0.5.1) with Docker](https://blog.rchain.coop/running-rnodev-0-5-1-with-docker/) 585 Words $76.05
[RChain Cooperative Presents RCon3](https://blog.rchain.coop/rchain-cooperative-rcon3/) 430 Words $55.90
[Building a New Blockchain Without Reinventing the Wheel: Part 1](https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/) 885 Words $115.05
[Introduction to rho calculus](https://blog.rchain.coop/intro-to-rho-calc/) 1,124 Words $146.12
[Runway Interview: The Future of Blockchain](https://blog.rchain.coop/the-future-of-blockchain-event/) 808 Words  $105.04
[RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5) 892 Words $115.96
[RChain Weekly Update (Debrief 83) 27th June, 2018 ](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500) 1,187 Words $154.31
[RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0) 786 Words $102.18
[RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) 1,666 Words $216.58
[RChain update (Debrief 86), July 18th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) 2,913 Words $378.69
[RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) 1,609 Words $209.17

Sums: 585+430+885+1124+808+892+1187+786+1666+2913+1609=12885 words
76,05+55,9+115,05+146,12+105,04+115,96+154,31+102,18+216,58+378,69+209,17=1675,05$

**Comment by kovmargo** [comment]
@pavlos1851 yes, first, I create issue for translation both - Russian and Ukrainian languages, then I found that Debriefs 83-87 are not translated on Ukrainian yet and I decided to split the issue - one for Russian #863 and second for Ukrainian #865. 

According the budget, it's very tricky for me how it should be count, to be honest. I found the similar articles in another issues (translate English to Greek) and copy-past the same data(amount of words and price) for articles, that I had to translate. But some article(s) were nor repeated and I could not set a price.... Thats why I start to serf another issues and didn't find the formulas for price depending on the number of words. So I found the articles that was translated on Ukrainian and set the average value depending on the number of articles. 

Now, I research better the World's Fastest Human Translation Service and found that I did not follow through to the end - I stopped at counting the words -  and this ignorance pushed me to search for similar issues.... It's definitely my fault, and I'm ashamed that set so big budget (already changed). Thanks that pointed me!

**Comment by kovmargo** [comment]
@AyAyRon-P The translations will be posting on the RChain Medium account in markdown text; I'm going to create Facebook account with the aim to popularize RChain and involve people/developers to the coop. I think, I will post some of this articles or all (now discussion about it at the #862 issue). I thinks, it will be better to add short summary to each article or explanation in short form to get better traffic (one of the value)

<<What is the value to RChain having these translated? Please provide 3 objectives in your proposal.

As I tell above, it will be good base for Facebook.
It's a way to development: translation makes articles and ideas more accessible;
number of views can be analyzed and you can trace the people's need to open new directions and new understanding.
Translation is a good part of Regional marketing: because the people, who makes translation familiar with the regions and having a good knowledge of what is most effective for each region for on involving new developers. Ukrainian-speaking people will better trust you if you are speaking Russian, this will add more insight, answers to questions. Blockchain technologies are increasingly being embraced as potential solutions for Russian/Ukrainian nations and people need to know what RСhain can do for them.

**Comment by kovmargo** [comment]
@thiefintheshadows Could you please provide me with credentials for Medium RChain Ucrainian account ? I’m going to post transactions. Thanks!

**Comment by kovmargo** [comment]
Work is done. Translations are stored on the docs now and will be posted at Medium RChain (Ukrainian) account as soon as @thiefinshadows provides me with credentials. 

@AyAyRon-P  @pavlos1851 I've tried to contact with @thiefinshadows on Discord and on his issues #873... I see that he has activity but does't answer. I would like to believe that he is interested in the overall contribution to building community in the Russian-speaking world. 

Closing this issue
