### ISSUE TITLE
RChain: The Journey So Far. 

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#890]
### Benefit to RChain

*Part of periodic articles to keep community members updated:*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[Ongoing/2 weeks]**
_How will we measure completion?_ *Publication*
[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities.

*My deepest regards to @Lapin7*

**Comment by pmoorman** [comment]
I'll close this issue, because the goal & description are so empty that even a `needs-SMART-objectives` seems like a stretch.

@ResonanceXX if you want to re-activate this issue, please add a (much) more specific description of what you plan to do. Now everything is just a bunch of scaffolding & placeholder text
