### ISSUE TITLE
RChain Thai Community First Meetup (Bangkok)

### ISSUE THREAD

**Issue by vkhansen** [rchain/bounties#917]
•	Lecture to propagate RChain and explain why it is revolutionary by comparing its scalability / concurrency / compositionality with traditional von Neumann style computing.
•	Lecture to introduce Rholang to BKK developer community
Time: 2018-08-22 18:30 UTC+9 (Indochina Time)

Location : The Hive Soi 49, Rooftop
46/9 Soi Sukhumvit 49, Khwaeng Khlong Tan Nuea, Khet Watthana, Krung Thep Maha Nakhon 10110
Attendees : Williams Sissoko

Media:
•	Partial video recorded by Wassana & Viggo
•	Photos taken by photographer (will upload later)
Agenda:
1.	Introduction to Rchain:
Slides: https://docs.google.com/presentation/d/1C-Xf68jEJUJULofemg3ZL9BBRcf-vuQ6afJTQDXfebc/edit#slide=id.g3dac6137f7_1_0

2.	Introducing Rholang (Greg) explains Ethereum ERC20 token in Rholang:
 https://www.youtube.com/watch?v=7tW1fAWg6s8
3.	Review Rchain Tutorial and live examples:

i.	https://joshorndorff.github.io/LearnRholangByExample/
ii.	https://developer.rchain.coop/tutorial/
iii.	See example contracts in /usr/share/Rnode

4.	Introduction to running Rnode on Ubuntu VM
i.	Explain how to install Rnode for testing
ii.	Go through process of starting Rnode within Ubuntu VM
iii.	Eval and REPL modes
	Evaluating contract cost
5.	Free Talk, small group discussion
i.	Go through tutorial material

Effort & Cost
1.	Advertisement & Organization (Facebook, meetup.com)
2.	Meeting Venue Fee (12,500 Baht ~ $381.91) (http://thehive.co.th/location/ )
3.	Photographer (1000 Baht ~ $30.59)
4.	Speaker spent several days to prepare for lecture and learning how to setup Rnode. (remaining funds)
Budget of Task: $600

Timeline Required to Complete the Task: 3 days 
Measure of Completion: **We successfully carried out this meetup. Attendance was low due to rain and there were several cancellations, will try again next month with more advertising, the venue offered to assist with this.**

Person	Discord ID	GitHub ID	What she/he did	Percentage
Viggo Hansen	Viggo#0485	vkhansen	Lecture/Review Rholang 1-on-1	100%
-- 
Legal 
Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

[RChain_Github_Summary.docx](https://github.com/rchain/bounties/files/2313995/RChain_Github_Summary.docx)

**Comment by Ojimadu** [comment]
@vkhansen Good work on this, what do you think would make the next meet up better? What problems did you face trying to set this meet up? Are the pictures available yet?

**Comment by Ojimadu** [comment]
The venue is nice. 

> Overall I think the most effective way to recruit people will be visiting other related meetups in BKK and building it in a grass roots way, which takes some time.

Good. For future meet ups, I would suggest that instead of advertising online, you reach out to communities within reach around Bangkok like universities, polytechnics etc. Also try forming a local chat group that might be interested in blockchain/development and general technology and have discussions around it.

**Comment by allancto** [comment]
@Ojimadu , all. I am voting $1600 rather than the $600 suggested. @vkhansen obviously spent a lot of time on this in addition to out of pocket expenses listed above. The work he did in proposing issue #929 (and possibly #930) is probably directly related to what he did setting up the meetup here. We should certainly reward at least what @vkhansen proposed, but taking a broader view @vkhansen's overall contribution during August was more significant than what's written and we can recognize that. 

@vkhansen thanks for contributing. You've made two significant, thought provoking proposals during August and made a difference. Please accept our appreciation and continue to keep RChain front and center in your aspirations and your activities. -@allancto

**Comment by Ojimadu** [comment]
@allancto I wouldn't suggest raising the budget above $1,000 because of the budgeting requirements of the "local meet up wiki". If work is done on other issues I'll prefer it's reflected on the issue rather than here.
@Ojimadu

**Comment by dckc** [comment]
I see rewards were issued in the 201808 pay period.
