### ISSUE TITLE
Usability Testing and Updates to e-sign Invoice

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#965]
When filling in the RContributor Invoice Agreement form, I noticed some usability problems and hit a bug.

- The Ethereum address field is too short. It should display 42 chars: size="42"
- The Reward Voted field should only accept numeric chars. 
- Placing a Dollar sign to the left of the Reward Voted field would be a useful hint.
- Displaying placeholder text in the Reward Voted field would mitigate confusion about the amount format: placeholder="1234.56"
- Typically the positive button ("I Agree") is located on the right in order to move forward. The negative button ("I Disagree") should be on the left to indicate non-continuation. Or, the buttons should be stacked, with the most likely course of action ("I Agree") on top. 

After clicking the "I Agree" button, a Javascript alert pops up saying:

```Data provided doesn't match the values on file.```

Afaik the data matches the invoice. This alert appears regardless of what I enter in the Reward Voted field: #### | #,### | ####.## | #,###.## | $####. 

Bug: the md5 checksum generated in the Javascript for my ETH address is incorrect. 

Since the form can't be submitted due to the alert, I clicked the ("I Disagree") button. The form submitted. It went to invoice.rhobot.net/../disagree and replied "Thank you for contributing!". Maybe it should say "Thank you anyway!".

**Comment by owans** [comment]
The process was also smooth on my end

**Comment by nonnykul** [comment]
The process was Smooth and precise

**Comment by allancto** [comment]
@kitblake thanks for your well considered feedback. 

1. BUG (fixed): the md5 checksum generated in the Javascript for my ETH address is incorrect.This was indeed a bug. We neglected to treat eth_address as a number and ended up with a case sensitive comparison of text. @kitblake gets extra points for reading the client javascript 👍 

2. DESIGN FLAW: there was no positive confirmation of receipt, this will now say something like "Agreed at <timestamp>". Thanks to @zsluedem. 

3. UX amount. The purpose of this field is to positively confirm that you have actually read and are agreeing to the pdf. So i suppose it might say "Please confirm "Total to pay" matches the reward voted for your contributions" rather than "Please agree to the reward voted by entering the amount below". On the other hand it does say "Please check your invoice carefully and confirm the information below."  Anyone who has an opinion about this, feel free to speak up! 

4. UX eth_address. this is a bit complicated so i'll put it in a separate comment. 

5. Button location. Is on the right more typical? Is there a ux design principles or equivalent link you can provide confirming this? we should absolutely conform to standard practice. 

6. Popup. This is absolutely lame, you are correct, should be fixed soon. Our design is for sequential enabling of ux elements. We took a shortcut to get this version out more timely. 

Thanks! -allancto

**Comment by allancto** [comment]
@kitblake , about the description of the eth_address text. I agree that it's bad UX, the reason is we haven't found a simple way of describing the purpose of this field. 

Here's the purpose. It's a safety check for you. We have had a small but significant number of cases in the past where contributors change eth_addresses for various reasons (expose a private key in a Colab video, for instance). Transmitting to an incorrect eth_address would be problematic. The screening we provide, as you point out written in the javascript, is a simple comparison of the hash you provide against the hash we have on file. 

How to communicate this with an intuitive and simple UX? -@allancto

**Comment by allancto** [comment]
@kitblake , @all. 

The question has been raised again as to whether language in the board resolution of Jan 25 should be interpreted to protect bounty contributors against rhoc market price fluctuation during the time between contribution pay period and payment processing. I believe that this protection was unintended and we should remove ambiguous language in the invoice form itself. 

Here is a draft email I am proposing to seek consensus to change the invoice language to reflect this. Please comment below if you disagree with this email and with making corresponding modifications to the e-sign agreement. 

DRAFT 
Dear Kate and Kenny

The recent market valuation of rhoc has raised once more the question of how to interpret the clause in the Board resolution of Jan 25, 2018. It's possible this clause was either intended to cover a situations other than the bounty system or perhaps was simply a "bug" around which now we have clearer understanding. Our actual practice has been to use the monthly average interpretation for rewards, except for a one time special adjustment on June 20 when the issue was first recognized. 

I believe i speak for the vast majority of contributors that our actual practice of using the monthly average is fair, appropriate, and aligns bounty contributors with other holders of rhoc. Setting the rhoc rate to an average price for the month in which contributions were made seems clear and correct. Any adjustment places bounty contributors in a different situation than other rhoc holders, a situation we do not wish. 

Going forward I propose we change and simplify the invoice agreement to reflect our actual practice. Attached below is a copy of a proposed invoice format which reflects this. Please let me know if you have any objections to bounty contributors using this simplified format and unambiguously e-signing this rhoc denominated agreement at the monthly average rate. 

Thanks!

attached: simplified invoice format [link] reflecting our actual practice by removing text "Exact Units are set by Board at date of payment", "Units (indicative)", and "Coin..Eth".

**Comment by allancto** [comment]
I sent the email drafted above just now to @kate and @kennyrowe cc @lapin7, representing my understanding that it's the consensus of contributors. I included a reference to this issue and comments. If anyone disagrees that the average price for the month in which contributions were made is appropriate and desirable in order to align your interests with those of fellow members and fellow rhoc holders, please comment below. 

Thanks! -@allancto

**Comment by dckc** [comment]
If this is development, somebody point me to the source code, please.

**Comment by whereyouatwimm** [comment]
@dckc apologize for the delay, haven't been keeping up with github as much as i should.

https://github.com/whereyouatwimm/rchain-invoice

**Comment by dckc** [comment]
I suggest tweaking the scope (i.e. title) of this issue to something like "usability testing of rchain-invoice".

**Comment by dckc** [comment]
Has the treasurer started trying this thing out? If so, please summarize the results. If not, please make (and share) plans for that.

**Comment by dckc** [comment]
@allancto you've contacted the compensation committee, which is the right place for the discussion, but in case anyone only looks here...

> I sent the email drafted above just now to @kate and @kennyrowe cc @lapin7, representing my understanding that it's the consensus of contributors. I included a reference to this issue and comments. If anyone disagrees that the average price for the month in which contributions were made is appropriate and desirable in order to align your interests with those of fellow members and fellow rhoc holders, please comment below.

1. Clearly #969 is the more relevant issue; I don't think it's reasonable to expect all bounty system contributors to express their position on USD/RHOC conversion rate for invoices under "usability testing..."
2. There is evidently not a consensus around using the monthly average. @AyAyRon-P disagreed in https://github.com/rchain/bounties/issues/969#issuecomment-422128176 and @barneycinnamon and I argued that the Jan 25 board decision applies until it's changed through due process.

**Comment by allancto** [comment]
@dckc yes, i created #969 AT_TIME_OF_CONTRIBUTION vs AT_TIME_OF_PAYMENT to have the discussion. It's also true that I sent the email without consensus yet and that's why i raised #969. In that discussion it became clear there was not consensus which i reported and ultimately will result in this question being addressed by the Compensation Committee sometime this week. 

Please help me to clarify in any of the channels you may have noticed any miscommunication on my part. Thanks! -@allancto

**Comment by allancto** [comment]
Work done in September. 

* Usability upgrades 
  1. @zsluedem06 (positive confirmation) the app now provides a time stamp for signed time. 
  2. eth address 42 characters
  3. $ hint as suggested 
  4. left/ right research indicated [cancel/continue](https://material.io/design/components/dialogs.html) different ux than [agree/disagree](https://www.shutterstock.com/search/disagree+button) 

* bug fix
  1. eth address case sensitive

* handling of Sept 28 scramble. 
  1. 84% "over" rewards returned, 11.5% likely but still pending, 4.5% refused
  2. all "under" rewards properly distributed (with no errors reported!)
  3. Is this rewardable? actually it caused a lot of problems for a lot of people, perhaps worthy of NEGATIVE reward. On the other hand it took a lot of work to track properly, notify, resolve, get correct adjustments sent. 

Suggested reward: 
@whereyouatwimm 1000
@allancto 3000 (OR 1000 for items 1 and 2)

**Comment by dckc** [comment]
After discussing this with @allancto and some others in the coop who work with budgets in this area, I supported this work with a $2K budget vote, with the expectation that @allancto and @whereyouatwimm will split it.

More to follow under #912 .

reminder: you can do your own reward votes in 201809; see #785 .

Regarding my question above, @allancto wrote in #bounties:
> yes Kate has said "I like it" :p.

**Comment by dckc** [comment]
This looks done.

If it's not please clarify what work is left to do and how we'll measure completion.
